package com.notice.model;

import java.math.BigDecimal;
import java.util.Date;

public class SysDbLinks {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_DB_LINKS.LINK_ID
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    private BigDecimal LINK_ID;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_DB_LINKS.LINK_CODE
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    private String LINK_CODE;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_DB_LINKS.DRIVER_CLASS
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    private String DRIVER_CLASS;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_DB_LINKS.URL
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    private String URL;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_DB_LINKS.USER_NAME
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    private String USER_NAME;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_DB_LINKS.PASSWORD
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    private String PASSWORD;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_DB_LINKS.DESCRIPTION
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    private String DESCRIPTION;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_DB_LINKS.ENABLE_DATE
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    private Date ENABLE_DATE;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_DB_LINKS.DISABLE_DATE
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    private Date DISABLE_DATE;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_DB_LINKS.CREATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    private BigDecimal CREATED_BY;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_DB_LINKS.CREATION_DATE
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    private Date CREATION_DATE;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_DB_LINKS.LAST_UPDATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    private BigDecimal LAST_UPDATED_BY;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_DB_LINKS.LAST_UPDATE_DATE
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    private Date LAST_UPDATE_DATE;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_DB_LINKS.LINK_ID
     *
     * @return the value of SYS_DB_LINKS.LINK_ID
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public BigDecimal getLINK_ID() {
        return LINK_ID;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_DB_LINKS.LINK_ID
     *
     * @param LINK_ID the value for SYS_DB_LINKS.LINK_ID
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public void setLINK_ID(BigDecimal LINK_ID) {
        this.LINK_ID = LINK_ID;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_DB_LINKS.LINK_CODE
     *
     * @return the value of SYS_DB_LINKS.LINK_CODE
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public String getLINK_CODE() {
        return LINK_CODE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_DB_LINKS.LINK_CODE
     *
     * @param LINK_CODE the value for SYS_DB_LINKS.LINK_CODE
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public void setLINK_CODE(String LINK_CODE) {
        this.LINK_CODE = LINK_CODE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_DB_LINKS.DRIVER_CLASS
     *
     * @return the value of SYS_DB_LINKS.DRIVER_CLASS
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public String getDRIVER_CLASS() {
        return DRIVER_CLASS;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_DB_LINKS.DRIVER_CLASS
     *
     * @param DRIVER_CLASS the value for SYS_DB_LINKS.DRIVER_CLASS
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public void setDRIVER_CLASS(String DRIVER_CLASS) {
        this.DRIVER_CLASS = DRIVER_CLASS;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_DB_LINKS.URL
     *
     * @return the value of SYS_DB_LINKS.URL
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public String getURL() {
        return URL;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_DB_LINKS.URL
     *
     * @param URL the value for SYS_DB_LINKS.URL
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public void setURL(String URL) {
        this.URL = URL;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_DB_LINKS.USER_NAME
     *
     * @return the value of SYS_DB_LINKS.USER_NAME
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public String getUSER_NAME() {
        return USER_NAME;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_DB_LINKS.USER_NAME
     *
     * @param USER_NAME the value for SYS_DB_LINKS.USER_NAME
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public void setUSER_NAME(String USER_NAME) {
        this.USER_NAME = USER_NAME;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_DB_LINKS.PASSWORD
     *
     * @return the value of SYS_DB_LINKS.PASSWORD
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public String getPASSWORD() {
        return PASSWORD;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_DB_LINKS.PASSWORD
     *
     * @param PASSWORD the value for SYS_DB_LINKS.PASSWORD
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public void setPASSWORD(String PASSWORD) {
        this.PASSWORD = PASSWORD;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_DB_LINKS.DESCRIPTION
     *
     * @return the value of SYS_DB_LINKS.DESCRIPTION
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_DB_LINKS.DESCRIPTION
     *
     * @param DESCRIPTION the value for SYS_DB_LINKS.DESCRIPTION
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_DB_LINKS.ENABLE_DATE
     *
     * @return the value of SYS_DB_LINKS.ENABLE_DATE
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public Date getENABLE_DATE() {
        return ENABLE_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_DB_LINKS.ENABLE_DATE
     *
     * @param ENABLE_DATE the value for SYS_DB_LINKS.ENABLE_DATE
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public void setENABLE_DATE(Date ENABLE_DATE) {
        this.ENABLE_DATE = ENABLE_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_DB_LINKS.DISABLE_DATE
     *
     * @return the value of SYS_DB_LINKS.DISABLE_DATE
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public Date getDISABLE_DATE() {
        return DISABLE_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_DB_LINKS.DISABLE_DATE
     *
     * @param DISABLE_DATE the value for SYS_DB_LINKS.DISABLE_DATE
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public void setDISABLE_DATE(Date DISABLE_DATE) {
        this.DISABLE_DATE = DISABLE_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_DB_LINKS.CREATED_BY
     *
     * @return the value of SYS_DB_LINKS.CREATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public BigDecimal getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_DB_LINKS.CREATED_BY
     *
     * @param CREATED_BY the value for SYS_DB_LINKS.CREATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public void setCREATED_BY(BigDecimal CREATED_BY) {
        this.CREATED_BY = CREATED_BY;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_DB_LINKS.CREATION_DATE
     *
     * @return the value of SYS_DB_LINKS.CREATION_DATE
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public Date getCREATION_DATE() {
        return CREATION_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_DB_LINKS.CREATION_DATE
     *
     * @param CREATION_DATE the value for SYS_DB_LINKS.CREATION_DATE
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public void setCREATION_DATE(Date CREATION_DATE) {
        this.CREATION_DATE = CREATION_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_DB_LINKS.LAST_UPDATED_BY
     *
     * @return the value of SYS_DB_LINKS.LAST_UPDATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public BigDecimal getLAST_UPDATED_BY() {
        return LAST_UPDATED_BY;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_DB_LINKS.LAST_UPDATED_BY
     *
     * @param LAST_UPDATED_BY the value for SYS_DB_LINKS.LAST_UPDATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public void setLAST_UPDATED_BY(BigDecimal LAST_UPDATED_BY) {
        this.LAST_UPDATED_BY = LAST_UPDATED_BY;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_DB_LINKS.LAST_UPDATE_DATE
     *
     * @return the value of SYS_DB_LINKS.LAST_UPDATE_DATE
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public Date getLAST_UPDATE_DATE() {
        return LAST_UPDATE_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_DB_LINKS.LAST_UPDATE_DATE
     *
     * @param LAST_UPDATE_DATE the value for SYS_DB_LINKS.LAST_UPDATE_DATE
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public void setLAST_UPDATE_DATE(Date LAST_UPDATE_DATE) {
        this.LAST_UPDATE_DATE = LAST_UPDATE_DATE;
    }
}