package com.notice.model;

import java.math.BigDecimal;
import java.util.Date;

public class SysDataSource {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_DATA_SOURCE.ID
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	private BigDecimal ID;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_DATA_SOURCE.CODE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	private String CODE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_DATA_SOURCE.DESCRIPTION
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	private String DESCRIPTION;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_DATA_SOURCE.TYPE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	private BigDecimal TYPE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_DATA_SOURCE.DISABLED
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	private String DISABLED;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_DATA_SOURCE.CREATEDBY
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	private BigDecimal CREATEDBY;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_DATA_SOURCE.CREATIONDATE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	private Date CREATIONDATE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_DATA_SOURCE.LASTUPDATEDBY
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	private BigDecimal LASTUPDATEDBY;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_DATA_SOURCE.LASTUPDATEDATE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	private Date LASTUPDATEDATE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_DATA_SOURCE.ATTRIBUTE1
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	private String ATTRIBUTE1;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_DATA_SOURCE.ATTRIBUTE2
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	private String ATTRIBUTE2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_DATA_SOURCE.ATTRIBUTE3
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	private String ATTRIBUTE3;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_DATA_SOURCE.ATTRIBUTE4
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	private String ATTRIBUTE4;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_DATA_SOURCE.ATTRIBUTE5
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	private String ATTRIBUTE5;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_DATA_SOURCE.LINK_ID
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	private BigDecimal LINK_ID;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_DATA_SOURCE.ID
	 * @return  the value of SYS_DATA_SOURCE.ID
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public BigDecimal getID() {
		return ID;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_DATA_SOURCE.ID
	 * @param ID  the value for SYS_DATA_SOURCE.ID
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void setID(BigDecimal ID) {
		this.ID = ID;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_DATA_SOURCE.CODE
	 * @return  the value of SYS_DATA_SOURCE.CODE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public String getCODE() {
		return CODE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_DATA_SOURCE.CODE
	 * @param CODE  the value for SYS_DATA_SOURCE.CODE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void setCODE(String CODE) {
		this.CODE = CODE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_DATA_SOURCE.DESCRIPTION
	 * @return  the value of SYS_DATA_SOURCE.DESCRIPTION
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public String getDESCRIPTION() {
		return DESCRIPTION;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_DATA_SOURCE.DESCRIPTION
	 * @param DESCRIPTION  the value for SYS_DATA_SOURCE.DESCRIPTION
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void setDESCRIPTION(String DESCRIPTION) {
		this.DESCRIPTION = DESCRIPTION;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_DATA_SOURCE.TYPE
	 * @return  the value of SYS_DATA_SOURCE.TYPE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public BigDecimal getTYPE() {
		return TYPE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_DATA_SOURCE.TYPE
	 * @param TYPE  the value for SYS_DATA_SOURCE.TYPE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void setTYPE(BigDecimal TYPE) {
		this.TYPE = TYPE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_DATA_SOURCE.DISABLED
	 * @return  the value of SYS_DATA_SOURCE.DISABLED
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public String getDISABLED() {
		return DISABLED;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_DATA_SOURCE.DISABLED
	 * @param DISABLED  the value for SYS_DATA_SOURCE.DISABLED
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void setDISABLED(String DISABLED) {
		this.DISABLED = DISABLED;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_DATA_SOURCE.CREATEDBY
	 * @return  the value of SYS_DATA_SOURCE.CREATEDBY
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public BigDecimal getCREATEDBY() {
		return CREATEDBY;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_DATA_SOURCE.CREATEDBY
	 * @param CREATEDBY  the value for SYS_DATA_SOURCE.CREATEDBY
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void setCREATEDBY(BigDecimal CREATEDBY) {
		this.CREATEDBY = CREATEDBY;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_DATA_SOURCE.CREATIONDATE
	 * @return  the value of SYS_DATA_SOURCE.CREATIONDATE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public Date getCREATIONDATE() {
		return CREATIONDATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_DATA_SOURCE.CREATIONDATE
	 * @param CREATIONDATE  the value for SYS_DATA_SOURCE.CREATIONDATE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void setCREATIONDATE(Date CREATIONDATE) {
		this.CREATIONDATE = CREATIONDATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_DATA_SOURCE.LASTUPDATEDBY
	 * @return  the value of SYS_DATA_SOURCE.LASTUPDATEDBY
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public BigDecimal getLASTUPDATEDBY() {
		return LASTUPDATEDBY;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_DATA_SOURCE.LASTUPDATEDBY
	 * @param LASTUPDATEDBY  the value for SYS_DATA_SOURCE.LASTUPDATEDBY
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void setLASTUPDATEDBY(BigDecimal LASTUPDATEDBY) {
		this.LASTUPDATEDBY = LASTUPDATEDBY;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_DATA_SOURCE.LASTUPDATEDATE
	 * @return  the value of SYS_DATA_SOURCE.LASTUPDATEDATE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public Date getLASTUPDATEDATE() {
		return LASTUPDATEDATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_DATA_SOURCE.LASTUPDATEDATE
	 * @param LASTUPDATEDATE  the value for SYS_DATA_SOURCE.LASTUPDATEDATE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void setLASTUPDATEDATE(Date LASTUPDATEDATE) {
		this.LASTUPDATEDATE = LASTUPDATEDATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_DATA_SOURCE.ATTRIBUTE1
	 * @return  the value of SYS_DATA_SOURCE.ATTRIBUTE1
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public String getATTRIBUTE1() {
		return ATTRIBUTE1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_DATA_SOURCE.ATTRIBUTE1
	 * @param ATTRIBUTE1  the value for SYS_DATA_SOURCE.ATTRIBUTE1
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void setATTRIBUTE1(String ATTRIBUTE1) {
		this.ATTRIBUTE1 = ATTRIBUTE1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_DATA_SOURCE.ATTRIBUTE2
	 * @return  the value of SYS_DATA_SOURCE.ATTRIBUTE2
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public String getATTRIBUTE2() {
		return ATTRIBUTE2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_DATA_SOURCE.ATTRIBUTE2
	 * @param ATTRIBUTE2  the value for SYS_DATA_SOURCE.ATTRIBUTE2
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void setATTRIBUTE2(String ATTRIBUTE2) {
		this.ATTRIBUTE2 = ATTRIBUTE2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_DATA_SOURCE.ATTRIBUTE3
	 * @return  the value of SYS_DATA_SOURCE.ATTRIBUTE3
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public String getATTRIBUTE3() {
		return ATTRIBUTE3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_DATA_SOURCE.ATTRIBUTE3
	 * @param ATTRIBUTE3  the value for SYS_DATA_SOURCE.ATTRIBUTE3
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void setATTRIBUTE3(String ATTRIBUTE3) {
		this.ATTRIBUTE3 = ATTRIBUTE3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_DATA_SOURCE.ATTRIBUTE4
	 * @return  the value of SYS_DATA_SOURCE.ATTRIBUTE4
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public String getATTRIBUTE4() {
		return ATTRIBUTE4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_DATA_SOURCE.ATTRIBUTE4
	 * @param ATTRIBUTE4  the value for SYS_DATA_SOURCE.ATTRIBUTE4
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void setATTRIBUTE4(String ATTRIBUTE4) {
		this.ATTRIBUTE4 = ATTRIBUTE4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_DATA_SOURCE.ATTRIBUTE5
	 * @return  the value of SYS_DATA_SOURCE.ATTRIBUTE5
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public String getATTRIBUTE5() {
		return ATTRIBUTE5;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_DATA_SOURCE.ATTRIBUTE5
	 * @param ATTRIBUTE5  the value for SYS_DATA_SOURCE.ATTRIBUTE5
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void setATTRIBUTE5(String ATTRIBUTE5) {
		this.ATTRIBUTE5 = ATTRIBUTE5;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_DATA_SOURCE.LINK_ID
	 * @return  the value of SYS_DATA_SOURCE.LINK_ID
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public BigDecimal getLINK_ID() {
		return LINK_ID;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_DATA_SOURCE.LINK_ID
	 * @param LINK_ID  the value for SYS_DATA_SOURCE.LINK_ID
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void setLINK_ID(BigDecimal LINK_ID) {
		this.LINK_ID = LINK_ID;
	}
	  /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_DATA_SOURCE.DEFINING
     *
     * @abatorgenerated Wed May 29 11:33:49 CST 2013
     */
    private String DEFINING;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_DATA_SOURCE.PS_DEFINING
     *
     * @abatorgenerated Wed May 29 11:33:49 CST 2013
     */
    private String PS_DEFINING;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_DATA_SOURCE.DEFINING
     *
     * @return the value of SYS_DATA_SOURCE.DEFINING
     *
     * @abatorgenerated Wed May 29 11:33:49 CST 2013
     */
    public String getDEFINING() {
        return DEFINING;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_DATA_SOURCE.DEFINING
     *
     * @param DEFINING the value for SYS_DATA_SOURCE.DEFINING
     *
     * @abatorgenerated Wed May 29 11:33:49 CST 2013
     */
    public void setDEFINING(String DEFINING) {
        this.DEFINING = DEFINING;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_DATA_SOURCE.PS_DEFINING
     *
     * @return the value of SYS_DATA_SOURCE.PS_DEFINING
     *
     * @abatorgenerated Wed May 29 11:33:49 CST 2013
     */
    public String getPS_DEFINING() {
        return PS_DEFINING;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_DATA_SOURCE.PS_DEFINING
     *
     * @param PS_DEFINING the value for SYS_DATA_SOURCE.PS_DEFINING
     *
     * @abatorgenerated Wed May 29 11:33:49 CST 2013
     */
    public void setPS_DEFINING(String PS_DEFINING) {
        this.PS_DEFINING = PS_DEFINING;
    }
}