package com.notice.model;

public class SysDataSourceWithBLOBs extends SysDataSource {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_DATA_SOURCE.DEFINING
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	private String DEFINING;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_DATA_SOURCE.PS_DEFINING
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	private String PS_DEFINING;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_DATA_SOURCE.DEFINING
	 * @return  the value of SYS_DATA_SOURCE.DEFINING
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public String getDEFINING() {
		return DEFINING;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_DATA_SOURCE.DEFINING
	 * @param DEFINING  the value for SYS_DATA_SOURCE.DEFINING
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void setDEFINING(String DEFINING) {
		this.DEFINING = DEFINING;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_DATA_SOURCE.PS_DEFINING
	 * @return  the value of SYS_DATA_SOURCE.PS_DEFINING
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public String getPS_DEFINING() {
		return PS_DEFINING;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_DATA_SOURCE.PS_DEFINING
	 * @param PS_DEFINING  the value for SYS_DATA_SOURCE.PS_DEFINING
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void setPS_DEFINING(String PS_DEFINING) {
		this.PS_DEFINING = PS_DEFINING;
	}
}