package com.notice.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class SysDbLinksExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table SYS_DB_LINKS
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table SYS_DB_LINKS
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_DB_LINKS
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public SysDbLinksExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_DB_LINKS
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    protected SysDbLinksExample(SysDbLinksExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_DB_LINKS
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_DB_LINKS
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_DB_LINKS
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_DB_LINKS
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_DB_LINKS
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_DB_LINKS
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_DB_LINKS
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table SYS_DB_LINKS
     *
     * @abatorgenerated Fri May 24 18:30:12 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andLINK_IDIsNull() {
            addCriterion("LINK_ID is null");
            return this;
        }

        public Criteria andLINK_IDIsNotNull() {
            addCriterion("LINK_ID is not null");
            return this;
        }

        public Criteria andLINK_IDEqualTo(BigDecimal value) {
            addCriterion("LINK_ID =", value, "LINK_ID");
            return this;
        }

        public Criteria andLINK_IDNotEqualTo(BigDecimal value) {
            addCriterion("LINK_ID <>", value, "LINK_ID");
            return this;
        }

        public Criteria andLINK_IDGreaterThan(BigDecimal value) {
            addCriterion("LINK_ID >", value, "LINK_ID");
            return this;
        }

        public Criteria andLINK_IDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LINK_ID >=", value, "LINK_ID");
            return this;
        }

        public Criteria andLINK_IDLessThan(BigDecimal value) {
            addCriterion("LINK_ID <", value, "LINK_ID");
            return this;
        }

        public Criteria andLINK_IDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LINK_ID <=", value, "LINK_ID");
            return this;
        }

        public Criteria andLINK_IDIn(List values) {
            addCriterion("LINK_ID in", values, "LINK_ID");
            return this;
        }

        public Criteria andLINK_IDNotIn(List values) {
            addCriterion("LINK_ID not in", values, "LINK_ID");
            return this;
        }

        public Criteria andLINK_IDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LINK_ID between", value1, value2, "LINK_ID");
            return this;
        }

        public Criteria andLINK_IDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LINK_ID not between", value1, value2, "LINK_ID");
            return this;
        }

        public Criteria andLINK_CODEIsNull() {
            addCriterion("LINK_CODE is null");
            return this;
        }

        public Criteria andLINK_CODEIsNotNull() {
            addCriterion("LINK_CODE is not null");
            return this;
        }

        public Criteria andLINK_CODEEqualTo(String value) {
            addCriterion("LINK_CODE =", value, "LINK_CODE");
            return this;
        }

        public Criteria andLINK_CODENotEqualTo(String value) {
            addCriterion("LINK_CODE <>", value, "LINK_CODE");
            return this;
        }

        public Criteria andLINK_CODEGreaterThan(String value) {
            addCriterion("LINK_CODE >", value, "LINK_CODE");
            return this;
        }

        public Criteria andLINK_CODEGreaterThanOrEqualTo(String value) {
            addCriterion("LINK_CODE >=", value, "LINK_CODE");
            return this;
        }

        public Criteria andLINK_CODELessThan(String value) {
            addCriterion("LINK_CODE <", value, "LINK_CODE");
            return this;
        }

        public Criteria andLINK_CODELessThanOrEqualTo(String value) {
            addCriterion("LINK_CODE <=", value, "LINK_CODE");
            return this;
        }

        public Criteria andLINK_CODELike(String value) {
            addCriterion("LINK_CODE like", value, "LINK_CODE");
            return this;
        }

        public Criteria andLINK_CODENotLike(String value) {
            addCriterion("LINK_CODE not like", value, "LINK_CODE");
            return this;
        }

        public Criteria andLINK_CODEIn(List values) {
            addCriterion("LINK_CODE in", values, "LINK_CODE");
            return this;
        }

        public Criteria andLINK_CODENotIn(List values) {
            addCriterion("LINK_CODE not in", values, "LINK_CODE");
            return this;
        }

        public Criteria andLINK_CODEBetween(String value1, String value2) {
            addCriterion("LINK_CODE between", value1, value2, "LINK_CODE");
            return this;
        }

        public Criteria andLINK_CODENotBetween(String value1, String value2) {
            addCriterion("LINK_CODE not between", value1, value2, "LINK_CODE");
            return this;
        }

        public Criteria andDRIVER_CLASSIsNull() {
            addCriterion("DRIVER_CLASS is null");
            return this;
        }

        public Criteria andDRIVER_CLASSIsNotNull() {
            addCriterion("DRIVER_CLASS is not null");
            return this;
        }

        public Criteria andDRIVER_CLASSEqualTo(String value) {
            addCriterion("DRIVER_CLASS =", value, "DRIVER_CLASS");
            return this;
        }

        public Criteria andDRIVER_CLASSNotEqualTo(String value) {
            addCriterion("DRIVER_CLASS <>", value, "DRIVER_CLASS");
            return this;
        }

        public Criteria andDRIVER_CLASSGreaterThan(String value) {
            addCriterion("DRIVER_CLASS >", value, "DRIVER_CLASS");
            return this;
        }

        public Criteria andDRIVER_CLASSGreaterThanOrEqualTo(String value) {
            addCriterion("DRIVER_CLASS >=", value, "DRIVER_CLASS");
            return this;
        }

        public Criteria andDRIVER_CLASSLessThan(String value) {
            addCriterion("DRIVER_CLASS <", value, "DRIVER_CLASS");
            return this;
        }

        public Criteria andDRIVER_CLASSLessThanOrEqualTo(String value) {
            addCriterion("DRIVER_CLASS <=", value, "DRIVER_CLASS");
            return this;
        }

        public Criteria andDRIVER_CLASSLike(String value) {
            addCriterion("DRIVER_CLASS like", value, "DRIVER_CLASS");
            return this;
        }

        public Criteria andDRIVER_CLASSNotLike(String value) {
            addCriterion("DRIVER_CLASS not like", value, "DRIVER_CLASS");
            return this;
        }

        public Criteria andDRIVER_CLASSIn(List values) {
            addCriterion("DRIVER_CLASS in", values, "DRIVER_CLASS");
            return this;
        }

        public Criteria andDRIVER_CLASSNotIn(List values) {
            addCriterion("DRIVER_CLASS not in", values, "DRIVER_CLASS");
            return this;
        }

        public Criteria andDRIVER_CLASSBetween(String value1, String value2) {
            addCriterion("DRIVER_CLASS between", value1, value2, "DRIVER_CLASS");
            return this;
        }

        public Criteria andDRIVER_CLASSNotBetween(String value1, String value2) {
            addCriterion("DRIVER_CLASS not between", value1, value2, "DRIVER_CLASS");
            return this;
        }

        public Criteria andURLIsNull() {
            addCriterion("URL is null");
            return this;
        }

        public Criteria andURLIsNotNull() {
            addCriterion("URL is not null");
            return this;
        }

        public Criteria andURLEqualTo(String value) {
            addCriterion("URL =", value, "URL");
            return this;
        }

        public Criteria andURLNotEqualTo(String value) {
            addCriterion("URL <>", value, "URL");
            return this;
        }

        public Criteria andURLGreaterThan(String value) {
            addCriterion("URL >", value, "URL");
            return this;
        }

        public Criteria andURLGreaterThanOrEqualTo(String value) {
            addCriterion("URL >=", value, "URL");
            return this;
        }

        public Criteria andURLLessThan(String value) {
            addCriterion("URL <", value, "URL");
            return this;
        }

        public Criteria andURLLessThanOrEqualTo(String value) {
            addCriterion("URL <=", value, "URL");
            return this;
        }

        public Criteria andURLLike(String value) {
            addCriterion("URL like", value, "URL");
            return this;
        }

        public Criteria andURLNotLike(String value) {
            addCriterion("URL not like", value, "URL");
            return this;
        }

        public Criteria andURLIn(List values) {
            addCriterion("URL in", values, "URL");
            return this;
        }

        public Criteria andURLNotIn(List values) {
            addCriterion("URL not in", values, "URL");
            return this;
        }

        public Criteria andURLBetween(String value1, String value2) {
            addCriterion("URL between", value1, value2, "URL");
            return this;
        }

        public Criteria andURLNotBetween(String value1, String value2) {
            addCriterion("URL not between", value1, value2, "URL");
            return this;
        }

        public Criteria andUSER_NAMEIsNull() {
            addCriterion("USER_NAME is null");
            return this;
        }

        public Criteria andUSER_NAMEIsNotNull() {
            addCriterion("USER_NAME is not null");
            return this;
        }

        public Criteria andUSER_NAMEEqualTo(String value) {
            addCriterion("USER_NAME =", value, "USER_NAME");
            return this;
        }

        public Criteria andUSER_NAMENotEqualTo(String value) {
            addCriterion("USER_NAME <>", value, "USER_NAME");
            return this;
        }

        public Criteria andUSER_NAMEGreaterThan(String value) {
            addCriterion("USER_NAME >", value, "USER_NAME");
            return this;
        }

        public Criteria andUSER_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NAME >=", value, "USER_NAME");
            return this;
        }

        public Criteria andUSER_NAMELessThan(String value) {
            addCriterion("USER_NAME <", value, "USER_NAME");
            return this;
        }

        public Criteria andUSER_NAMELessThanOrEqualTo(String value) {
            addCriterion("USER_NAME <=", value, "USER_NAME");
            return this;
        }

        public Criteria andUSER_NAMELike(String value) {
            addCriterion("USER_NAME like", value, "USER_NAME");
            return this;
        }

        public Criteria andUSER_NAMENotLike(String value) {
            addCriterion("USER_NAME not like", value, "USER_NAME");
            return this;
        }

        public Criteria andUSER_NAMEIn(List values) {
            addCriterion("USER_NAME in", values, "USER_NAME");
            return this;
        }

        public Criteria andUSER_NAMENotIn(List values) {
            addCriterion("USER_NAME not in", values, "USER_NAME");
            return this;
        }

        public Criteria andUSER_NAMEBetween(String value1, String value2) {
            addCriterion("USER_NAME between", value1, value2, "USER_NAME");
            return this;
        }

        public Criteria andUSER_NAMENotBetween(String value1, String value2) {
            addCriterion("USER_NAME not between", value1, value2, "USER_NAME");
            return this;
        }

        public Criteria andPASSWORDIsNull() {
            addCriterion("PASSWORD is null");
            return this;
        }

        public Criteria andPASSWORDIsNotNull() {
            addCriterion("PASSWORD is not null");
            return this;
        }

        public Criteria andPASSWORDEqualTo(String value) {
            addCriterion("PASSWORD =", value, "PASSWORD");
            return this;
        }

        public Criteria andPASSWORDNotEqualTo(String value) {
            addCriterion("PASSWORD <>", value, "PASSWORD");
            return this;
        }

        public Criteria andPASSWORDGreaterThan(String value) {
            addCriterion("PASSWORD >", value, "PASSWORD");
            return this;
        }

        public Criteria andPASSWORDGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWORD >=", value, "PASSWORD");
            return this;
        }

        public Criteria andPASSWORDLessThan(String value) {
            addCriterion("PASSWORD <", value, "PASSWORD");
            return this;
        }

        public Criteria andPASSWORDLessThanOrEqualTo(String value) {
            addCriterion("PASSWORD <=", value, "PASSWORD");
            return this;
        }

        public Criteria andPASSWORDLike(String value) {
            addCriterion("PASSWORD like", value, "PASSWORD");
            return this;
        }

        public Criteria andPASSWORDNotLike(String value) {
            addCriterion("PASSWORD not like", value, "PASSWORD");
            return this;
        }

        public Criteria andPASSWORDIn(List values) {
            addCriterion("PASSWORD in", values, "PASSWORD");
            return this;
        }

        public Criteria andPASSWORDNotIn(List values) {
            addCriterion("PASSWORD not in", values, "PASSWORD");
            return this;
        }

        public Criteria andPASSWORDBetween(String value1, String value2) {
            addCriterion("PASSWORD between", value1, value2, "PASSWORD");
            return this;
        }

        public Criteria andPASSWORDNotBetween(String value1, String value2) {
            addCriterion("PASSWORD not between", value1, value2, "PASSWORD");
            return this;
        }

        public Criteria andDESCRIPTIONIsNull() {
            addCriterion("DESCRIPTION is null");
            return this;
        }

        public Criteria andDESCRIPTIONIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return this;
        }

        public Criteria andDESCRIPTIONEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONLike(String value) {
            addCriterion("DESCRIPTION like", value, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONIn(List values) {
            addCriterion("DESCRIPTION in", values, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONNotIn(List values) {
            addCriterion("DESCRIPTION not in", values, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "DESCRIPTION");
            return this;
        }

        public Criteria andENABLE_DATEIsNull() {
            addCriterion("ENABLE_DATE is null");
            return this;
        }

        public Criteria andENABLE_DATEIsNotNull() {
            addCriterion("ENABLE_DATE is not null");
            return this;
        }

        public Criteria andENABLE_DATEEqualTo(Date value) {
            addCriterionForJDBCDate("ENABLE_DATE =", value, "ENABLE_DATE");
            return this;
        }

        public Criteria andENABLE_DATENotEqualTo(Date value) {
            addCriterionForJDBCDate("ENABLE_DATE <>", value, "ENABLE_DATE");
            return this;
        }

        public Criteria andENABLE_DATEGreaterThan(Date value) {
            addCriterionForJDBCDate("ENABLE_DATE >", value, "ENABLE_DATE");
            return this;
        }

        public Criteria andENABLE_DATEGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ENABLE_DATE >=", value, "ENABLE_DATE");
            return this;
        }

        public Criteria andENABLE_DATELessThan(Date value) {
            addCriterionForJDBCDate("ENABLE_DATE <", value, "ENABLE_DATE");
            return this;
        }

        public Criteria andENABLE_DATELessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ENABLE_DATE <=", value, "ENABLE_DATE");
            return this;
        }

        public Criteria andENABLE_DATEIn(List values) {
            addCriterionForJDBCDate("ENABLE_DATE in", values, "ENABLE_DATE");
            return this;
        }

        public Criteria andENABLE_DATENotIn(List values) {
            addCriterionForJDBCDate("ENABLE_DATE not in", values, "ENABLE_DATE");
            return this;
        }

        public Criteria andENABLE_DATEBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ENABLE_DATE between", value1, value2, "ENABLE_DATE");
            return this;
        }

        public Criteria andENABLE_DATENotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ENABLE_DATE not between", value1, value2, "ENABLE_DATE");
            return this;
        }

        public Criteria andDISABLE_DATEIsNull() {
            addCriterion("DISABLE_DATE is null");
            return this;
        }

        public Criteria andDISABLE_DATEIsNotNull() {
            addCriterion("DISABLE_DATE is not null");
            return this;
        }

        public Criteria andDISABLE_DATEEqualTo(Date value) {
            addCriterionForJDBCDate("DISABLE_DATE =", value, "DISABLE_DATE");
            return this;
        }

        public Criteria andDISABLE_DATENotEqualTo(Date value) {
            addCriterionForJDBCDate("DISABLE_DATE <>", value, "DISABLE_DATE");
            return this;
        }

        public Criteria andDISABLE_DATEGreaterThan(Date value) {
            addCriterionForJDBCDate("DISABLE_DATE >", value, "DISABLE_DATE");
            return this;
        }

        public Criteria andDISABLE_DATEGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DISABLE_DATE >=", value, "DISABLE_DATE");
            return this;
        }

        public Criteria andDISABLE_DATELessThan(Date value) {
            addCriterionForJDBCDate("DISABLE_DATE <", value, "DISABLE_DATE");
            return this;
        }

        public Criteria andDISABLE_DATELessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DISABLE_DATE <=", value, "DISABLE_DATE");
            return this;
        }

        public Criteria andDISABLE_DATEIn(List values) {
            addCriterionForJDBCDate("DISABLE_DATE in", values, "DISABLE_DATE");
            return this;
        }

        public Criteria andDISABLE_DATENotIn(List values) {
            addCriterionForJDBCDate("DISABLE_DATE not in", values, "DISABLE_DATE");
            return this;
        }

        public Criteria andDISABLE_DATEBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DISABLE_DATE between", value1, value2, "DISABLE_DATE");
            return this;
        }

        public Criteria andDISABLE_DATENotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DISABLE_DATE not between", value1, value2, "DISABLE_DATE");
            return this;
        }

        public Criteria andCREATED_BYIsNull() {
            addCriterion("CREATED_BY is null");
            return this;
        }

        public Criteria andCREATED_BYIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return this;
        }

        public Criteria andCREATED_BYEqualTo(BigDecimal value) {
            addCriterion("CREATED_BY =", value, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYNotEqualTo(BigDecimal value) {
            addCriterion("CREATED_BY <>", value, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYGreaterThan(BigDecimal value) {
            addCriterion("CREATED_BY >", value, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CREATED_BY >=", value, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYLessThan(BigDecimal value) {
            addCriterion("CREATED_BY <", value, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CREATED_BY <=", value, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYIn(List values) {
            addCriterion("CREATED_BY in", values, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYNotIn(List values) {
            addCriterion("CREATED_BY not in", values, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREATED_BY between", value1, value2, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREATED_BY not between", value1, value2, "CREATED_BY");
            return this;
        }

        public Criteria andCREATION_DATEIsNull() {
            addCriterion("CREATION_DATE is null");
            return this;
        }

        public Criteria andCREATION_DATEIsNotNull() {
            addCriterion("CREATION_DATE is not null");
            return this;
        }

        public Criteria andCREATION_DATEEqualTo(Date value) {
            addCriterionForJDBCDate("CREATION_DATE =", value, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATENotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATION_DATE <>", value, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATEGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATION_DATE >", value, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATEGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATION_DATE >=", value, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATELessThan(Date value) {
            addCriterionForJDBCDate("CREATION_DATE <", value, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATELessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATION_DATE <=", value, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATEIn(List values) {
            addCriterionForJDBCDate("CREATION_DATE in", values, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATENotIn(List values) {
            addCriterionForJDBCDate("CREATION_DATE not in", values, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATEBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATION_DATE between", value1, value2, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATENotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATION_DATE not between", value1, value2, "CREATION_DATE");
            return this;
        }

        public Criteria andLAST_UPDATED_BYIsNull() {
            addCriterion("LAST_UPDATED_BY is null");
            return this;
        }

        public Criteria andLAST_UPDATED_BYIsNotNull() {
            addCriterion("LAST_UPDATED_BY is not null");
            return this;
        }

        public Criteria andLAST_UPDATED_BYEqualTo(BigDecimal value) {
            addCriterion("LAST_UPDATED_BY =", value, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYNotEqualTo(BigDecimal value) {
            addCriterion("LAST_UPDATED_BY <>", value, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYGreaterThan(BigDecimal value) {
            addCriterion("LAST_UPDATED_BY >", value, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LAST_UPDATED_BY >=", value, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYLessThan(BigDecimal value) {
            addCriterion("LAST_UPDATED_BY <", value, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LAST_UPDATED_BY <=", value, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYIn(List values) {
            addCriterion("LAST_UPDATED_BY in", values, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYNotIn(List values) {
            addCriterion("LAST_UPDATED_BY not in", values, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAST_UPDATED_BY between", value1, value2, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAST_UPDATED_BY not between", value1, value2, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEIsNull() {
            addCriterion("LAST_UPDATE_DATE is null");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEIsNotNull() {
            addCriterion("LAST_UPDATE_DATE is not null");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE =", value, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATENotEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE <>", value, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEGreaterThan(Date value) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE >", value, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE >=", value, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATELessThan(Date value) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE <", value, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATELessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE <=", value, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEIn(List values) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE in", values, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATENotIn(List values) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE not in", values, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE between", value1, value2, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATENotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE not between", value1, value2, "LAST_UPDATE_DATE");
            return this;
        }
    }
}