package com.notice.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class SysDataSourceExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table SYS_DATA_SOURCE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table SYS_DATA_SOURCE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_DATA_SOURCE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public SysDataSourceExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_DATA_SOURCE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	protected SysDataSourceExample(SysDataSourceExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_DATA_SOURCE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_DATA_SOURCE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_DATA_SOURCE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_DATA_SOURCE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_DATA_SOURCE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_DATA_SOURCE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_DATA_SOURCE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table SYS_DATA_SOURCE
	 * @abatorgenerated  Fri May 24 18:29:57 CST 2013
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List dateList = new ArrayList();
			Iterator iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(((Date) iter.next()).getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIDIsNull() {
			addCriterion("ID is null");
			return this;
		}

		public Criteria andIDIsNotNull() {
			addCriterion("ID is not null");
			return this;
		}

		public Criteria andIDEqualTo(BigDecimal value) {
			addCriterion("ID =", value, "ID");
			return this;
		}

		public Criteria andIDNotEqualTo(BigDecimal value) {
			addCriterion("ID <>", value, "ID");
			return this;
		}

		public Criteria andIDGreaterThan(BigDecimal value) {
			addCriterion("ID >", value, "ID");
			return this;
		}

		public Criteria andIDGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ID >=", value, "ID");
			return this;
		}

		public Criteria andIDLessThan(BigDecimal value) {
			addCriterion("ID <", value, "ID");
			return this;
		}

		public Criteria andIDLessThanOrEqualTo(BigDecimal value) {
			addCriterion("ID <=", value, "ID");
			return this;
		}

		public Criteria andIDIn(List values) {
			addCriterion("ID in", values, "ID");
			return this;
		}

		public Criteria andIDNotIn(List values) {
			addCriterion("ID not in", values, "ID");
			return this;
		}

		public Criteria andIDBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ID between", value1, value2, "ID");
			return this;
		}

		public Criteria andIDNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ID not between", value1, value2, "ID");
			return this;
		}

		public Criteria andCODEIsNull() {
			addCriterion("CODE is null");
			return this;
		}

		public Criteria andCODEIsNotNull() {
			addCriterion("CODE is not null");
			return this;
		}

		public Criteria andCODEEqualTo(String value) {
			addCriterion("CODE =", value, "CODE");
			return this;
		}

		public Criteria andCODENotEqualTo(String value) {
			addCriterion("CODE <>", value, "CODE");
			return this;
		}

		public Criteria andCODEGreaterThan(String value) {
			addCriterion("CODE >", value, "CODE");
			return this;
		}

		public Criteria andCODEGreaterThanOrEqualTo(String value) {
			addCriterion("CODE >=", value, "CODE");
			return this;
		}

		public Criteria andCODELessThan(String value) {
			addCriterion("CODE <", value, "CODE");
			return this;
		}

		public Criteria andCODELessThanOrEqualTo(String value) {
			addCriterion("CODE <=", value, "CODE");
			return this;
		}

		public Criteria andCODELike(String value) {
			addCriterion("CODE like", value, "CODE");
			return this;
		}

		public Criteria andCODENotLike(String value) {
			addCriterion("CODE not like", value, "CODE");
			return this;
		}

		public Criteria andCODEIn(List values) {
			addCriterion("CODE in", values, "CODE");
			return this;
		}

		public Criteria andCODENotIn(List values) {
			addCriterion("CODE not in", values, "CODE");
			return this;
		}

		public Criteria andCODEBetween(String value1, String value2) {
			addCriterion("CODE between", value1, value2, "CODE");
			return this;
		}

		public Criteria andCODENotBetween(String value1, String value2) {
			addCriterion("CODE not between", value1, value2, "CODE");
			return this;
		}

		public Criteria andDESCRIPTIONIsNull() {
			addCriterion("DESCRIPTION is null");
			return this;
		}

		public Criteria andDESCRIPTIONIsNotNull() {
			addCriterion("DESCRIPTION is not null");
			return this;
		}

		public Criteria andDESCRIPTIONEqualTo(String value) {
			addCriterion("DESCRIPTION =", value, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONNotEqualTo(String value) {
			addCriterion("DESCRIPTION <>", value, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONGreaterThan(String value) {
			addCriterion("DESCRIPTION >", value, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONGreaterThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION >=", value, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONLessThan(String value) {
			addCriterion("DESCRIPTION <", value, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONLessThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION <=", value, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONLike(String value) {
			addCriterion("DESCRIPTION like", value, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONNotLike(String value) {
			addCriterion("DESCRIPTION not like", value, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONIn(List values) {
			addCriterion("DESCRIPTION in", values, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONNotIn(List values) {
			addCriterion("DESCRIPTION not in", values, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONBetween(String value1, String value2) {
			addCriterion("DESCRIPTION between", value1, value2, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONNotBetween(String value1, String value2) {
			addCriterion("DESCRIPTION not between", value1, value2, "DESCRIPTION");
			return this;
		}

		public Criteria andTYPEIsNull() {
			addCriterion("TYPE is null");
			return this;
		}

		public Criteria andTYPEIsNotNull() {
			addCriterion("TYPE is not null");
			return this;
		}

		public Criteria andTYPEEqualTo(BigDecimal value) {
			addCriterion("TYPE =", value, "TYPE");
			return this;
		}

		public Criteria andTYPENotEqualTo(BigDecimal value) {
			addCriterion("TYPE <>", value, "TYPE");
			return this;
		}

		public Criteria andTYPEGreaterThan(BigDecimal value) {
			addCriterion("TYPE >", value, "TYPE");
			return this;
		}

		public Criteria andTYPEGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("TYPE >=", value, "TYPE");
			return this;
		}

		public Criteria andTYPELessThan(BigDecimal value) {
			addCriterion("TYPE <", value, "TYPE");
			return this;
		}

		public Criteria andTYPELessThanOrEqualTo(BigDecimal value) {
			addCriterion("TYPE <=", value, "TYPE");
			return this;
		}

		public Criteria andTYPEIn(List values) {
			addCriterion("TYPE in", values, "TYPE");
			return this;
		}

		public Criteria andTYPENotIn(List values) {
			addCriterion("TYPE not in", values, "TYPE");
			return this;
		}

		public Criteria andTYPEBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("TYPE between", value1, value2, "TYPE");
			return this;
		}

		public Criteria andTYPENotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("TYPE not between", value1, value2, "TYPE");
			return this;
		}

		public Criteria andDISABLEDIsNull() {
			addCriterion("DISABLED is null");
			return this;
		}

		public Criteria andDISABLEDIsNotNull() {
			addCriterion("DISABLED is not null");
			return this;
		}

		public Criteria andDISABLEDEqualTo(String value) {
			addCriterion("DISABLED =", value, "DISABLED");
			return this;
		}

		public Criteria andDISABLEDNotEqualTo(String value) {
			addCriterion("DISABLED <>", value, "DISABLED");
			return this;
		}

		public Criteria andDISABLEDGreaterThan(String value) {
			addCriterion("DISABLED >", value, "DISABLED");
			return this;
		}

		public Criteria andDISABLEDGreaterThanOrEqualTo(String value) {
			addCriterion("DISABLED >=", value, "DISABLED");
			return this;
		}

		public Criteria andDISABLEDLessThan(String value) {
			addCriterion("DISABLED <", value, "DISABLED");
			return this;
		}

		public Criteria andDISABLEDLessThanOrEqualTo(String value) {
			addCriterion("DISABLED <=", value, "DISABLED");
			return this;
		}

		public Criteria andDISABLEDLike(String value) {
			addCriterion("DISABLED like", value, "DISABLED");
			return this;
		}

		public Criteria andDISABLEDNotLike(String value) {
			addCriterion("DISABLED not like", value, "DISABLED");
			return this;
		}

		public Criteria andDISABLEDIn(List values) {
			addCriterion("DISABLED in", values, "DISABLED");
			return this;
		}

		public Criteria andDISABLEDNotIn(List values) {
			addCriterion("DISABLED not in", values, "DISABLED");
			return this;
		}

		public Criteria andDISABLEDBetween(String value1, String value2) {
			addCriterion("DISABLED between", value1, value2, "DISABLED");
			return this;
		}

		public Criteria andDISABLEDNotBetween(String value1, String value2) {
			addCriterion("DISABLED not between", value1, value2, "DISABLED");
			return this;
		}

		public Criteria andCREATEDBYIsNull() {
			addCriterion("CREATEDBY is null");
			return this;
		}

		public Criteria andCREATEDBYIsNotNull() {
			addCriterion("CREATEDBY is not null");
			return this;
		}

		public Criteria andCREATEDBYEqualTo(BigDecimal value) {
			addCriterion("CREATEDBY =", value, "CREATEDBY");
			return this;
		}

		public Criteria andCREATEDBYNotEqualTo(BigDecimal value) {
			addCriterion("CREATEDBY <>", value, "CREATEDBY");
			return this;
		}

		public Criteria andCREATEDBYGreaterThan(BigDecimal value) {
			addCriterion("CREATEDBY >", value, "CREATEDBY");
			return this;
		}

		public Criteria andCREATEDBYGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("CREATEDBY >=", value, "CREATEDBY");
			return this;
		}

		public Criteria andCREATEDBYLessThan(BigDecimal value) {
			addCriterion("CREATEDBY <", value, "CREATEDBY");
			return this;
		}

		public Criteria andCREATEDBYLessThanOrEqualTo(BigDecimal value) {
			addCriterion("CREATEDBY <=", value, "CREATEDBY");
			return this;
		}

		public Criteria andCREATEDBYIn(List values) {
			addCriterion("CREATEDBY in", values, "CREATEDBY");
			return this;
		}

		public Criteria andCREATEDBYNotIn(List values) {
			addCriterion("CREATEDBY not in", values, "CREATEDBY");
			return this;
		}

		public Criteria andCREATEDBYBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("CREATEDBY between", value1, value2, "CREATEDBY");
			return this;
		}

		public Criteria andCREATEDBYNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("CREATEDBY not between", value1, value2, "CREATEDBY");
			return this;
		}

		public Criteria andCREATIONDATEIsNull() {
			addCriterion("CREATIONDATE is null");
			return this;
		}

		public Criteria andCREATIONDATEIsNotNull() {
			addCriterion("CREATIONDATE is not null");
			return this;
		}

		public Criteria andCREATIONDATEEqualTo(Date value) {
			addCriterionForJDBCDate("CREATIONDATE =", value, "CREATIONDATE");
			return this;
		}

		public Criteria andCREATIONDATENotEqualTo(Date value) {
			addCriterionForJDBCDate("CREATIONDATE <>", value, "CREATIONDATE");
			return this;
		}

		public Criteria andCREATIONDATEGreaterThan(Date value) {
			addCriterionForJDBCDate("CREATIONDATE >", value, "CREATIONDATE");
			return this;
		}

		public Criteria andCREATIONDATEGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATIONDATE >=", value, "CREATIONDATE");
			return this;
		}

		public Criteria andCREATIONDATELessThan(Date value) {
			addCriterionForJDBCDate("CREATIONDATE <", value, "CREATIONDATE");
			return this;
		}

		public Criteria andCREATIONDATELessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATIONDATE <=", value, "CREATIONDATE");
			return this;
		}

		public Criteria andCREATIONDATEIn(List values) {
			addCriterionForJDBCDate("CREATIONDATE in", values, "CREATIONDATE");
			return this;
		}

		public Criteria andCREATIONDATENotIn(List values) {
			addCriterionForJDBCDate("CREATIONDATE not in", values, "CREATIONDATE");
			return this;
		}

		public Criteria andCREATIONDATEBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATIONDATE between", value1, value2, "CREATIONDATE");
			return this;
		}

		public Criteria andCREATIONDATENotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATIONDATE not between", value1, value2, "CREATIONDATE");
			return this;
		}

		public Criteria andLASTUPDATEDBYIsNull() {
			addCriterion("LASTUPDATEDBY is null");
			return this;
		}

		public Criteria andLASTUPDATEDBYIsNotNull() {
			addCriterion("LASTUPDATEDBY is not null");
			return this;
		}

		public Criteria andLASTUPDATEDBYEqualTo(BigDecimal value) {
			addCriterion("LASTUPDATEDBY =", value, "LASTUPDATEDBY");
			return this;
		}

		public Criteria andLASTUPDATEDBYNotEqualTo(BigDecimal value) {
			addCriterion("LASTUPDATEDBY <>", value, "LASTUPDATEDBY");
			return this;
		}

		public Criteria andLASTUPDATEDBYGreaterThan(BigDecimal value) {
			addCriterion("LASTUPDATEDBY >", value, "LASTUPDATEDBY");
			return this;
		}

		public Criteria andLASTUPDATEDBYGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("LASTUPDATEDBY >=", value, "LASTUPDATEDBY");
			return this;
		}

		public Criteria andLASTUPDATEDBYLessThan(BigDecimal value) {
			addCriterion("LASTUPDATEDBY <", value, "LASTUPDATEDBY");
			return this;
		}

		public Criteria andLASTUPDATEDBYLessThanOrEqualTo(BigDecimal value) {
			addCriterion("LASTUPDATEDBY <=", value, "LASTUPDATEDBY");
			return this;
		}

		public Criteria andLASTUPDATEDBYIn(List values) {
			addCriterion("LASTUPDATEDBY in", values, "LASTUPDATEDBY");
			return this;
		}

		public Criteria andLASTUPDATEDBYNotIn(List values) {
			addCriterion("LASTUPDATEDBY not in", values, "LASTUPDATEDBY");
			return this;
		}

		public Criteria andLASTUPDATEDBYBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("LASTUPDATEDBY between", value1, value2, "LASTUPDATEDBY");
			return this;
		}

		public Criteria andLASTUPDATEDBYNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("LASTUPDATEDBY not between", value1, value2, "LASTUPDATEDBY");
			return this;
		}

		public Criteria andLASTUPDATEDATEIsNull() {
			addCriterion("LASTUPDATEDATE is null");
			return this;
		}

		public Criteria andLASTUPDATEDATEIsNotNull() {
			addCriterion("LASTUPDATEDATE is not null");
			return this;
		}

		public Criteria andLASTUPDATEDATEEqualTo(Date value) {
			addCriterionForJDBCDate("LASTUPDATEDATE =", value, "LASTUPDATEDATE");
			return this;
		}

		public Criteria andLASTUPDATEDATENotEqualTo(Date value) {
			addCriterionForJDBCDate("LASTUPDATEDATE <>", value, "LASTUPDATEDATE");
			return this;
		}

		public Criteria andLASTUPDATEDATEGreaterThan(Date value) {
			addCriterionForJDBCDate("LASTUPDATEDATE >", value, "LASTUPDATEDATE");
			return this;
		}

		public Criteria andLASTUPDATEDATEGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("LASTUPDATEDATE >=", value, "LASTUPDATEDATE");
			return this;
		}

		public Criteria andLASTUPDATEDATELessThan(Date value) {
			addCriterionForJDBCDate("LASTUPDATEDATE <", value, "LASTUPDATEDATE");
			return this;
		}

		public Criteria andLASTUPDATEDATELessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("LASTUPDATEDATE <=", value, "LASTUPDATEDATE");
			return this;
		}

		public Criteria andLASTUPDATEDATEIn(List values) {
			addCriterionForJDBCDate("LASTUPDATEDATE in", values, "LASTUPDATEDATE");
			return this;
		}

		public Criteria andLASTUPDATEDATENotIn(List values) {
			addCriterionForJDBCDate("LASTUPDATEDATE not in", values, "LASTUPDATEDATE");
			return this;
		}

		public Criteria andLASTUPDATEDATEBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("LASTUPDATEDATE between", value1, value2, "LASTUPDATEDATE");
			return this;
		}

		public Criteria andLASTUPDATEDATENotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("LASTUPDATEDATE not between", value1, value2, "LASTUPDATEDATE");
			return this;
		}

		public Criteria andATTRIBUTE1IsNull() {
			addCriterion("ATTRIBUTE1 is null");
			return this;
		}

		public Criteria andATTRIBUTE1IsNotNull() {
			addCriterion("ATTRIBUTE1 is not null");
			return this;
		}

		public Criteria andATTRIBUTE1EqualTo(String value) {
			addCriterion("ATTRIBUTE1 =", value, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1NotEqualTo(String value) {
			addCriterion("ATTRIBUTE1 <>", value, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1GreaterThan(String value) {
			addCriterion("ATTRIBUTE1 >", value, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1GreaterThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE1 >=", value, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1LessThan(String value) {
			addCriterion("ATTRIBUTE1 <", value, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1LessThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE1 <=", value, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1Like(String value) {
			addCriterion("ATTRIBUTE1 like", value, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1NotLike(String value) {
			addCriterion("ATTRIBUTE1 not like", value, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1In(List values) {
			addCriterion("ATTRIBUTE1 in", values, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1NotIn(List values) {
			addCriterion("ATTRIBUTE1 not in", values, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1Between(String value1, String value2) {
			addCriterion("ATTRIBUTE1 between", value1, value2, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1NotBetween(String value1, String value2) {
			addCriterion("ATTRIBUTE1 not between", value1, value2, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE2IsNull() {
			addCriterion("ATTRIBUTE2 is null");
			return this;
		}

		public Criteria andATTRIBUTE2IsNotNull() {
			addCriterion("ATTRIBUTE2 is not null");
			return this;
		}

		public Criteria andATTRIBUTE2EqualTo(String value) {
			addCriterion("ATTRIBUTE2 =", value, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2NotEqualTo(String value) {
			addCriterion("ATTRIBUTE2 <>", value, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2GreaterThan(String value) {
			addCriterion("ATTRIBUTE2 >", value, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2GreaterThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE2 >=", value, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2LessThan(String value) {
			addCriterion("ATTRIBUTE2 <", value, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2LessThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE2 <=", value, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2Like(String value) {
			addCriterion("ATTRIBUTE2 like", value, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2NotLike(String value) {
			addCriterion("ATTRIBUTE2 not like", value, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2In(List values) {
			addCriterion("ATTRIBUTE2 in", values, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2NotIn(List values) {
			addCriterion("ATTRIBUTE2 not in", values, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2Between(String value1, String value2) {
			addCriterion("ATTRIBUTE2 between", value1, value2, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2NotBetween(String value1, String value2) {
			addCriterion("ATTRIBUTE2 not between", value1, value2, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE3IsNull() {
			addCriterion("ATTRIBUTE3 is null");
			return this;
		}

		public Criteria andATTRIBUTE3IsNotNull() {
			addCriterion("ATTRIBUTE3 is not null");
			return this;
		}

		public Criteria andATTRIBUTE3EqualTo(String value) {
			addCriterion("ATTRIBUTE3 =", value, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3NotEqualTo(String value) {
			addCriterion("ATTRIBUTE3 <>", value, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3GreaterThan(String value) {
			addCriterion("ATTRIBUTE3 >", value, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3GreaterThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE3 >=", value, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3LessThan(String value) {
			addCriterion("ATTRIBUTE3 <", value, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3LessThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE3 <=", value, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3Like(String value) {
			addCriterion("ATTRIBUTE3 like", value, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3NotLike(String value) {
			addCriterion("ATTRIBUTE3 not like", value, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3In(List values) {
			addCriterion("ATTRIBUTE3 in", values, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3NotIn(List values) {
			addCriterion("ATTRIBUTE3 not in", values, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3Between(String value1, String value2) {
			addCriterion("ATTRIBUTE3 between", value1, value2, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3NotBetween(String value1, String value2) {
			addCriterion("ATTRIBUTE3 not between", value1, value2, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE4IsNull() {
			addCriterion("ATTRIBUTE4 is null");
			return this;
		}

		public Criteria andATTRIBUTE4IsNotNull() {
			addCriterion("ATTRIBUTE4 is not null");
			return this;
		}

		public Criteria andATTRIBUTE4EqualTo(String value) {
			addCriterion("ATTRIBUTE4 =", value, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4NotEqualTo(String value) {
			addCriterion("ATTRIBUTE4 <>", value, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4GreaterThan(String value) {
			addCriterion("ATTRIBUTE4 >", value, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4GreaterThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE4 >=", value, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4LessThan(String value) {
			addCriterion("ATTRIBUTE4 <", value, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4LessThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE4 <=", value, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4Like(String value) {
			addCriterion("ATTRIBUTE4 like", value, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4NotLike(String value) {
			addCriterion("ATTRIBUTE4 not like", value, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4In(List values) {
			addCriterion("ATTRIBUTE4 in", values, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4NotIn(List values) {
			addCriterion("ATTRIBUTE4 not in", values, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4Between(String value1, String value2) {
			addCriterion("ATTRIBUTE4 between", value1, value2, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4NotBetween(String value1, String value2) {
			addCriterion("ATTRIBUTE4 not between", value1, value2, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE5IsNull() {
			addCriterion("ATTRIBUTE5 is null");
			return this;
		}

		public Criteria andATTRIBUTE5IsNotNull() {
			addCriterion("ATTRIBUTE5 is not null");
			return this;
		}

		public Criteria andATTRIBUTE5EqualTo(String value) {
			addCriterion("ATTRIBUTE5 =", value, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5NotEqualTo(String value) {
			addCriterion("ATTRIBUTE5 <>", value, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5GreaterThan(String value) {
			addCriterion("ATTRIBUTE5 >", value, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5GreaterThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE5 >=", value, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5LessThan(String value) {
			addCriterion("ATTRIBUTE5 <", value, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5LessThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE5 <=", value, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5Like(String value) {
			addCriterion("ATTRIBUTE5 like", value, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5NotLike(String value) {
			addCriterion("ATTRIBUTE5 not like", value, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5In(List values) {
			addCriterion("ATTRIBUTE5 in", values, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5NotIn(List values) {
			addCriterion("ATTRIBUTE5 not in", values, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5Between(String value1, String value2) {
			addCriterion("ATTRIBUTE5 between", value1, value2, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5NotBetween(String value1, String value2) {
			addCriterion("ATTRIBUTE5 not between", value1, value2, "ATTRIBUTE5");
			return this;
		}

		public Criteria andLINK_IDIsNull() {
			addCriterion("LINK_ID is null");
			return this;
		}

		public Criteria andLINK_IDIsNotNull() {
			addCriterion("LINK_ID is not null");
			return this;
		}

		public Criteria andLINK_IDEqualTo(BigDecimal value) {
			addCriterion("LINK_ID =", value, "LINK_ID");
			return this;
		}

		public Criteria andLINK_IDNotEqualTo(BigDecimal value) {
			addCriterion("LINK_ID <>", value, "LINK_ID");
			return this;
		}

		public Criteria andLINK_IDGreaterThan(BigDecimal value) {
			addCriterion("LINK_ID >", value, "LINK_ID");
			return this;
		}

		public Criteria andLINK_IDGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("LINK_ID >=", value, "LINK_ID");
			return this;
		}

		public Criteria andLINK_IDLessThan(BigDecimal value) {
			addCriterion("LINK_ID <", value, "LINK_ID");
			return this;
		}

		public Criteria andLINK_IDLessThanOrEqualTo(BigDecimal value) {
			addCriterion("LINK_ID <=", value, "LINK_ID");
			return this;
		}

		public Criteria andLINK_IDIn(List values) {
			addCriterion("LINK_ID in", values, "LINK_ID");
			return this;
		}

		public Criteria andLINK_IDNotIn(List values) {
			addCriterion("LINK_ID not in", values, "LINK_ID");
			return this;
		}

		public Criteria andLINK_IDBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("LINK_ID between", value1, value2, "LINK_ID");
			return this;
		}

		public Criteria andLINK_IDNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("LINK_ID not between", value1, value2, "LINK_ID");
			return this;
		}
	}
}