package com.notice.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class SysEmailSendHistoryExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table SYS_EMAIL_SEND_HISTORY
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table SYS_EMAIL_SEND_HISTORY
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_EMAIL_SEND_HISTORY
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public SysEmailSendHistoryExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_EMAIL_SEND_HISTORY
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    protected SysEmailSendHistoryExample(SysEmailSendHistoryExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_EMAIL_SEND_HISTORY
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_EMAIL_SEND_HISTORY
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_EMAIL_SEND_HISTORY
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_EMAIL_SEND_HISTORY
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_EMAIL_SEND_HISTORY
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_EMAIL_SEND_HISTORY
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_EMAIL_SEND_HISTORY
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table SYS_EMAIL_SEND_HISTORY
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andHISTORY_IDIsNull() {
            addCriterion("HISTORY_ID is null");
            return this;
        }

        public Criteria andHISTORY_IDIsNotNull() {
            addCriterion("HISTORY_ID is not null");
            return this;
        }

        public Criteria andHISTORY_IDEqualTo(BigDecimal value) {
            addCriterion("HISTORY_ID =", value, "HISTORY_ID");
            return this;
        }

        public Criteria andHISTORY_IDNotEqualTo(BigDecimal value) {
            addCriterion("HISTORY_ID <>", value, "HISTORY_ID");
            return this;
        }

        public Criteria andHISTORY_IDGreaterThan(BigDecimal value) {
            addCriterion("HISTORY_ID >", value, "HISTORY_ID");
            return this;
        }

        public Criteria andHISTORY_IDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("HISTORY_ID >=", value, "HISTORY_ID");
            return this;
        }

        public Criteria andHISTORY_IDLessThan(BigDecimal value) {
            addCriterion("HISTORY_ID <", value, "HISTORY_ID");
            return this;
        }

        public Criteria andHISTORY_IDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("HISTORY_ID <=", value, "HISTORY_ID");
            return this;
        }

        public Criteria andHISTORY_IDIn(List values) {
            addCriterion("HISTORY_ID in", values, "HISTORY_ID");
            return this;
        }

        public Criteria andHISTORY_IDNotIn(List values) {
            addCriterion("HISTORY_ID not in", values, "HISTORY_ID");
            return this;
        }

        public Criteria andHISTORY_IDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HISTORY_ID between", value1, value2, "HISTORY_ID");
            return this;
        }

        public Criteria andHISTORY_IDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HISTORY_ID not between", value1, value2, "HISTORY_ID");
            return this;
        }

        public Criteria andEMAIL_IDIsNull() {
            addCriterion("EMAIL_ID is null");
            return this;
        }

        public Criteria andEMAIL_IDIsNotNull() {
            addCriterion("EMAIL_ID is not null");
            return this;
        }

        public Criteria andEMAIL_IDEqualTo(BigDecimal value) {
            addCriterion("EMAIL_ID =", value, "EMAIL_ID");
            return this;
        }

        public Criteria andEMAIL_IDNotEqualTo(BigDecimal value) {
            addCriterion("EMAIL_ID <>", value, "EMAIL_ID");
            return this;
        }

        public Criteria andEMAIL_IDGreaterThan(BigDecimal value) {
            addCriterion("EMAIL_ID >", value, "EMAIL_ID");
            return this;
        }

        public Criteria andEMAIL_IDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("EMAIL_ID >=", value, "EMAIL_ID");
            return this;
        }

        public Criteria andEMAIL_IDLessThan(BigDecimal value) {
            addCriterion("EMAIL_ID <", value, "EMAIL_ID");
            return this;
        }

        public Criteria andEMAIL_IDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("EMAIL_ID <=", value, "EMAIL_ID");
            return this;
        }

        public Criteria andEMAIL_IDIn(List values) {
            addCriterion("EMAIL_ID in", values, "EMAIL_ID");
            return this;
        }

        public Criteria andEMAIL_IDNotIn(List values) {
            addCriterion("EMAIL_ID not in", values, "EMAIL_ID");
            return this;
        }

        public Criteria andEMAIL_IDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EMAIL_ID between", value1, value2, "EMAIL_ID");
            return this;
        }

        public Criteria andEMAIL_IDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EMAIL_ID not between", value1, value2, "EMAIL_ID");
            return this;
        }

        public Criteria andBIZ_IDIsNull() {
            addCriterion("BIZ_ID is null");
            return this;
        }

        public Criteria andBIZ_IDIsNotNull() {
            addCriterion("BIZ_ID is not null");
            return this;
        }

        public Criteria andBIZ_IDEqualTo(BigDecimal value) {
            addCriterion("BIZ_ID =", value, "BIZ_ID");
            return this;
        }

        public Criteria andBIZ_IDNotEqualTo(BigDecimal value) {
            addCriterion("BIZ_ID <>", value, "BIZ_ID");
            return this;
        }

        public Criteria andBIZ_IDGreaterThan(BigDecimal value) {
            addCriterion("BIZ_ID >", value, "BIZ_ID");
            return this;
        }

        public Criteria andBIZ_IDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BIZ_ID >=", value, "BIZ_ID");
            return this;
        }

        public Criteria andBIZ_IDLessThan(BigDecimal value) {
            addCriterion("BIZ_ID <", value, "BIZ_ID");
            return this;
        }

        public Criteria andBIZ_IDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BIZ_ID <=", value, "BIZ_ID");
            return this;
        }

        public Criteria andBIZ_IDIn(List values) {
            addCriterion("BIZ_ID in", values, "BIZ_ID");
            return this;
        }

        public Criteria andBIZ_IDNotIn(List values) {
            addCriterion("BIZ_ID not in", values, "BIZ_ID");
            return this;
        }

        public Criteria andBIZ_IDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BIZ_ID between", value1, value2, "BIZ_ID");
            return this;
        }

        public Criteria andBIZ_IDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BIZ_ID not between", value1, value2, "BIZ_ID");
            return this;
        }

        public Criteria andMODULE_CODEIsNull() {
            addCriterion("MODULE_CODE is null");
            return this;
        }

        public Criteria andMODULE_CODEIsNotNull() {
            addCriterion("MODULE_CODE is not null");
            return this;
        }

        public Criteria andMODULE_CODEEqualTo(String value) {
            addCriterion("MODULE_CODE =", value, "MODULE_CODE");
            return this;
        }

        public Criteria andMODULE_CODENotEqualTo(String value) {
            addCriterion("MODULE_CODE <>", value, "MODULE_CODE");
            return this;
        }

        public Criteria andMODULE_CODEGreaterThan(String value) {
            addCriterion("MODULE_CODE >", value, "MODULE_CODE");
            return this;
        }

        public Criteria andMODULE_CODEGreaterThanOrEqualTo(String value) {
            addCriterion("MODULE_CODE >=", value, "MODULE_CODE");
            return this;
        }

        public Criteria andMODULE_CODELessThan(String value) {
            addCriterion("MODULE_CODE <", value, "MODULE_CODE");
            return this;
        }

        public Criteria andMODULE_CODELessThanOrEqualTo(String value) {
            addCriterion("MODULE_CODE <=", value, "MODULE_CODE");
            return this;
        }

        public Criteria andMODULE_CODELike(String value) {
            addCriterion("MODULE_CODE like", value, "MODULE_CODE");
            return this;
        }

        public Criteria andMODULE_CODENotLike(String value) {
            addCriterion("MODULE_CODE not like", value, "MODULE_CODE");
            return this;
        }

        public Criteria andMODULE_CODEIn(List values) {
            addCriterion("MODULE_CODE in", values, "MODULE_CODE");
            return this;
        }

        public Criteria andMODULE_CODENotIn(List values) {
            addCriterion("MODULE_CODE not in", values, "MODULE_CODE");
            return this;
        }

        public Criteria andMODULE_CODEBetween(String value1, String value2) {
            addCriterion("MODULE_CODE between", value1, value2, "MODULE_CODE");
            return this;
        }

        public Criteria andMODULE_CODENotBetween(String value1, String value2) {
            addCriterion("MODULE_CODE not between", value1, value2, "MODULE_CODE");
            return this;
        }

        public Criteria andTYPE_CODEIsNull() {
            addCriterion("TYPE_CODE is null");
            return this;
        }

        public Criteria andTYPE_CODEIsNotNull() {
            addCriterion("TYPE_CODE is not null");
            return this;
        }

        public Criteria andTYPE_CODEEqualTo(String value) {
            addCriterion("TYPE_CODE =", value, "TYPE_CODE");
            return this;
        }

        public Criteria andTYPE_CODENotEqualTo(String value) {
            addCriterion("TYPE_CODE <>", value, "TYPE_CODE");
            return this;
        }

        public Criteria andTYPE_CODEGreaterThan(String value) {
            addCriterion("TYPE_CODE >", value, "TYPE_CODE");
            return this;
        }

        public Criteria andTYPE_CODEGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE_CODE >=", value, "TYPE_CODE");
            return this;
        }

        public Criteria andTYPE_CODELessThan(String value) {
            addCriterion("TYPE_CODE <", value, "TYPE_CODE");
            return this;
        }

        public Criteria andTYPE_CODELessThanOrEqualTo(String value) {
            addCriterion("TYPE_CODE <=", value, "TYPE_CODE");
            return this;
        }

        public Criteria andTYPE_CODELike(String value) {
            addCriterion("TYPE_CODE like", value, "TYPE_CODE");
            return this;
        }

        public Criteria andTYPE_CODENotLike(String value) {
            addCriterion("TYPE_CODE not like", value, "TYPE_CODE");
            return this;
        }

        public Criteria andTYPE_CODEIn(List values) {
            addCriterion("TYPE_CODE in", values, "TYPE_CODE");
            return this;
        }

        public Criteria andTYPE_CODENotIn(List values) {
            addCriterion("TYPE_CODE not in", values, "TYPE_CODE");
            return this;
        }

        public Criteria andTYPE_CODEBetween(String value1, String value2) {
            addCriterion("TYPE_CODE between", value1, value2, "TYPE_CODE");
            return this;
        }

        public Criteria andTYPE_CODENotBetween(String value1, String value2) {
            addCriterion("TYPE_CODE not between", value1, value2, "TYPE_CODE");
            return this;
        }

        public Criteria andTITLEIsNull() {
            addCriterion("TITLE is null");
            return this;
        }

        public Criteria andTITLEIsNotNull() {
            addCriterion("TITLE is not null");
            return this;
        }

        public Criteria andTITLEEqualTo(String value) {
            addCriterion("TITLE =", value, "TITLE");
            return this;
        }

        public Criteria andTITLENotEqualTo(String value) {
            addCriterion("TITLE <>", value, "TITLE");
            return this;
        }

        public Criteria andTITLEGreaterThan(String value) {
            addCriterion("TITLE >", value, "TITLE");
            return this;
        }

        public Criteria andTITLEGreaterThanOrEqualTo(String value) {
            addCriterion("TITLE >=", value, "TITLE");
            return this;
        }

        public Criteria andTITLELessThan(String value) {
            addCriterion("TITLE <", value, "TITLE");
            return this;
        }

        public Criteria andTITLELessThanOrEqualTo(String value) {
            addCriterion("TITLE <=", value, "TITLE");
            return this;
        }

        public Criteria andTITLELike(String value) {
            addCriterion("TITLE like", value, "TITLE");
            return this;
        }

        public Criteria andTITLENotLike(String value) {
            addCriterion("TITLE not like", value, "TITLE");
            return this;
        }

        public Criteria andTITLEIn(List values) {
            addCriterion("TITLE in", values, "TITLE");
            return this;
        }

        public Criteria andTITLENotIn(List values) {
            addCriterion("TITLE not in", values, "TITLE");
            return this;
        }

        public Criteria andTITLEBetween(String value1, String value2) {
            addCriterion("TITLE between", value1, value2, "TITLE");
            return this;
        }

        public Criteria andTITLENotBetween(String value1, String value2) {
            addCriterion("TITLE not between", value1, value2, "TITLE");
            return this;
        }

        public Criteria andRECIPIENTSIsNull() {
            addCriterion("RECIPIENTS is null");
            return this;
        }

        public Criteria andRECIPIENTSIsNotNull() {
            addCriterion("RECIPIENTS is not null");
            return this;
        }

        public Criteria andRECIPIENTSEqualTo(String value) {
            addCriterion("RECIPIENTS =", value, "RECIPIENTS");
            return this;
        }

        public Criteria andRECIPIENTSNotEqualTo(String value) {
            addCriterion("RECIPIENTS <>", value, "RECIPIENTS");
            return this;
        }

        public Criteria andRECIPIENTSGreaterThan(String value) {
            addCriterion("RECIPIENTS >", value, "RECIPIENTS");
            return this;
        }

        public Criteria andRECIPIENTSGreaterThanOrEqualTo(String value) {
            addCriterion("RECIPIENTS >=", value, "RECIPIENTS");
            return this;
        }

        public Criteria andRECIPIENTSLessThan(String value) {
            addCriterion("RECIPIENTS <", value, "RECIPIENTS");
            return this;
        }

        public Criteria andRECIPIENTSLessThanOrEqualTo(String value) {
            addCriterion("RECIPIENTS <=", value, "RECIPIENTS");
            return this;
        }

        public Criteria andRECIPIENTSLike(String value) {
            addCriterion("RECIPIENTS like", value, "RECIPIENTS");
            return this;
        }

        public Criteria andRECIPIENTSNotLike(String value) {
            addCriterion("RECIPIENTS not like", value, "RECIPIENTS");
            return this;
        }

        public Criteria andRECIPIENTSIn(List values) {
            addCriterion("RECIPIENTS in", values, "RECIPIENTS");
            return this;
        }

        public Criteria andRECIPIENTSNotIn(List values) {
            addCriterion("RECIPIENTS not in", values, "RECIPIENTS");
            return this;
        }

        public Criteria andRECIPIENTSBetween(String value1, String value2) {
            addCriterion("RECIPIENTS between", value1, value2, "RECIPIENTS");
            return this;
        }

        public Criteria andRECIPIENTSNotBetween(String value1, String value2) {
            addCriterion("RECIPIENTS not between", value1, value2, "RECIPIENTS");
            return this;
        }

        public Criteria andCARBON_COPYSIsNull() {
            addCriterion("CARBON_COPYS is null");
            return this;
        }

        public Criteria andCARBON_COPYSIsNotNull() {
            addCriterion("CARBON_COPYS is not null");
            return this;
        }

        public Criteria andCARBON_COPYSEqualTo(String value) {
            addCriterion("CARBON_COPYS =", value, "CARBON_COPYS");
            return this;
        }

        public Criteria andCARBON_COPYSNotEqualTo(String value) {
            addCriterion("CARBON_COPYS <>", value, "CARBON_COPYS");
            return this;
        }

        public Criteria andCARBON_COPYSGreaterThan(String value) {
            addCriterion("CARBON_COPYS >", value, "CARBON_COPYS");
            return this;
        }

        public Criteria andCARBON_COPYSGreaterThanOrEqualTo(String value) {
            addCriterion("CARBON_COPYS >=", value, "CARBON_COPYS");
            return this;
        }

        public Criteria andCARBON_COPYSLessThan(String value) {
            addCriterion("CARBON_COPYS <", value, "CARBON_COPYS");
            return this;
        }

        public Criteria andCARBON_COPYSLessThanOrEqualTo(String value) {
            addCriterion("CARBON_COPYS <=", value, "CARBON_COPYS");
            return this;
        }

        public Criteria andCARBON_COPYSLike(String value) {
            addCriterion("CARBON_COPYS like", value, "CARBON_COPYS");
            return this;
        }

        public Criteria andCARBON_COPYSNotLike(String value) {
            addCriterion("CARBON_COPYS not like", value, "CARBON_COPYS");
            return this;
        }

        public Criteria andCARBON_COPYSIn(List values) {
            addCriterion("CARBON_COPYS in", values, "CARBON_COPYS");
            return this;
        }

        public Criteria andCARBON_COPYSNotIn(List values) {
            addCriterion("CARBON_COPYS not in", values, "CARBON_COPYS");
            return this;
        }

        public Criteria andCARBON_COPYSBetween(String value1, String value2) {
            addCriterion("CARBON_COPYS between", value1, value2, "CARBON_COPYS");
            return this;
        }

        public Criteria andCARBON_COPYSNotBetween(String value1, String value2) {
            addCriterion("CARBON_COPYS not between", value1, value2, "CARBON_COPYS");
            return this;
        }

        public Criteria andBLIND_CARBON_COPYSIsNull() {
            addCriterion("BLIND_CARBON_COPYS is null");
            return this;
        }

        public Criteria andBLIND_CARBON_COPYSIsNotNull() {
            addCriterion("BLIND_CARBON_COPYS is not null");
            return this;
        }

        public Criteria andBLIND_CARBON_COPYSEqualTo(String value) {
            addCriterion("BLIND_CARBON_COPYS =", value, "BLIND_CARBON_COPYS");
            return this;
        }

        public Criteria andBLIND_CARBON_COPYSNotEqualTo(String value) {
            addCriterion("BLIND_CARBON_COPYS <>", value, "BLIND_CARBON_COPYS");
            return this;
        }

        public Criteria andBLIND_CARBON_COPYSGreaterThan(String value) {
            addCriterion("BLIND_CARBON_COPYS >", value, "BLIND_CARBON_COPYS");
            return this;
        }

        public Criteria andBLIND_CARBON_COPYSGreaterThanOrEqualTo(String value) {
            addCriterion("BLIND_CARBON_COPYS >=", value, "BLIND_CARBON_COPYS");
            return this;
        }

        public Criteria andBLIND_CARBON_COPYSLessThan(String value) {
            addCriterion("BLIND_CARBON_COPYS <", value, "BLIND_CARBON_COPYS");
            return this;
        }

        public Criteria andBLIND_CARBON_COPYSLessThanOrEqualTo(String value) {
            addCriterion("BLIND_CARBON_COPYS <=", value, "BLIND_CARBON_COPYS");
            return this;
        }

        public Criteria andBLIND_CARBON_COPYSLike(String value) {
            addCriterion("BLIND_CARBON_COPYS like", value, "BLIND_CARBON_COPYS");
            return this;
        }

        public Criteria andBLIND_CARBON_COPYSNotLike(String value) {
            addCriterion("BLIND_CARBON_COPYS not like", value, "BLIND_CARBON_COPYS");
            return this;
        }

        public Criteria andBLIND_CARBON_COPYSIn(List values) {
            addCriterion("BLIND_CARBON_COPYS in", values, "BLIND_CARBON_COPYS");
            return this;
        }

        public Criteria andBLIND_CARBON_COPYSNotIn(List values) {
            addCriterion("BLIND_CARBON_COPYS not in", values, "BLIND_CARBON_COPYS");
            return this;
        }

        public Criteria andBLIND_CARBON_COPYSBetween(String value1, String value2) {
            addCriterion("BLIND_CARBON_COPYS between", value1, value2, "BLIND_CARBON_COPYS");
            return this;
        }

        public Criteria andBLIND_CARBON_COPYSNotBetween(String value1, String value2) {
            addCriterion("BLIND_CARBON_COPYS not between", value1, value2, "BLIND_CARBON_COPYS");
            return this;
        }

        public Criteria andATTACH_FILE_NAMEIsNull() {
            addCriterion("ATTACH_FILE_NAME is null");
            return this;
        }

        public Criteria andATTACH_FILE_NAMEIsNotNull() {
            addCriterion("ATTACH_FILE_NAME is not null");
            return this;
        }

        public Criteria andATTACH_FILE_NAMEEqualTo(String value) {
            addCriterion("ATTACH_FILE_NAME =", value, "ATTACH_FILE_NAME");
            return this;
        }

        public Criteria andATTACH_FILE_NAMENotEqualTo(String value) {
            addCriterion("ATTACH_FILE_NAME <>", value, "ATTACH_FILE_NAME");
            return this;
        }

        public Criteria andATTACH_FILE_NAMEGreaterThan(String value) {
            addCriterion("ATTACH_FILE_NAME >", value, "ATTACH_FILE_NAME");
            return this;
        }

        public Criteria andATTACH_FILE_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("ATTACH_FILE_NAME >=", value, "ATTACH_FILE_NAME");
            return this;
        }

        public Criteria andATTACH_FILE_NAMELessThan(String value) {
            addCriterion("ATTACH_FILE_NAME <", value, "ATTACH_FILE_NAME");
            return this;
        }

        public Criteria andATTACH_FILE_NAMELessThanOrEqualTo(String value) {
            addCriterion("ATTACH_FILE_NAME <=", value, "ATTACH_FILE_NAME");
            return this;
        }

        public Criteria andATTACH_FILE_NAMELike(String value) {
            addCriterion("ATTACH_FILE_NAME like", value, "ATTACH_FILE_NAME");
            return this;
        }

        public Criteria andATTACH_FILE_NAMENotLike(String value) {
            addCriterion("ATTACH_FILE_NAME not like", value, "ATTACH_FILE_NAME");
            return this;
        }

        public Criteria andATTACH_FILE_NAMEIn(List values) {
            addCriterion("ATTACH_FILE_NAME in", values, "ATTACH_FILE_NAME");
            return this;
        }

        public Criteria andATTACH_FILE_NAMENotIn(List values) {
            addCriterion("ATTACH_FILE_NAME not in", values, "ATTACH_FILE_NAME");
            return this;
        }

        public Criteria andATTACH_FILE_NAMEBetween(String value1, String value2) {
            addCriterion("ATTACH_FILE_NAME between", value1, value2, "ATTACH_FILE_NAME");
            return this;
        }

        public Criteria andATTACH_FILE_NAMENotBetween(String value1, String value2) {
            addCriterion("ATTACH_FILE_NAME not between", value1, value2, "ATTACH_FILE_NAME");
            return this;
        }

        public Criteria andCREATED_BYIsNull() {
            addCriterion("CREATED_BY is null");
            return this;
        }

        public Criteria andCREATED_BYIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return this;
        }

        public Criteria andCREATED_BYEqualTo(BigDecimal value) {
            addCriterion("CREATED_BY =", value, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYNotEqualTo(BigDecimal value) {
            addCriterion("CREATED_BY <>", value, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYGreaterThan(BigDecimal value) {
            addCriterion("CREATED_BY >", value, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CREATED_BY >=", value, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYLessThan(BigDecimal value) {
            addCriterion("CREATED_BY <", value, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CREATED_BY <=", value, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYIn(List values) {
            addCriterion("CREATED_BY in", values, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYNotIn(List values) {
            addCriterion("CREATED_BY not in", values, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREATED_BY between", value1, value2, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREATED_BY not between", value1, value2, "CREATED_BY");
            return this;
        }

        public Criteria andCREATION_DATEIsNull() {
            addCriterion("CREATION_DATE is null");
            return this;
        }

        public Criteria andCREATION_DATEIsNotNull() {
            addCriterion("CREATION_DATE is not null");
            return this;
        }

        public Criteria andCREATION_DATEEqualTo(Date value) {
            addCriterionForJDBCDate("CREATION_DATE =", value, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATENotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATION_DATE <>", value, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATEGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATION_DATE >", value, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATEGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATION_DATE >=", value, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATELessThan(Date value) {
            addCriterionForJDBCDate("CREATION_DATE <", value, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATELessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATION_DATE <=", value, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATEIn(List values) {
            addCriterionForJDBCDate("CREATION_DATE in", values, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATENotIn(List values) {
            addCriterionForJDBCDate("CREATION_DATE not in", values, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATEBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATION_DATE between", value1, value2, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATENotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATION_DATE not between", value1, value2, "CREATION_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEIsNull() {
            addCriterion("LAST_UPDATE_DATE is null");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEIsNotNull() {
            addCriterion("LAST_UPDATE_DATE is not null");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE =", value, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATENotEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE <>", value, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEGreaterThan(Date value) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE >", value, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE >=", value, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATELessThan(Date value) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE <", value, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATELessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE <=", value, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEIn(List values) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE in", values, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATENotIn(List values) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE not in", values, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE between", value1, value2, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATENotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE not between", value1, value2, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATED_BYIsNull() {
            addCriterion("LAST_UPDATED_BY is null");
            return this;
        }

        public Criteria andLAST_UPDATED_BYIsNotNull() {
            addCriterion("LAST_UPDATED_BY is not null");
            return this;
        }

        public Criteria andLAST_UPDATED_BYEqualTo(BigDecimal value) {
            addCriterion("LAST_UPDATED_BY =", value, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYNotEqualTo(BigDecimal value) {
            addCriterion("LAST_UPDATED_BY <>", value, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYGreaterThan(BigDecimal value) {
            addCriterion("LAST_UPDATED_BY >", value, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LAST_UPDATED_BY >=", value, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYLessThan(BigDecimal value) {
            addCriterion("LAST_UPDATED_BY <", value, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LAST_UPDATED_BY <=", value, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYIn(List values) {
            addCriterion("LAST_UPDATED_BY in", values, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYNotIn(List values) {
            addCriterion("LAST_UPDATED_BY not in", values, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAST_UPDATED_BY between", value1, value2, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAST_UPDATED_BY not between", value1, value2, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andSUCCESSIsNull() {
            addCriterion("SUCCESS is null");
            return this;
        }

        public Criteria andSUCCESSIsNotNull() {
            addCriterion("SUCCESS is not null");
            return this;
        }

        public Criteria andSUCCESSEqualTo(String value) {
            addCriterion("SUCCESS =", value, "SUCCESS");
            return this;
        }

        public Criteria andSUCCESSNotEqualTo(String value) {
            addCriterion("SUCCESS <>", value, "SUCCESS");
            return this;
        }

        public Criteria andSUCCESSGreaterThan(String value) {
            addCriterion("SUCCESS >", value, "SUCCESS");
            return this;
        }

        public Criteria andSUCCESSGreaterThanOrEqualTo(String value) {
            addCriterion("SUCCESS >=", value, "SUCCESS");
            return this;
        }

        public Criteria andSUCCESSLessThan(String value) {
            addCriterion("SUCCESS <", value, "SUCCESS");
            return this;
        }

        public Criteria andSUCCESSLessThanOrEqualTo(String value) {
            addCriterion("SUCCESS <=", value, "SUCCESS");
            return this;
        }

        public Criteria andSUCCESSLike(String value) {
            addCriterion("SUCCESS like", value, "SUCCESS");
            return this;
        }

        public Criteria andSUCCESSNotLike(String value) {
            addCriterion("SUCCESS not like", value, "SUCCESS");
            return this;
        }

        public Criteria andSUCCESSIn(List values) {
            addCriterion("SUCCESS in", values, "SUCCESS");
            return this;
        }

        public Criteria andSUCCESSNotIn(List values) {
            addCriterion("SUCCESS not in", values, "SUCCESS");
            return this;
        }

        public Criteria andSUCCESSBetween(String value1, String value2) {
            addCriterion("SUCCESS between", value1, value2, "SUCCESS");
            return this;
        }

        public Criteria andSUCCESSNotBetween(String value1, String value2) {
            addCriterion("SUCCESS not between", value1, value2, "SUCCESS");
            return this;
        }

        public Criteria andSEND_DATEIsNull() {
            addCriterion("SEND_DATE is null");
            return this;
        }

        public Criteria andSEND_DATEIsNotNull() {
            addCriterion("SEND_DATE is not null");
            return this;
        }

        public Criteria andSEND_DATEEqualTo(Date value) {
            addCriterionForJDBCDate("SEND_DATE =", value, "SEND_DATE");
            return this;
        }

        public Criteria andSEND_DATENotEqualTo(Date value) {
            addCriterionForJDBCDate("SEND_DATE <>", value, "SEND_DATE");
            return this;
        }

        public Criteria andSEND_DATEGreaterThan(Date value) {
            addCriterionForJDBCDate("SEND_DATE >", value, "SEND_DATE");
            return this;
        }

        public Criteria andSEND_DATEGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SEND_DATE >=", value, "SEND_DATE");
            return this;
        }

        public Criteria andSEND_DATELessThan(Date value) {
            addCriterionForJDBCDate("SEND_DATE <", value, "SEND_DATE");
            return this;
        }

        public Criteria andSEND_DATELessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SEND_DATE <=", value, "SEND_DATE");
            return this;
        }

        public Criteria andSEND_DATEIn(List values) {
            addCriterionForJDBCDate("SEND_DATE in", values, "SEND_DATE");
            return this;
        }

        public Criteria andSEND_DATENotIn(List values) {
            addCriterionForJDBCDate("SEND_DATE not in", values, "SEND_DATE");
            return this;
        }

        public Criteria andSEND_DATEBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SEND_DATE between", value1, value2, "SEND_DATE");
            return this;
        }

        public Criteria andSEND_DATENotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SEND_DATE not between", value1, value2, "SEND_DATE");
            return this;
        }
    }
}