package com.notice.model;

import java.math.BigDecimal;
import java.util.Date;

public class SysEmailSendHistory {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_EMAIL_SEND_HISTORY.HISTORY_ID
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    private BigDecimal HISTORY_ID;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_EMAIL_SEND_HISTORY.EMAIL_ID
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    private BigDecimal EMAIL_ID;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_EMAIL_SEND_HISTORY.BIZ_ID
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    private BigDecimal BIZ_ID;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_EMAIL_SEND_HISTORY.MODULE_CODE
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    private String MODULE_CODE;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_EMAIL_SEND_HISTORY.TYPE_CODE
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    private String TYPE_CODE;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_EMAIL_SEND_HISTORY.TITLE
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    private String TITLE;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_EMAIL_SEND_HISTORY.RECIPIENTS
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    private String RECIPIENTS;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_EMAIL_SEND_HISTORY.CARBON_COPYS
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    private String CARBON_COPYS;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_EMAIL_SEND_HISTORY.BLIND_CARBON_COPYS
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    private String BLIND_CARBON_COPYS;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_EMAIL_SEND_HISTORY.ATTACH_FILE_NAME
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    private String ATTACH_FILE_NAME;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_EMAIL_SEND_HISTORY.CREATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    private BigDecimal CREATED_BY;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_EMAIL_SEND_HISTORY.CREATION_DATE
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    private Date CREATION_DATE;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_EMAIL_SEND_HISTORY.LAST_UPDATE_DATE
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    private Date LAST_UPDATE_DATE;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_EMAIL_SEND_HISTORY.LAST_UPDATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    private BigDecimal LAST_UPDATED_BY;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_EMAIL_SEND_HISTORY.SUCCESS
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    private String SUCCESS;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_EMAIL_SEND_HISTORY.SEND_DATE
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    private Date SEND_DATE;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_EMAIL_SEND_HISTORY.CONTENT
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    private String CONTENT;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_EMAIL_SEND_HISTORY.HISTORY_ID
     *
     * @return the value of SYS_EMAIL_SEND_HISTORY.HISTORY_ID
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public BigDecimal getHISTORY_ID() {
        return HISTORY_ID;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_EMAIL_SEND_HISTORY.HISTORY_ID
     *
     * @param HISTORY_ID the value for SYS_EMAIL_SEND_HISTORY.HISTORY_ID
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void setHISTORY_ID(BigDecimal HISTORY_ID) {
        this.HISTORY_ID = HISTORY_ID;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_EMAIL_SEND_HISTORY.EMAIL_ID
     *
     * @return the value of SYS_EMAIL_SEND_HISTORY.EMAIL_ID
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public BigDecimal getEMAIL_ID() {
        return EMAIL_ID;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_EMAIL_SEND_HISTORY.EMAIL_ID
     *
     * @param EMAIL_ID the value for SYS_EMAIL_SEND_HISTORY.EMAIL_ID
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void setEMAIL_ID(BigDecimal EMAIL_ID) {
        this.EMAIL_ID = EMAIL_ID;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_EMAIL_SEND_HISTORY.BIZ_ID
     *
     * @return the value of SYS_EMAIL_SEND_HISTORY.BIZ_ID
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public BigDecimal getBIZ_ID() {
        return BIZ_ID;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_EMAIL_SEND_HISTORY.BIZ_ID
     *
     * @param BIZ_ID the value for SYS_EMAIL_SEND_HISTORY.BIZ_ID
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void setBIZ_ID(BigDecimal BIZ_ID) {
        this.BIZ_ID = BIZ_ID;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_EMAIL_SEND_HISTORY.MODULE_CODE
     *
     * @return the value of SYS_EMAIL_SEND_HISTORY.MODULE_CODE
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public String getMODULE_CODE() {
        return MODULE_CODE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_EMAIL_SEND_HISTORY.MODULE_CODE
     *
     * @param MODULE_CODE the value for SYS_EMAIL_SEND_HISTORY.MODULE_CODE
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void setMODULE_CODE(String MODULE_CODE) {
        this.MODULE_CODE = MODULE_CODE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_EMAIL_SEND_HISTORY.TYPE_CODE
     *
     * @return the value of SYS_EMAIL_SEND_HISTORY.TYPE_CODE
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public String getTYPE_CODE() {
        return TYPE_CODE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_EMAIL_SEND_HISTORY.TYPE_CODE
     *
     * @param TYPE_CODE the value for SYS_EMAIL_SEND_HISTORY.TYPE_CODE
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void setTYPE_CODE(String TYPE_CODE) {
        this.TYPE_CODE = TYPE_CODE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_EMAIL_SEND_HISTORY.TITLE
     *
     * @return the value of SYS_EMAIL_SEND_HISTORY.TITLE
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public String getTITLE() {
        return TITLE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_EMAIL_SEND_HISTORY.TITLE
     *
     * @param TITLE the value for SYS_EMAIL_SEND_HISTORY.TITLE
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void setTITLE(String TITLE) {
        this.TITLE = TITLE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_EMAIL_SEND_HISTORY.RECIPIENTS
     *
     * @return the value of SYS_EMAIL_SEND_HISTORY.RECIPIENTS
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public String getRECIPIENTS() {
        return RECIPIENTS;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_EMAIL_SEND_HISTORY.RECIPIENTS
     *
     * @param RECIPIENTS the value for SYS_EMAIL_SEND_HISTORY.RECIPIENTS
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void setRECIPIENTS(String RECIPIENTS) {
        this.RECIPIENTS = RECIPIENTS;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_EMAIL_SEND_HISTORY.CARBON_COPYS
     *
     * @return the value of SYS_EMAIL_SEND_HISTORY.CARBON_COPYS
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public String getCARBON_COPYS() {
        return CARBON_COPYS;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_EMAIL_SEND_HISTORY.CARBON_COPYS
     *
     * @param CARBON_COPYS the value for SYS_EMAIL_SEND_HISTORY.CARBON_COPYS
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void setCARBON_COPYS(String CARBON_COPYS) {
        this.CARBON_COPYS = CARBON_COPYS;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_EMAIL_SEND_HISTORY.BLIND_CARBON_COPYS
     *
     * @return the value of SYS_EMAIL_SEND_HISTORY.BLIND_CARBON_COPYS
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public String getBLIND_CARBON_COPYS() {
        return BLIND_CARBON_COPYS;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_EMAIL_SEND_HISTORY.BLIND_CARBON_COPYS
     *
     * @param BLIND_CARBON_COPYS the value for SYS_EMAIL_SEND_HISTORY.BLIND_CARBON_COPYS
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void setBLIND_CARBON_COPYS(String BLIND_CARBON_COPYS) {
        this.BLIND_CARBON_COPYS = BLIND_CARBON_COPYS;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_EMAIL_SEND_HISTORY.ATTACH_FILE_NAME
     *
     * @return the value of SYS_EMAIL_SEND_HISTORY.ATTACH_FILE_NAME
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public String getATTACH_FILE_NAME() {
        return ATTACH_FILE_NAME;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_EMAIL_SEND_HISTORY.ATTACH_FILE_NAME
     *
     * @param ATTACH_FILE_NAME the value for SYS_EMAIL_SEND_HISTORY.ATTACH_FILE_NAME
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void setATTACH_FILE_NAME(String ATTACH_FILE_NAME) {
        this.ATTACH_FILE_NAME = ATTACH_FILE_NAME;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_EMAIL_SEND_HISTORY.CREATED_BY
     *
     * @return the value of SYS_EMAIL_SEND_HISTORY.CREATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public BigDecimal getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_EMAIL_SEND_HISTORY.CREATED_BY
     *
     * @param CREATED_BY the value for SYS_EMAIL_SEND_HISTORY.CREATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void setCREATED_BY(BigDecimal CREATED_BY) {
        this.CREATED_BY = CREATED_BY;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_EMAIL_SEND_HISTORY.CREATION_DATE
     *
     * @return the value of SYS_EMAIL_SEND_HISTORY.CREATION_DATE
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public Date getCREATION_DATE() {
        return CREATION_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_EMAIL_SEND_HISTORY.CREATION_DATE
     *
     * @param CREATION_DATE the value for SYS_EMAIL_SEND_HISTORY.CREATION_DATE
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void setCREATION_DATE(Date CREATION_DATE) {
        this.CREATION_DATE = CREATION_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_EMAIL_SEND_HISTORY.LAST_UPDATE_DATE
     *
     * @return the value of SYS_EMAIL_SEND_HISTORY.LAST_UPDATE_DATE
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public Date getLAST_UPDATE_DATE() {
        return LAST_UPDATE_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_EMAIL_SEND_HISTORY.LAST_UPDATE_DATE
     *
     * @param LAST_UPDATE_DATE the value for SYS_EMAIL_SEND_HISTORY.LAST_UPDATE_DATE
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void setLAST_UPDATE_DATE(Date LAST_UPDATE_DATE) {
        this.LAST_UPDATE_DATE = LAST_UPDATE_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_EMAIL_SEND_HISTORY.LAST_UPDATED_BY
     *
     * @return the value of SYS_EMAIL_SEND_HISTORY.LAST_UPDATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public BigDecimal getLAST_UPDATED_BY() {
        return LAST_UPDATED_BY;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_EMAIL_SEND_HISTORY.LAST_UPDATED_BY
     *
     * @param LAST_UPDATED_BY the value for SYS_EMAIL_SEND_HISTORY.LAST_UPDATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void setLAST_UPDATED_BY(BigDecimal LAST_UPDATED_BY) {
        this.LAST_UPDATED_BY = LAST_UPDATED_BY;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_EMAIL_SEND_HISTORY.SUCCESS
     *
     * @return the value of SYS_EMAIL_SEND_HISTORY.SUCCESS
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public String getSUCCESS() {
        return SUCCESS;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_EMAIL_SEND_HISTORY.SUCCESS
     *
     * @param SUCCESS the value for SYS_EMAIL_SEND_HISTORY.SUCCESS
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void setSUCCESS(String SUCCESS) {
        this.SUCCESS = SUCCESS;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_EMAIL_SEND_HISTORY.SEND_DATE
     *
     * @return the value of SYS_EMAIL_SEND_HISTORY.SEND_DATE
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public Date getSEND_DATE() {
        return SEND_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_EMAIL_SEND_HISTORY.SEND_DATE
     *
     * @param SEND_DATE the value for SYS_EMAIL_SEND_HISTORY.SEND_DATE
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void setSEND_DATE(Date SEND_DATE) {
        this.SEND_DATE = SEND_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_EMAIL_SEND_HISTORY.CONTENT
     *
     * @return the value of SYS_EMAIL_SEND_HISTORY.CONTENT
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public String getCONTENT() {
        return CONTENT;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_EMAIL_SEND_HISTORY.CONTENT
     *
     * @param CONTENT the value for SYS_EMAIL_SEND_HISTORY.CONTENT
     *
     * @abatorgenerated Fri May 24 18:30:08 CST 2013
     */
    public void setCONTENT(String CONTENT) {
        this.CONTENT = CONTENT;
    }
}