package com.notice.model;

import java.math.BigDecimal;
import java.util.Date;

public class SysFileRelations {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_FILE_RELATIONS.RELATION_ID
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    private BigDecimal RELATION_ID;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_FILE_RELATIONS.FILE_ID
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    private BigDecimal FILE_ID;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_FILE_RELATIONS.FILE_NAME
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    private String FILE_NAME;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_FILE_RELATIONS.ORIGINAL_FILE_NAME
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    private String ORIGINAL_FILE_NAME;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_FILE_RELATIONS.SUFFIX_CODE
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    private String SUFFIX_CODE;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_FILE_RELATIONS.FILE_PATH
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    private String FILE_PATH;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_FILE_RELATIONS.FILE_SIZE
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    private BigDecimal FILE_SIZE;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_FILE_RELATIONS.BILL_ID
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    private BigDecimal BILL_ID;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_FILE_RELATIONS.BILL_TYPE
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    private String BILL_TYPE;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_FILE_RELATIONS.BILL_ATTACHMENT_CODE
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    private String BILL_ATTACHMENT_CODE;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_FILE_RELATIONS.DISABLED
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    private String DISABLED;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_FILE_RELATIONS.CREATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    private BigDecimal CREATED_BY;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_FILE_RELATIONS.CREATION_DATE
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    private Date CREATION_DATE;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_FILE_RELATIONS.LAST_UPDATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    private BigDecimal LAST_UPDATED_BY;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_FILE_RELATIONS.LAST_UPDATE_DATE
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    private Date LAST_UPDATE_DATE;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_FILE_RELATIONS.DESCRIPTION
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    private String DESCRIPTION;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_FILE_RELATIONS.RELATION_ID
     *
     * @return the value of SYS_FILE_RELATIONS.RELATION_ID
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public BigDecimal getRELATION_ID() {
        return RELATION_ID;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_FILE_RELATIONS.RELATION_ID
     *
     * @param RELATION_ID the value for SYS_FILE_RELATIONS.RELATION_ID
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void setRELATION_ID(BigDecimal RELATION_ID) {
        this.RELATION_ID = RELATION_ID;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_FILE_RELATIONS.FILE_ID
     *
     * @return the value of SYS_FILE_RELATIONS.FILE_ID
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public BigDecimal getFILE_ID() {
        return FILE_ID;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_FILE_RELATIONS.FILE_ID
     *
     * @param FILE_ID the value for SYS_FILE_RELATIONS.FILE_ID
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void setFILE_ID(BigDecimal FILE_ID) {
        this.FILE_ID = FILE_ID;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_FILE_RELATIONS.FILE_NAME
     *
     * @return the value of SYS_FILE_RELATIONS.FILE_NAME
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public String getFILE_NAME() {
        return FILE_NAME;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_FILE_RELATIONS.FILE_NAME
     *
     * @param FILE_NAME the value for SYS_FILE_RELATIONS.FILE_NAME
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void setFILE_NAME(String FILE_NAME) {
        this.FILE_NAME = FILE_NAME;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_FILE_RELATIONS.ORIGINAL_FILE_NAME
     *
     * @return the value of SYS_FILE_RELATIONS.ORIGINAL_FILE_NAME
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public String getORIGINAL_FILE_NAME() {
        return ORIGINAL_FILE_NAME;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_FILE_RELATIONS.ORIGINAL_FILE_NAME
     *
     * @param ORIGINAL_FILE_NAME the value for SYS_FILE_RELATIONS.ORIGINAL_FILE_NAME
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void setORIGINAL_FILE_NAME(String ORIGINAL_FILE_NAME) {
        this.ORIGINAL_FILE_NAME = ORIGINAL_FILE_NAME;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_FILE_RELATIONS.SUFFIX_CODE
     *
     * @return the value of SYS_FILE_RELATIONS.SUFFIX_CODE
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public String getSUFFIX_CODE() {
        return SUFFIX_CODE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_FILE_RELATIONS.SUFFIX_CODE
     *
     * @param SUFFIX_CODE the value for SYS_FILE_RELATIONS.SUFFIX_CODE
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void setSUFFIX_CODE(String SUFFIX_CODE) {
        this.SUFFIX_CODE = SUFFIX_CODE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_FILE_RELATIONS.FILE_PATH
     *
     * @return the value of SYS_FILE_RELATIONS.FILE_PATH
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public String getFILE_PATH() {
        return FILE_PATH;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_FILE_RELATIONS.FILE_PATH
     *
     * @param FILE_PATH the value for SYS_FILE_RELATIONS.FILE_PATH
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void setFILE_PATH(String FILE_PATH) {
        this.FILE_PATH = FILE_PATH;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_FILE_RELATIONS.FILE_SIZE
     *
     * @return the value of SYS_FILE_RELATIONS.FILE_SIZE
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public BigDecimal getFILE_SIZE() {
        return FILE_SIZE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_FILE_RELATIONS.FILE_SIZE
     *
     * @param FILE_SIZE the value for SYS_FILE_RELATIONS.FILE_SIZE
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void setFILE_SIZE(BigDecimal FILE_SIZE) {
        this.FILE_SIZE = FILE_SIZE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_FILE_RELATIONS.BILL_ID
     *
     * @return the value of SYS_FILE_RELATIONS.BILL_ID
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public BigDecimal getBILL_ID() {
        return BILL_ID;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_FILE_RELATIONS.BILL_ID
     *
     * @param BILL_ID the value for SYS_FILE_RELATIONS.BILL_ID
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void setBILL_ID(BigDecimal BILL_ID) {
        this.BILL_ID = BILL_ID;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_FILE_RELATIONS.BILL_TYPE
     *
     * @return the value of SYS_FILE_RELATIONS.BILL_TYPE
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public String getBILL_TYPE() {
        return BILL_TYPE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_FILE_RELATIONS.BILL_TYPE
     *
     * @param BILL_TYPE the value for SYS_FILE_RELATIONS.BILL_TYPE
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void setBILL_TYPE(String BILL_TYPE) {
        this.BILL_TYPE = BILL_TYPE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_FILE_RELATIONS.BILL_ATTACHMENT_CODE
     *
     * @return the value of SYS_FILE_RELATIONS.BILL_ATTACHMENT_CODE
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public String getBILL_ATTACHMENT_CODE() {
        return BILL_ATTACHMENT_CODE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_FILE_RELATIONS.BILL_ATTACHMENT_CODE
     *
     * @param BILL_ATTACHMENT_CODE the value for SYS_FILE_RELATIONS.BILL_ATTACHMENT_CODE
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void setBILL_ATTACHMENT_CODE(String BILL_ATTACHMENT_CODE) {
        this.BILL_ATTACHMENT_CODE = BILL_ATTACHMENT_CODE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_FILE_RELATIONS.DISABLED
     *
     * @return the value of SYS_FILE_RELATIONS.DISABLED
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public String getDISABLED() {
        return DISABLED;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_FILE_RELATIONS.DISABLED
     *
     * @param DISABLED the value for SYS_FILE_RELATIONS.DISABLED
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void setDISABLED(String DISABLED) {
        this.DISABLED = DISABLED;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_FILE_RELATIONS.CREATED_BY
     *
     * @return the value of SYS_FILE_RELATIONS.CREATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public BigDecimal getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_FILE_RELATIONS.CREATED_BY
     *
     * @param CREATED_BY the value for SYS_FILE_RELATIONS.CREATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void setCREATED_BY(BigDecimal CREATED_BY) {
        this.CREATED_BY = CREATED_BY;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_FILE_RELATIONS.CREATION_DATE
     *
     * @return the value of SYS_FILE_RELATIONS.CREATION_DATE
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public Date getCREATION_DATE() {
        return CREATION_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_FILE_RELATIONS.CREATION_DATE
     *
     * @param CREATION_DATE the value for SYS_FILE_RELATIONS.CREATION_DATE
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void setCREATION_DATE(Date CREATION_DATE) {
        this.CREATION_DATE = CREATION_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_FILE_RELATIONS.LAST_UPDATED_BY
     *
     * @return the value of SYS_FILE_RELATIONS.LAST_UPDATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public BigDecimal getLAST_UPDATED_BY() {
        return LAST_UPDATED_BY;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_FILE_RELATIONS.LAST_UPDATED_BY
     *
     * @param LAST_UPDATED_BY the value for SYS_FILE_RELATIONS.LAST_UPDATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void setLAST_UPDATED_BY(BigDecimal LAST_UPDATED_BY) {
        this.LAST_UPDATED_BY = LAST_UPDATED_BY;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_FILE_RELATIONS.LAST_UPDATE_DATE
     *
     * @return the value of SYS_FILE_RELATIONS.LAST_UPDATE_DATE
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public Date getLAST_UPDATE_DATE() {
        return LAST_UPDATE_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_FILE_RELATIONS.LAST_UPDATE_DATE
     *
     * @param LAST_UPDATE_DATE the value for SYS_FILE_RELATIONS.LAST_UPDATE_DATE
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void setLAST_UPDATE_DATE(Date LAST_UPDATE_DATE) {
        this.LAST_UPDATE_DATE = LAST_UPDATE_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_FILE_RELATIONS.DESCRIPTION
     *
     * @return the value of SYS_FILE_RELATIONS.DESCRIPTION
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_FILE_RELATIONS.DESCRIPTION
     *
     * @param DESCRIPTION the value for SYS_FILE_RELATIONS.DESCRIPTION
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION;
    }
}