package com.notice.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class SysFileRelationsExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table SYS_FILE_RELATIONS
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table SYS_FILE_RELATIONS
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_FILE_RELATIONS
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public SysFileRelationsExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_FILE_RELATIONS
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    protected SysFileRelationsExample(SysFileRelationsExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_FILE_RELATIONS
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_FILE_RELATIONS
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_FILE_RELATIONS
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_FILE_RELATIONS
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_FILE_RELATIONS
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_FILE_RELATIONS
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SYS_FILE_RELATIONS
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table SYS_FILE_RELATIONS
     *
     * @abatorgenerated Fri May 24 18:30:03 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andRELATION_IDIsNull() {
            addCriterion("RELATION_ID is null");
            return this;
        }

        public Criteria andRELATION_IDIsNotNull() {
            addCriterion("RELATION_ID is not null");
            return this;
        }

        public Criteria andRELATION_IDEqualTo(BigDecimal value) {
            addCriterion("RELATION_ID =", value, "RELATION_ID");
            return this;
        }

        public Criteria andRELATION_IDNotEqualTo(BigDecimal value) {
            addCriterion("RELATION_ID <>", value, "RELATION_ID");
            return this;
        }

        public Criteria andRELATION_IDGreaterThan(BigDecimal value) {
            addCriterion("RELATION_ID >", value, "RELATION_ID");
            return this;
        }

        public Criteria andRELATION_IDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RELATION_ID >=", value, "RELATION_ID");
            return this;
        }

        public Criteria andRELATION_IDLessThan(BigDecimal value) {
            addCriterion("RELATION_ID <", value, "RELATION_ID");
            return this;
        }

        public Criteria andRELATION_IDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RELATION_ID <=", value, "RELATION_ID");
            return this;
        }

        public Criteria andRELATION_IDIn(List values) {
            addCriterion("RELATION_ID in", values, "RELATION_ID");
            return this;
        }

        public Criteria andRELATION_IDNotIn(List values) {
            addCriterion("RELATION_ID not in", values, "RELATION_ID");
            return this;
        }

        public Criteria andRELATION_IDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RELATION_ID between", value1, value2, "RELATION_ID");
            return this;
        }

        public Criteria andRELATION_IDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RELATION_ID not between", value1, value2, "RELATION_ID");
            return this;
        }

        public Criteria andFILE_IDIsNull() {
            addCriterion("FILE_ID is null");
            return this;
        }

        public Criteria andFILE_IDIsNotNull() {
            addCriterion("FILE_ID is not null");
            return this;
        }

        public Criteria andFILE_IDEqualTo(BigDecimal value) {
            addCriterion("FILE_ID =", value, "FILE_ID");
            return this;
        }

        public Criteria andFILE_IDNotEqualTo(BigDecimal value) {
            addCriterion("FILE_ID <>", value, "FILE_ID");
            return this;
        }

        public Criteria andFILE_IDGreaterThan(BigDecimal value) {
            addCriterion("FILE_ID >", value, "FILE_ID");
            return this;
        }

        public Criteria andFILE_IDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FILE_ID >=", value, "FILE_ID");
            return this;
        }

        public Criteria andFILE_IDLessThan(BigDecimal value) {
            addCriterion("FILE_ID <", value, "FILE_ID");
            return this;
        }

        public Criteria andFILE_IDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FILE_ID <=", value, "FILE_ID");
            return this;
        }

        public Criteria andFILE_IDIn(List values) {
            addCriterion("FILE_ID in", values, "FILE_ID");
            return this;
        }

        public Criteria andFILE_IDNotIn(List values) {
            addCriterion("FILE_ID not in", values, "FILE_ID");
            return this;
        }

        public Criteria andFILE_IDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILE_ID between", value1, value2, "FILE_ID");
            return this;
        }

        public Criteria andFILE_IDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILE_ID not between", value1, value2, "FILE_ID");
            return this;
        }

        public Criteria andFILE_NAMEIsNull() {
            addCriterion("FILE_NAME is null");
            return this;
        }

        public Criteria andFILE_NAMEIsNotNull() {
            addCriterion("FILE_NAME is not null");
            return this;
        }

        public Criteria andFILE_NAMEEqualTo(String value) {
            addCriterion("FILE_NAME =", value, "FILE_NAME");
            return this;
        }

        public Criteria andFILE_NAMENotEqualTo(String value) {
            addCriterion("FILE_NAME <>", value, "FILE_NAME");
            return this;
        }

        public Criteria andFILE_NAMEGreaterThan(String value) {
            addCriterion("FILE_NAME >", value, "FILE_NAME");
            return this;
        }

        public Criteria andFILE_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_NAME >=", value, "FILE_NAME");
            return this;
        }

        public Criteria andFILE_NAMELessThan(String value) {
            addCriterion("FILE_NAME <", value, "FILE_NAME");
            return this;
        }

        public Criteria andFILE_NAMELessThanOrEqualTo(String value) {
            addCriterion("FILE_NAME <=", value, "FILE_NAME");
            return this;
        }

        public Criteria andFILE_NAMELike(String value) {
            addCriterion("FILE_NAME like", value, "FILE_NAME");
            return this;
        }

        public Criteria andFILE_NAMENotLike(String value) {
            addCriterion("FILE_NAME not like", value, "FILE_NAME");
            return this;
        }

        public Criteria andFILE_NAMEIn(List values) {
            addCriterion("FILE_NAME in", values, "FILE_NAME");
            return this;
        }

        public Criteria andFILE_NAMENotIn(List values) {
            addCriterion("FILE_NAME not in", values, "FILE_NAME");
            return this;
        }

        public Criteria andFILE_NAMEBetween(String value1, String value2) {
            addCriterion("FILE_NAME between", value1, value2, "FILE_NAME");
            return this;
        }

        public Criteria andFILE_NAMENotBetween(String value1, String value2) {
            addCriterion("FILE_NAME not between", value1, value2, "FILE_NAME");
            return this;
        }

        public Criteria andORIGINAL_FILE_NAMEIsNull() {
            addCriterion("ORIGINAL_FILE_NAME is null");
            return this;
        }

        public Criteria andORIGINAL_FILE_NAMEIsNotNull() {
            addCriterion("ORIGINAL_FILE_NAME is not null");
            return this;
        }

        public Criteria andORIGINAL_FILE_NAMEEqualTo(String value) {
            addCriterion("ORIGINAL_FILE_NAME =", value, "ORIGINAL_FILE_NAME");
            return this;
        }

        public Criteria andORIGINAL_FILE_NAMENotEqualTo(String value) {
            addCriterion("ORIGINAL_FILE_NAME <>", value, "ORIGINAL_FILE_NAME");
            return this;
        }

        public Criteria andORIGINAL_FILE_NAMEGreaterThan(String value) {
            addCriterion("ORIGINAL_FILE_NAME >", value, "ORIGINAL_FILE_NAME");
            return this;
        }

        public Criteria andORIGINAL_FILE_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("ORIGINAL_FILE_NAME >=", value, "ORIGINAL_FILE_NAME");
            return this;
        }

        public Criteria andORIGINAL_FILE_NAMELessThan(String value) {
            addCriterion("ORIGINAL_FILE_NAME <", value, "ORIGINAL_FILE_NAME");
            return this;
        }

        public Criteria andORIGINAL_FILE_NAMELessThanOrEqualTo(String value) {
            addCriterion("ORIGINAL_FILE_NAME <=", value, "ORIGINAL_FILE_NAME");
            return this;
        }

        public Criteria andORIGINAL_FILE_NAMELike(String value) {
            addCriterion("ORIGINAL_FILE_NAME like", value, "ORIGINAL_FILE_NAME");
            return this;
        }

        public Criteria andORIGINAL_FILE_NAMENotLike(String value) {
            addCriterion("ORIGINAL_FILE_NAME not like", value, "ORIGINAL_FILE_NAME");
            return this;
        }

        public Criteria andORIGINAL_FILE_NAMEIn(List values) {
            addCriterion("ORIGINAL_FILE_NAME in", values, "ORIGINAL_FILE_NAME");
            return this;
        }

        public Criteria andORIGINAL_FILE_NAMENotIn(List values) {
            addCriterion("ORIGINAL_FILE_NAME not in", values, "ORIGINAL_FILE_NAME");
            return this;
        }

        public Criteria andORIGINAL_FILE_NAMEBetween(String value1, String value2) {
            addCriterion("ORIGINAL_FILE_NAME between", value1, value2, "ORIGINAL_FILE_NAME");
            return this;
        }

        public Criteria andORIGINAL_FILE_NAMENotBetween(String value1, String value2) {
            addCriterion("ORIGINAL_FILE_NAME not between", value1, value2, "ORIGINAL_FILE_NAME");
            return this;
        }

        public Criteria andSUFFIX_CODEIsNull() {
            addCriterion("SUFFIX_CODE is null");
            return this;
        }

        public Criteria andSUFFIX_CODEIsNotNull() {
            addCriterion("SUFFIX_CODE is not null");
            return this;
        }

        public Criteria andSUFFIX_CODEEqualTo(String value) {
            addCriterion("SUFFIX_CODE =", value, "SUFFIX_CODE");
            return this;
        }

        public Criteria andSUFFIX_CODENotEqualTo(String value) {
            addCriterion("SUFFIX_CODE <>", value, "SUFFIX_CODE");
            return this;
        }

        public Criteria andSUFFIX_CODEGreaterThan(String value) {
            addCriterion("SUFFIX_CODE >", value, "SUFFIX_CODE");
            return this;
        }

        public Criteria andSUFFIX_CODEGreaterThanOrEqualTo(String value) {
            addCriterion("SUFFIX_CODE >=", value, "SUFFIX_CODE");
            return this;
        }

        public Criteria andSUFFIX_CODELessThan(String value) {
            addCriterion("SUFFIX_CODE <", value, "SUFFIX_CODE");
            return this;
        }

        public Criteria andSUFFIX_CODELessThanOrEqualTo(String value) {
            addCriterion("SUFFIX_CODE <=", value, "SUFFIX_CODE");
            return this;
        }

        public Criteria andSUFFIX_CODELike(String value) {
            addCriterion("SUFFIX_CODE like", value, "SUFFIX_CODE");
            return this;
        }

        public Criteria andSUFFIX_CODENotLike(String value) {
            addCriterion("SUFFIX_CODE not like", value, "SUFFIX_CODE");
            return this;
        }

        public Criteria andSUFFIX_CODEIn(List values) {
            addCriterion("SUFFIX_CODE in", values, "SUFFIX_CODE");
            return this;
        }

        public Criteria andSUFFIX_CODENotIn(List values) {
            addCriterion("SUFFIX_CODE not in", values, "SUFFIX_CODE");
            return this;
        }

        public Criteria andSUFFIX_CODEBetween(String value1, String value2) {
            addCriterion("SUFFIX_CODE between", value1, value2, "SUFFIX_CODE");
            return this;
        }

        public Criteria andSUFFIX_CODENotBetween(String value1, String value2) {
            addCriterion("SUFFIX_CODE not between", value1, value2, "SUFFIX_CODE");
            return this;
        }

        public Criteria andFILE_PATHIsNull() {
            addCriterion("FILE_PATH is null");
            return this;
        }

        public Criteria andFILE_PATHIsNotNull() {
            addCriterion("FILE_PATH is not null");
            return this;
        }

        public Criteria andFILE_PATHEqualTo(String value) {
            addCriterion("FILE_PATH =", value, "FILE_PATH");
            return this;
        }

        public Criteria andFILE_PATHNotEqualTo(String value) {
            addCriterion("FILE_PATH <>", value, "FILE_PATH");
            return this;
        }

        public Criteria andFILE_PATHGreaterThan(String value) {
            addCriterion("FILE_PATH >", value, "FILE_PATH");
            return this;
        }

        public Criteria andFILE_PATHGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_PATH >=", value, "FILE_PATH");
            return this;
        }

        public Criteria andFILE_PATHLessThan(String value) {
            addCriterion("FILE_PATH <", value, "FILE_PATH");
            return this;
        }

        public Criteria andFILE_PATHLessThanOrEqualTo(String value) {
            addCriterion("FILE_PATH <=", value, "FILE_PATH");
            return this;
        }

        public Criteria andFILE_PATHLike(String value) {
            addCriterion("FILE_PATH like", value, "FILE_PATH");
            return this;
        }

        public Criteria andFILE_PATHNotLike(String value) {
            addCriterion("FILE_PATH not like", value, "FILE_PATH");
            return this;
        }

        public Criteria andFILE_PATHIn(List values) {
            addCriterion("FILE_PATH in", values, "FILE_PATH");
            return this;
        }

        public Criteria andFILE_PATHNotIn(List values) {
            addCriterion("FILE_PATH not in", values, "FILE_PATH");
            return this;
        }

        public Criteria andFILE_PATHBetween(String value1, String value2) {
            addCriterion("FILE_PATH between", value1, value2, "FILE_PATH");
            return this;
        }

        public Criteria andFILE_PATHNotBetween(String value1, String value2) {
            addCriterion("FILE_PATH not between", value1, value2, "FILE_PATH");
            return this;
        }

        public Criteria andFILE_SIZEIsNull() {
            addCriterion("FILE_SIZE is null");
            return this;
        }

        public Criteria andFILE_SIZEIsNotNull() {
            addCriterion("FILE_SIZE is not null");
            return this;
        }

        public Criteria andFILE_SIZEEqualTo(BigDecimal value) {
            addCriterion("FILE_SIZE =", value, "FILE_SIZE");
            return this;
        }

        public Criteria andFILE_SIZENotEqualTo(BigDecimal value) {
            addCriterion("FILE_SIZE <>", value, "FILE_SIZE");
            return this;
        }

        public Criteria andFILE_SIZEGreaterThan(BigDecimal value) {
            addCriterion("FILE_SIZE >", value, "FILE_SIZE");
            return this;
        }

        public Criteria andFILE_SIZEGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FILE_SIZE >=", value, "FILE_SIZE");
            return this;
        }

        public Criteria andFILE_SIZELessThan(BigDecimal value) {
            addCriterion("FILE_SIZE <", value, "FILE_SIZE");
            return this;
        }

        public Criteria andFILE_SIZELessThanOrEqualTo(BigDecimal value) {
            addCriterion("FILE_SIZE <=", value, "FILE_SIZE");
            return this;
        }

        public Criteria andFILE_SIZEIn(List values) {
            addCriterion("FILE_SIZE in", values, "FILE_SIZE");
            return this;
        }

        public Criteria andFILE_SIZENotIn(List values) {
            addCriterion("FILE_SIZE not in", values, "FILE_SIZE");
            return this;
        }

        public Criteria andFILE_SIZEBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILE_SIZE between", value1, value2, "FILE_SIZE");
            return this;
        }

        public Criteria andFILE_SIZENotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILE_SIZE not between", value1, value2, "FILE_SIZE");
            return this;
        }

        public Criteria andBILL_IDIsNull() {
            addCriterion("BILL_ID is null");
            return this;
        }

        public Criteria andBILL_IDIsNotNull() {
            addCriterion("BILL_ID is not null");
            return this;
        }

        public Criteria andBILL_IDEqualTo(BigDecimal value) {
            addCriterion("BILL_ID =", value, "BILL_ID");
            return this;
        }

        public Criteria andBILL_IDNotEqualTo(BigDecimal value) {
            addCriterion("BILL_ID <>", value, "BILL_ID");
            return this;
        }

        public Criteria andBILL_IDGreaterThan(BigDecimal value) {
            addCriterion("BILL_ID >", value, "BILL_ID");
            return this;
        }

        public Criteria andBILL_IDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BILL_ID >=", value, "BILL_ID");
            return this;
        }

        public Criteria andBILL_IDLessThan(BigDecimal value) {
            addCriterion("BILL_ID <", value, "BILL_ID");
            return this;
        }

        public Criteria andBILL_IDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BILL_ID <=", value, "BILL_ID");
            return this;
        }

        public Criteria andBILL_IDIn(List values) {
            addCriterion("BILL_ID in", values, "BILL_ID");
            return this;
        }

        public Criteria andBILL_IDNotIn(List values) {
            addCriterion("BILL_ID not in", values, "BILL_ID");
            return this;
        }

        public Criteria andBILL_IDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BILL_ID between", value1, value2, "BILL_ID");
            return this;
        }

        public Criteria andBILL_IDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BILL_ID not between", value1, value2, "BILL_ID");
            return this;
        }

        public Criteria andBILL_TYPEIsNull() {
            addCriterion("BILL_TYPE is null");
            return this;
        }

        public Criteria andBILL_TYPEIsNotNull() {
            addCriterion("BILL_TYPE is not null");
            return this;
        }

        public Criteria andBILL_TYPEEqualTo(String value) {
            addCriterion("BILL_TYPE =", value, "BILL_TYPE");
            return this;
        }

        public Criteria andBILL_TYPENotEqualTo(String value) {
            addCriterion("BILL_TYPE <>", value, "BILL_TYPE");
            return this;
        }

        public Criteria andBILL_TYPEGreaterThan(String value) {
            addCriterion("BILL_TYPE >", value, "BILL_TYPE");
            return this;
        }

        public Criteria andBILL_TYPEGreaterThanOrEqualTo(String value) {
            addCriterion("BILL_TYPE >=", value, "BILL_TYPE");
            return this;
        }

        public Criteria andBILL_TYPELessThan(String value) {
            addCriterion("BILL_TYPE <", value, "BILL_TYPE");
            return this;
        }

        public Criteria andBILL_TYPELessThanOrEqualTo(String value) {
            addCriterion("BILL_TYPE <=", value, "BILL_TYPE");
            return this;
        }

        public Criteria andBILL_TYPELike(String value) {
            addCriterion("BILL_TYPE like", value, "BILL_TYPE");
            return this;
        }

        public Criteria andBILL_TYPENotLike(String value) {
            addCriterion("BILL_TYPE not like", value, "BILL_TYPE");
            return this;
        }

        public Criteria andBILL_TYPEIn(List values) {
            addCriterion("BILL_TYPE in", values, "BILL_TYPE");
            return this;
        }

        public Criteria andBILL_TYPENotIn(List values) {
            addCriterion("BILL_TYPE not in", values, "BILL_TYPE");
            return this;
        }

        public Criteria andBILL_TYPEBetween(String value1, String value2) {
            addCriterion("BILL_TYPE between", value1, value2, "BILL_TYPE");
            return this;
        }

        public Criteria andBILL_TYPENotBetween(String value1, String value2) {
            addCriterion("BILL_TYPE not between", value1, value2, "BILL_TYPE");
            return this;
        }

        public Criteria andBILL_ATTACHMENT_CODEIsNull() {
            addCriterion("BILL_ATTACHMENT_CODE is null");
            return this;
        }

        public Criteria andBILL_ATTACHMENT_CODEIsNotNull() {
            addCriterion("BILL_ATTACHMENT_CODE is not null");
            return this;
        }

        public Criteria andBILL_ATTACHMENT_CODEEqualTo(String value) {
            addCriterion("BILL_ATTACHMENT_CODE =", value, "BILL_ATTACHMENT_CODE");
            return this;
        }

        public Criteria andBILL_ATTACHMENT_CODENotEqualTo(String value) {
            addCriterion("BILL_ATTACHMENT_CODE <>", value, "BILL_ATTACHMENT_CODE");
            return this;
        }

        public Criteria andBILL_ATTACHMENT_CODEGreaterThan(String value) {
            addCriterion("BILL_ATTACHMENT_CODE >", value, "BILL_ATTACHMENT_CODE");
            return this;
        }

        public Criteria andBILL_ATTACHMENT_CODEGreaterThanOrEqualTo(String value) {
            addCriterion("BILL_ATTACHMENT_CODE >=", value, "BILL_ATTACHMENT_CODE");
            return this;
        }

        public Criteria andBILL_ATTACHMENT_CODELessThan(String value) {
            addCriterion("BILL_ATTACHMENT_CODE <", value, "BILL_ATTACHMENT_CODE");
            return this;
        }

        public Criteria andBILL_ATTACHMENT_CODELessThanOrEqualTo(String value) {
            addCriterion("BILL_ATTACHMENT_CODE <=", value, "BILL_ATTACHMENT_CODE");
            return this;
        }

        public Criteria andBILL_ATTACHMENT_CODELike(String value) {
            addCriterion("BILL_ATTACHMENT_CODE like", value, "BILL_ATTACHMENT_CODE");
            return this;
        }

        public Criteria andBILL_ATTACHMENT_CODENotLike(String value) {
            addCriterion("BILL_ATTACHMENT_CODE not like", value, "BILL_ATTACHMENT_CODE");
            return this;
        }

        public Criteria andBILL_ATTACHMENT_CODEIn(List values) {
            addCriterion("BILL_ATTACHMENT_CODE in", values, "BILL_ATTACHMENT_CODE");
            return this;
        }

        public Criteria andBILL_ATTACHMENT_CODENotIn(List values) {
            addCriterion("BILL_ATTACHMENT_CODE not in", values, "BILL_ATTACHMENT_CODE");
            return this;
        }

        public Criteria andBILL_ATTACHMENT_CODEBetween(String value1, String value2) {
            addCriterion("BILL_ATTACHMENT_CODE between", value1, value2, "BILL_ATTACHMENT_CODE");
            return this;
        }

        public Criteria andBILL_ATTACHMENT_CODENotBetween(String value1, String value2) {
            addCriterion("BILL_ATTACHMENT_CODE not between", value1, value2, "BILL_ATTACHMENT_CODE");
            return this;
        }

        public Criteria andDISABLEDIsNull() {
            addCriterion("DISABLED is null");
            return this;
        }

        public Criteria andDISABLEDIsNotNull() {
            addCriterion("DISABLED is not null");
            return this;
        }

        public Criteria andDISABLEDEqualTo(String value) {
            addCriterion("DISABLED =", value, "DISABLED");
            return this;
        }

        public Criteria andDISABLEDNotEqualTo(String value) {
            addCriterion("DISABLED <>", value, "DISABLED");
            return this;
        }

        public Criteria andDISABLEDGreaterThan(String value) {
            addCriterion("DISABLED >", value, "DISABLED");
            return this;
        }

        public Criteria andDISABLEDGreaterThanOrEqualTo(String value) {
            addCriterion("DISABLED >=", value, "DISABLED");
            return this;
        }

        public Criteria andDISABLEDLessThan(String value) {
            addCriterion("DISABLED <", value, "DISABLED");
            return this;
        }

        public Criteria andDISABLEDLessThanOrEqualTo(String value) {
            addCriterion("DISABLED <=", value, "DISABLED");
            return this;
        }

        public Criteria andDISABLEDLike(String value) {
            addCriterion("DISABLED like", value, "DISABLED");
            return this;
        }

        public Criteria andDISABLEDNotLike(String value) {
            addCriterion("DISABLED not like", value, "DISABLED");
            return this;
        }

        public Criteria andDISABLEDIn(List values) {
            addCriterion("DISABLED in", values, "DISABLED");
            return this;
        }

        public Criteria andDISABLEDNotIn(List values) {
            addCriterion("DISABLED not in", values, "DISABLED");
            return this;
        }

        public Criteria andDISABLEDBetween(String value1, String value2) {
            addCriterion("DISABLED between", value1, value2, "DISABLED");
            return this;
        }

        public Criteria andDISABLEDNotBetween(String value1, String value2) {
            addCriterion("DISABLED not between", value1, value2, "DISABLED");
            return this;
        }

        public Criteria andCREATED_BYIsNull() {
            addCriterion("CREATED_BY is null");
            return this;
        }

        public Criteria andCREATED_BYIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return this;
        }

        public Criteria andCREATED_BYEqualTo(BigDecimal value) {
            addCriterion("CREATED_BY =", value, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYNotEqualTo(BigDecimal value) {
            addCriterion("CREATED_BY <>", value, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYGreaterThan(BigDecimal value) {
            addCriterion("CREATED_BY >", value, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CREATED_BY >=", value, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYLessThan(BigDecimal value) {
            addCriterion("CREATED_BY <", value, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CREATED_BY <=", value, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYIn(List values) {
            addCriterion("CREATED_BY in", values, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYNotIn(List values) {
            addCriterion("CREATED_BY not in", values, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREATED_BY between", value1, value2, "CREATED_BY");
            return this;
        }

        public Criteria andCREATED_BYNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREATED_BY not between", value1, value2, "CREATED_BY");
            return this;
        }

        public Criteria andCREATION_DATEIsNull() {
            addCriterion("CREATION_DATE is null");
            return this;
        }

        public Criteria andCREATION_DATEIsNotNull() {
            addCriterion("CREATION_DATE is not null");
            return this;
        }

        public Criteria andCREATION_DATEEqualTo(Date value) {
            addCriterionForJDBCDate("CREATION_DATE =", value, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATENotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATION_DATE <>", value, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATEGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATION_DATE >", value, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATEGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATION_DATE >=", value, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATELessThan(Date value) {
            addCriterionForJDBCDate("CREATION_DATE <", value, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATELessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATION_DATE <=", value, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATEIn(List values) {
            addCriterionForJDBCDate("CREATION_DATE in", values, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATENotIn(List values) {
            addCriterionForJDBCDate("CREATION_DATE not in", values, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATEBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATION_DATE between", value1, value2, "CREATION_DATE");
            return this;
        }

        public Criteria andCREATION_DATENotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATION_DATE not between", value1, value2, "CREATION_DATE");
            return this;
        }

        public Criteria andLAST_UPDATED_BYIsNull() {
            addCriterion("LAST_UPDATED_BY is null");
            return this;
        }

        public Criteria andLAST_UPDATED_BYIsNotNull() {
            addCriterion("LAST_UPDATED_BY is not null");
            return this;
        }

        public Criteria andLAST_UPDATED_BYEqualTo(BigDecimal value) {
            addCriterion("LAST_UPDATED_BY =", value, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYNotEqualTo(BigDecimal value) {
            addCriterion("LAST_UPDATED_BY <>", value, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYGreaterThan(BigDecimal value) {
            addCriterion("LAST_UPDATED_BY >", value, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LAST_UPDATED_BY >=", value, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYLessThan(BigDecimal value) {
            addCriterion("LAST_UPDATED_BY <", value, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LAST_UPDATED_BY <=", value, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYIn(List values) {
            addCriterion("LAST_UPDATED_BY in", values, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYNotIn(List values) {
            addCriterion("LAST_UPDATED_BY not in", values, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAST_UPDATED_BY between", value1, value2, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATED_BYNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAST_UPDATED_BY not between", value1, value2, "LAST_UPDATED_BY");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEIsNull() {
            addCriterion("LAST_UPDATE_DATE is null");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEIsNotNull() {
            addCriterion("LAST_UPDATE_DATE is not null");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE =", value, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATENotEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE <>", value, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEGreaterThan(Date value) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE >", value, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE >=", value, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATELessThan(Date value) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE <", value, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATELessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE <=", value, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEIn(List values) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE in", values, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATENotIn(List values) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE not in", values, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATEBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE between", value1, value2, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andLAST_UPDATE_DATENotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LAST_UPDATE_DATE not between", value1, value2, "LAST_UPDATE_DATE");
            return this;
        }

        public Criteria andDESCRIPTIONIsNull() {
            addCriterion("DESCRIPTION is null");
            return this;
        }

        public Criteria andDESCRIPTIONIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return this;
        }

        public Criteria andDESCRIPTIONEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONLike(String value) {
            addCriterion("DESCRIPTION like", value, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONIn(List values) {
            addCriterion("DESCRIPTION in", values, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONNotIn(List values) {
            addCriterion("DESCRIPTION not in", values, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "DESCRIPTION");
            return this;
        }

        public Criteria andDESCRIPTIONNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "DESCRIPTION");
            return this;
        }
    }
}