package com.notice.model;

import java.math.BigDecimal;
import java.util.Date;

public class SysParamAll {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_PARAM_ALL.PARAM_ID
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	private BigDecimal PARAM_ID;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_PARAM_ALL.TASK_ID
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	private BigDecimal TASK_ID;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_PARAM_ALL.PARAM_NAME
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	private String PARAM_NAME;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_PARAM_ALL.PARAM_VALUE
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	private String PARAM_VALUE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_PARAM_ALL.ENABLE_DATE
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	private Date ENABLE_DATE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_PARAM_ALL.DISABLE_DATE
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	private Date DISABLE_DATE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_PARAM_ALL.CREATED_DATE
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	private Date CREATED_DATE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_PARAM_ALL.CREATED_BY
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	private BigDecimal CREATED_BY;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_PARAM_ALL.LAST_UPDATED_DATE
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	private Date LAST_UPDATED_DATE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_PARAM_ALL.LAST_UPDATED_BY
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	private BigDecimal LAST_UPDATED_BY;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_PARAM_ALL.DESCRIPTION
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	private String DESCRIPTION;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_PARAM_ALL.PARAM_ID
	 * @return  the value of SYS_PARAM_ALL.PARAM_ID
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public BigDecimal getPARAM_ID() {
		return PARAM_ID;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_PARAM_ALL.PARAM_ID
	 * @param PARAM_ID  the value for SYS_PARAM_ALL.PARAM_ID
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public void setPARAM_ID(BigDecimal PARAM_ID) {
		this.PARAM_ID = PARAM_ID;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_PARAM_ALL.TASK_ID
	 * @return  the value of SYS_PARAM_ALL.TASK_ID
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public BigDecimal getTASK_ID() {
		return TASK_ID;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_PARAM_ALL.TASK_ID
	 * @param TASK_ID  the value for SYS_PARAM_ALL.TASK_ID
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public void setTASK_ID(BigDecimal TASK_ID) {
		this.TASK_ID = TASK_ID;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_PARAM_ALL.PARAM_NAME
	 * @return  the value of SYS_PARAM_ALL.PARAM_NAME
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public String getPARAM_NAME() {
		return PARAM_NAME;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_PARAM_ALL.PARAM_NAME
	 * @param PARAM_NAME  the value for SYS_PARAM_ALL.PARAM_NAME
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public void setPARAM_NAME(String PARAM_NAME) {
		this.PARAM_NAME = PARAM_NAME;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_PARAM_ALL.PARAM_VALUE
	 * @return  the value of SYS_PARAM_ALL.PARAM_VALUE
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public String getPARAM_VALUE() {
		return PARAM_VALUE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_PARAM_ALL.PARAM_VALUE
	 * @param PARAM_VALUE  the value for SYS_PARAM_ALL.PARAM_VALUE
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public void setPARAM_VALUE(String PARAM_VALUE) {
		this.PARAM_VALUE = PARAM_VALUE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_PARAM_ALL.ENABLE_DATE
	 * @return  the value of SYS_PARAM_ALL.ENABLE_DATE
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public Date getENABLE_DATE() {
		return ENABLE_DATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_PARAM_ALL.ENABLE_DATE
	 * @param ENABLE_DATE  the value for SYS_PARAM_ALL.ENABLE_DATE
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public void setENABLE_DATE(Date ENABLE_DATE) {
		this.ENABLE_DATE = ENABLE_DATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_PARAM_ALL.DISABLE_DATE
	 * @return  the value of SYS_PARAM_ALL.DISABLE_DATE
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public Date getDISABLE_DATE() {
		return DISABLE_DATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_PARAM_ALL.DISABLE_DATE
	 * @param DISABLE_DATE  the value for SYS_PARAM_ALL.DISABLE_DATE
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public void setDISABLE_DATE(Date DISABLE_DATE) {
		this.DISABLE_DATE = DISABLE_DATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_PARAM_ALL.CREATED_DATE
	 * @return  the value of SYS_PARAM_ALL.CREATED_DATE
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public Date getCREATED_DATE() {
		return CREATED_DATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_PARAM_ALL.CREATED_DATE
	 * @param CREATED_DATE  the value for SYS_PARAM_ALL.CREATED_DATE
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public void setCREATED_DATE(Date CREATED_DATE) {
		this.CREATED_DATE = CREATED_DATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_PARAM_ALL.CREATED_BY
	 * @return  the value of SYS_PARAM_ALL.CREATED_BY
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public BigDecimal getCREATED_BY() {
		return CREATED_BY;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_PARAM_ALL.CREATED_BY
	 * @param CREATED_BY  the value for SYS_PARAM_ALL.CREATED_BY
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public void setCREATED_BY(BigDecimal CREATED_BY) {
		this.CREATED_BY = CREATED_BY;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_PARAM_ALL.LAST_UPDATED_DATE
	 * @return  the value of SYS_PARAM_ALL.LAST_UPDATED_DATE
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public Date getLAST_UPDATED_DATE() {
		return LAST_UPDATED_DATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_PARAM_ALL.LAST_UPDATED_DATE
	 * @param LAST_UPDATED_DATE  the value for SYS_PARAM_ALL.LAST_UPDATED_DATE
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public void setLAST_UPDATED_DATE(Date LAST_UPDATED_DATE) {
		this.LAST_UPDATED_DATE = LAST_UPDATED_DATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_PARAM_ALL.LAST_UPDATED_BY
	 * @return  the value of SYS_PARAM_ALL.LAST_UPDATED_BY
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public BigDecimal getLAST_UPDATED_BY() {
		return LAST_UPDATED_BY;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_PARAM_ALL.LAST_UPDATED_BY
	 * @param LAST_UPDATED_BY  the value for SYS_PARAM_ALL.LAST_UPDATED_BY
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public void setLAST_UPDATED_BY(BigDecimal LAST_UPDATED_BY) {
		this.LAST_UPDATED_BY = LAST_UPDATED_BY;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_PARAM_ALL.DESCRIPTION
	 * @return  the value of SYS_PARAM_ALL.DESCRIPTION
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public String getDESCRIPTION() {
		return DESCRIPTION;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_PARAM_ALL.DESCRIPTION
	 * @param DESCRIPTION  the value for SYS_PARAM_ALL.DESCRIPTION
	 * @abatorgenerated  Fri May 24 18:29:49 CST 2013
	 */
	public void setDESCRIPTION(String DESCRIPTION) {
		this.DESCRIPTION = DESCRIPTION;
	}
}