package com.notice.model;

import java.math.BigDecimal;
import java.util.Date;

public class SysTaskAll {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.TASK_ID
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private BigDecimal TASK_ID;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.TASK_NAME
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private String TASK_NAME;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.TASK_EXE_CYCLE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private BigDecimal TASK_EXE_CYCLE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.LAST_EXE_TIME
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private Date LAST_EXE_TIME;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.IS_SEND_EMAIL
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private BigDecimal IS_SEND_EMAIL;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.EMAIL_TITLE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private String EMAIL_TITLE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.ENABLE_DATE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private Date ENABLE_DATE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.DISABLE_DATE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private Date DISABLE_DATE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.DESCRIPTION
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private String DESCRIPTION;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.ATTRIBUTE1
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private String ATTRIBUTE1;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.ATTRIBUTE2
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private String ATTRIBUTE2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.ATTRIBUTE3
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private String ATTRIBUTE3;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.ATTRIBUTE4
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private String ATTRIBUTE4;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.ATTRIBUTE5
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private String ATTRIBUTE5;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.CREATED_BY
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private BigDecimal CREATED_BY;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.CREATION_DATE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private Date CREATION_DATE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.LAST_UPDATED_BY
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private BigDecimal LAST_UPDATED_BY;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.LAST_UPDATE_DATE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private Date LAST_UPDATE_DATE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.STATUS
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private String STATUS;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.NODE_STATUS
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private String NODE_STATUS;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.TASK_EXE_CYCLE_VALUE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private BigDecimal TASK_EXE_CYCLE_VALUE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.TASK_EXE_CYCLE_TYPE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private String TASK_EXE_CYCLE_TYPE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.TASK_EXE_DATE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private Date TASK_EXE_DATE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.WEEKDAY_VALUE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private String WEEKDAY_VALUE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_TASK_ALL.WORKDAY_EXE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	private String WORKDAY_EXE;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.TASK_ID
	 * @return  the value of SYS_TASK_ALL.TASK_ID
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public BigDecimal getTASK_ID() {
		return TASK_ID;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.TASK_ID
	 * @param TASK_ID  the value for SYS_TASK_ALL.TASK_ID
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setTASK_ID(BigDecimal TASK_ID) {
		this.TASK_ID = TASK_ID;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.TASK_NAME
	 * @return  the value of SYS_TASK_ALL.TASK_NAME
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public String getTASK_NAME() {
		return TASK_NAME;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.TASK_NAME
	 * @param TASK_NAME  the value for SYS_TASK_ALL.TASK_NAME
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setTASK_NAME(String TASK_NAME) {
		this.TASK_NAME = TASK_NAME;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.TASK_EXE_CYCLE
	 * @return  the value of SYS_TASK_ALL.TASK_EXE_CYCLE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public BigDecimal getTASK_EXE_CYCLE() {
		return TASK_EXE_CYCLE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.TASK_EXE_CYCLE
	 * @param TASK_EXE_CYCLE  the value for SYS_TASK_ALL.TASK_EXE_CYCLE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setTASK_EXE_CYCLE(BigDecimal TASK_EXE_CYCLE) {
		this.TASK_EXE_CYCLE = TASK_EXE_CYCLE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.LAST_EXE_TIME
	 * @return  the value of SYS_TASK_ALL.LAST_EXE_TIME
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public Date getLAST_EXE_TIME() {
		return LAST_EXE_TIME;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.LAST_EXE_TIME
	 * @param LAST_EXE_TIME  the value for SYS_TASK_ALL.LAST_EXE_TIME
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setLAST_EXE_TIME(Date LAST_EXE_TIME) {
		this.LAST_EXE_TIME = LAST_EXE_TIME;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.IS_SEND_EMAIL
	 * @return  the value of SYS_TASK_ALL.IS_SEND_EMAIL
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public BigDecimal getIS_SEND_EMAIL() {
		return IS_SEND_EMAIL;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.IS_SEND_EMAIL
	 * @param IS_SEND_EMAIL  the value for SYS_TASK_ALL.IS_SEND_EMAIL
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setIS_SEND_EMAIL(BigDecimal IS_SEND_EMAIL) {
		this.IS_SEND_EMAIL = IS_SEND_EMAIL;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.EMAIL_TITLE
	 * @return  the value of SYS_TASK_ALL.EMAIL_TITLE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public String getEMAIL_TITLE() {
		return EMAIL_TITLE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.EMAIL_TITLE
	 * @param EMAIL_TITLE  the value for SYS_TASK_ALL.EMAIL_TITLE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setEMAIL_TITLE(String EMAIL_TITLE) {
		this.EMAIL_TITLE = EMAIL_TITLE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.ENABLE_DATE
	 * @return  the value of SYS_TASK_ALL.ENABLE_DATE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public Date getENABLE_DATE() {
		return ENABLE_DATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.ENABLE_DATE
	 * @param ENABLE_DATE  the value for SYS_TASK_ALL.ENABLE_DATE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setENABLE_DATE(Date ENABLE_DATE) {
		this.ENABLE_DATE = ENABLE_DATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.DISABLE_DATE
	 * @return  the value of SYS_TASK_ALL.DISABLE_DATE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public Date getDISABLE_DATE() {
		return DISABLE_DATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.DISABLE_DATE
	 * @param DISABLE_DATE  the value for SYS_TASK_ALL.DISABLE_DATE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setDISABLE_DATE(Date DISABLE_DATE) {
		this.DISABLE_DATE = DISABLE_DATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.DESCRIPTION
	 * @return  the value of SYS_TASK_ALL.DESCRIPTION
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public String getDESCRIPTION() {
		return DESCRIPTION;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.DESCRIPTION
	 * @param DESCRIPTION  the value for SYS_TASK_ALL.DESCRIPTION
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setDESCRIPTION(String DESCRIPTION) {
		this.DESCRIPTION = DESCRIPTION;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.ATTRIBUTE1
	 * @return  the value of SYS_TASK_ALL.ATTRIBUTE1
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public String getATTRIBUTE1() {
		return ATTRIBUTE1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.ATTRIBUTE1
	 * @param ATTRIBUTE1  the value for SYS_TASK_ALL.ATTRIBUTE1
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setATTRIBUTE1(String ATTRIBUTE1) {
		this.ATTRIBUTE1 = ATTRIBUTE1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.ATTRIBUTE2
	 * @return  the value of SYS_TASK_ALL.ATTRIBUTE2
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public String getATTRIBUTE2() {
		return ATTRIBUTE2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.ATTRIBUTE2
	 * @param ATTRIBUTE2  the value for SYS_TASK_ALL.ATTRIBUTE2
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setATTRIBUTE2(String ATTRIBUTE2) {
		this.ATTRIBUTE2 = ATTRIBUTE2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.ATTRIBUTE3
	 * @return  the value of SYS_TASK_ALL.ATTRIBUTE3
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public String getATTRIBUTE3() {
		return ATTRIBUTE3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.ATTRIBUTE3
	 * @param ATTRIBUTE3  the value for SYS_TASK_ALL.ATTRIBUTE3
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setATTRIBUTE3(String ATTRIBUTE3) {
		this.ATTRIBUTE3 = ATTRIBUTE3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.ATTRIBUTE4
	 * @return  the value of SYS_TASK_ALL.ATTRIBUTE4
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public String getATTRIBUTE4() {
		return ATTRIBUTE4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.ATTRIBUTE4
	 * @param ATTRIBUTE4  the value for SYS_TASK_ALL.ATTRIBUTE4
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setATTRIBUTE4(String ATTRIBUTE4) {
		this.ATTRIBUTE4 = ATTRIBUTE4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.ATTRIBUTE5
	 * @return  the value of SYS_TASK_ALL.ATTRIBUTE5
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public String getATTRIBUTE5() {
		return ATTRIBUTE5;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.ATTRIBUTE5
	 * @param ATTRIBUTE5  the value for SYS_TASK_ALL.ATTRIBUTE5
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setATTRIBUTE5(String ATTRIBUTE5) {
		this.ATTRIBUTE5 = ATTRIBUTE5;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.CREATED_BY
	 * @return  the value of SYS_TASK_ALL.CREATED_BY
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public BigDecimal getCREATED_BY() {
		return CREATED_BY;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.CREATED_BY
	 * @param CREATED_BY  the value for SYS_TASK_ALL.CREATED_BY
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setCREATED_BY(BigDecimal CREATED_BY) {
		this.CREATED_BY = CREATED_BY;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.CREATION_DATE
	 * @return  the value of SYS_TASK_ALL.CREATION_DATE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public Date getCREATION_DATE() {
		return CREATION_DATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.CREATION_DATE
	 * @param CREATION_DATE  the value for SYS_TASK_ALL.CREATION_DATE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setCREATION_DATE(Date CREATION_DATE) {
		this.CREATION_DATE = CREATION_DATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.LAST_UPDATED_BY
	 * @return  the value of SYS_TASK_ALL.LAST_UPDATED_BY
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public BigDecimal getLAST_UPDATED_BY() {
		return LAST_UPDATED_BY;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.LAST_UPDATED_BY
	 * @param LAST_UPDATED_BY  the value for SYS_TASK_ALL.LAST_UPDATED_BY
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setLAST_UPDATED_BY(BigDecimal LAST_UPDATED_BY) {
		this.LAST_UPDATED_BY = LAST_UPDATED_BY;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.LAST_UPDATE_DATE
	 * @return  the value of SYS_TASK_ALL.LAST_UPDATE_DATE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public Date getLAST_UPDATE_DATE() {
		return LAST_UPDATE_DATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.LAST_UPDATE_DATE
	 * @param LAST_UPDATE_DATE  the value for SYS_TASK_ALL.LAST_UPDATE_DATE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setLAST_UPDATE_DATE(Date LAST_UPDATE_DATE) {
		this.LAST_UPDATE_DATE = LAST_UPDATE_DATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.STATUS
	 * @return  the value of SYS_TASK_ALL.STATUS
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public String getSTATUS() {
		return STATUS;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.STATUS
	 * @param STATUS  the value for SYS_TASK_ALL.STATUS
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setSTATUS(String STATUS) {
		this.STATUS = STATUS;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.NODE_STATUS
	 * @return  the value of SYS_TASK_ALL.NODE_STATUS
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public String getNODE_STATUS() {
		return NODE_STATUS;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.NODE_STATUS
	 * @param NODE_STATUS  the value for SYS_TASK_ALL.NODE_STATUS
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setNODE_STATUS(String NODE_STATUS) {
		this.NODE_STATUS = NODE_STATUS;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.TASK_EXE_CYCLE_VALUE
	 * @return  the value of SYS_TASK_ALL.TASK_EXE_CYCLE_VALUE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public BigDecimal getTASK_EXE_CYCLE_VALUE() {
		return TASK_EXE_CYCLE_VALUE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.TASK_EXE_CYCLE_VALUE
	 * @param TASK_EXE_CYCLE_VALUE  the value for SYS_TASK_ALL.TASK_EXE_CYCLE_VALUE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setTASK_EXE_CYCLE_VALUE(BigDecimal TASK_EXE_CYCLE_VALUE) {
		this.TASK_EXE_CYCLE_VALUE = TASK_EXE_CYCLE_VALUE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.TASK_EXE_CYCLE_TYPE
	 * @return  the value of SYS_TASK_ALL.TASK_EXE_CYCLE_TYPE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public String getTASK_EXE_CYCLE_TYPE() {
		return TASK_EXE_CYCLE_TYPE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.TASK_EXE_CYCLE_TYPE
	 * @param TASK_EXE_CYCLE_TYPE  the value for SYS_TASK_ALL.TASK_EXE_CYCLE_TYPE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setTASK_EXE_CYCLE_TYPE(String TASK_EXE_CYCLE_TYPE) {
		this.TASK_EXE_CYCLE_TYPE = TASK_EXE_CYCLE_TYPE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.TASK_EXE_DATE
	 * @return  the value of SYS_TASK_ALL.TASK_EXE_DATE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public Date getTASK_EXE_DATE() {
		return TASK_EXE_DATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.TASK_EXE_DATE
	 * @param TASK_EXE_DATE  the value for SYS_TASK_ALL.TASK_EXE_DATE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setTASK_EXE_DATE(Date TASK_EXE_DATE) {
		this.TASK_EXE_DATE = TASK_EXE_DATE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.WEEKDAY_VALUE
	 * @return  the value of SYS_TASK_ALL.WEEKDAY_VALUE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public String getWEEKDAY_VALUE() {
		return WEEKDAY_VALUE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.WEEKDAY_VALUE
	 * @param WEEKDAY_VALUE  the value for SYS_TASK_ALL.WEEKDAY_VALUE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setWEEKDAY_VALUE(String WEEKDAY_VALUE) {
		this.WEEKDAY_VALUE = WEEKDAY_VALUE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_TASK_ALL.WORKDAY_EXE
	 * @return  the value of SYS_TASK_ALL.WORKDAY_EXE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public String getWORKDAY_EXE() {
		return WORKDAY_EXE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_TASK_ALL.WORKDAY_EXE
	 * @param WORKDAY_EXE  the value for SYS_TASK_ALL.WORKDAY_EXE
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setWORKDAY_EXE(String WORKDAY_EXE) {
		this.WORKDAY_EXE = WORKDAY_EXE;
	}
}