package com.notice.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class SysTaskAllExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table SYS_TASK_ALL
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table SYS_TASK_ALL
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_TASK_ALL
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public SysTaskAllExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_TASK_ALL
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	protected SysTaskAllExample(SysTaskAllExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_TASK_ALL
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_TASK_ALL
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_TASK_ALL
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_TASK_ALL
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_TASK_ALL
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_TASK_ALL
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_TASK_ALL
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table SYS_TASK_ALL
	 * @abatorgenerated  Fri May 24 18:29:46 CST 2013
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List dateList = new ArrayList();
			Iterator iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(((Date) iter.next()).getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andTASK_IDIsNull() {
			addCriterion("TASK_ID is null");
			return this;
		}

		public Criteria andTASK_IDIsNotNull() {
			addCriterion("TASK_ID is not null");
			return this;
		}

		public Criteria andTASK_IDEqualTo(BigDecimal value) {
			addCriterion("TASK_ID =", value, "TASK_ID");
			return this;
		}

		public Criteria andTASK_IDNotEqualTo(BigDecimal value) {
			addCriterion("TASK_ID <>", value, "TASK_ID");
			return this;
		}

		public Criteria andTASK_IDGreaterThan(BigDecimal value) {
			addCriterion("TASK_ID >", value, "TASK_ID");
			return this;
		}

		public Criteria andTASK_IDGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("TASK_ID >=", value, "TASK_ID");
			return this;
		}

		public Criteria andTASK_IDLessThan(BigDecimal value) {
			addCriterion("TASK_ID <", value, "TASK_ID");
			return this;
		}

		public Criteria andTASK_IDLessThanOrEqualTo(BigDecimal value) {
			addCriterion("TASK_ID <=", value, "TASK_ID");
			return this;
		}

		public Criteria andTASK_IDIn(List values) {
			addCriterion("TASK_ID in", values, "TASK_ID");
			return this;
		}

		public Criteria andTASK_IDNotIn(List values) {
			addCriterion("TASK_ID not in", values, "TASK_ID");
			return this;
		}

		public Criteria andTASK_IDBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("TASK_ID between", value1, value2, "TASK_ID");
			return this;
		}

		public Criteria andTASK_IDNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("TASK_ID not between", value1, value2, "TASK_ID");
			return this;
		}

		public Criteria andTASK_NAMEIsNull() {
			addCriterion("TASK_NAME is null");
			return this;
		}

		public Criteria andTASK_NAMEIsNotNull() {
			addCriterion("TASK_NAME is not null");
			return this;
		}

		public Criteria andTASK_NAMEEqualTo(String value) {
			addCriterion("TASK_NAME =", value, "TASK_NAME");
			return this;
		}

		public Criteria andTASK_NAMENotEqualTo(String value) {
			addCriterion("TASK_NAME <>", value, "TASK_NAME");
			return this;
		}

		public Criteria andTASK_NAMEGreaterThan(String value) {
			addCriterion("TASK_NAME >", value, "TASK_NAME");
			return this;
		}

		public Criteria andTASK_NAMEGreaterThanOrEqualTo(String value) {
			addCriterion("TASK_NAME >=", value, "TASK_NAME");
			return this;
		}

		public Criteria andTASK_NAMELessThan(String value) {
			addCriterion("TASK_NAME <", value, "TASK_NAME");
			return this;
		}

		public Criteria andTASK_NAMELessThanOrEqualTo(String value) {
			addCriterion("TASK_NAME <=", value, "TASK_NAME");
			return this;
		}

		public Criteria andTASK_NAMELike(String value) {
			addCriterion("TASK_NAME like", value, "TASK_NAME");
			return this;
		}

		public Criteria andTASK_NAMENotLike(String value) {
			addCriterion("TASK_NAME not like", value, "TASK_NAME");
			return this;
		}

		public Criteria andTASK_NAMEIn(List values) {
			addCriterion("TASK_NAME in", values, "TASK_NAME");
			return this;
		}

		public Criteria andTASK_NAMENotIn(List values) {
			addCriterion("TASK_NAME not in", values, "TASK_NAME");
			return this;
		}

		public Criteria andTASK_NAMEBetween(String value1, String value2) {
			addCriterion("TASK_NAME between", value1, value2, "TASK_NAME");
			return this;
		}

		public Criteria andTASK_NAMENotBetween(String value1, String value2) {
			addCriterion("TASK_NAME not between", value1, value2, "TASK_NAME");
			return this;
		}

		public Criteria andTASK_EXE_CYCLEIsNull() {
			addCriterion("TASK_EXE_CYCLE is null");
			return this;
		}

		public Criteria andTASK_EXE_CYCLEIsNotNull() {
			addCriterion("TASK_EXE_CYCLE is not null");
			return this;
		}

		public Criteria andTASK_EXE_CYCLEEqualTo(BigDecimal value) {
			addCriterion("TASK_EXE_CYCLE =", value, "TASK_EXE_CYCLE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLENotEqualTo(BigDecimal value) {
			addCriterion("TASK_EXE_CYCLE <>", value, "TASK_EXE_CYCLE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLEGreaterThan(BigDecimal value) {
			addCriterion("TASK_EXE_CYCLE >", value, "TASK_EXE_CYCLE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLEGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("TASK_EXE_CYCLE >=", value, "TASK_EXE_CYCLE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLELessThan(BigDecimal value) {
			addCriterion("TASK_EXE_CYCLE <", value, "TASK_EXE_CYCLE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLELessThanOrEqualTo(BigDecimal value) {
			addCriterion("TASK_EXE_CYCLE <=", value, "TASK_EXE_CYCLE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLEIn(List values) {
			addCriterion("TASK_EXE_CYCLE in", values, "TASK_EXE_CYCLE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLENotIn(List values) {
			addCriterion("TASK_EXE_CYCLE not in", values, "TASK_EXE_CYCLE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLEBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("TASK_EXE_CYCLE between", value1, value2, "TASK_EXE_CYCLE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLENotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("TASK_EXE_CYCLE not between", value1, value2, "TASK_EXE_CYCLE");
			return this;
		}

		public Criteria andLAST_EXE_TIMEIsNull() {
			addCriterion("LAST_EXE_TIME is null");
			return this;
		}

		public Criteria andLAST_EXE_TIMEIsNotNull() {
			addCriterion("LAST_EXE_TIME is not null");
			return this;
		}

		public Criteria andLAST_EXE_TIMEEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_EXE_TIME =", value, "LAST_EXE_TIME");
			return this;
		}

		public Criteria andLAST_EXE_TIMENotEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_EXE_TIME <>", value, "LAST_EXE_TIME");
			return this;
		}

		public Criteria andLAST_EXE_TIMEGreaterThan(Date value) {
			addCriterionForJDBCDate("LAST_EXE_TIME >", value, "LAST_EXE_TIME");
			return this;
		}

		public Criteria andLAST_EXE_TIMEGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_EXE_TIME >=", value, "LAST_EXE_TIME");
			return this;
		}

		public Criteria andLAST_EXE_TIMELessThan(Date value) {
			addCriterionForJDBCDate("LAST_EXE_TIME <", value, "LAST_EXE_TIME");
			return this;
		}

		public Criteria andLAST_EXE_TIMELessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_EXE_TIME <=", value, "LAST_EXE_TIME");
			return this;
		}

		public Criteria andLAST_EXE_TIMEIn(List values) {
			addCriterionForJDBCDate("LAST_EXE_TIME in", values, "LAST_EXE_TIME");
			return this;
		}

		public Criteria andLAST_EXE_TIMENotIn(List values) {
			addCriterionForJDBCDate("LAST_EXE_TIME not in", values, "LAST_EXE_TIME");
			return this;
		}

		public Criteria andLAST_EXE_TIMEBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("LAST_EXE_TIME between", value1, value2, "LAST_EXE_TIME");
			return this;
		}

		public Criteria andLAST_EXE_TIMENotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("LAST_EXE_TIME not between", value1, value2, "LAST_EXE_TIME");
			return this;
		}

		public Criteria andIS_SEND_EMAILIsNull() {
			addCriterion("IS_SEND_EMAIL is null");
			return this;
		}

		public Criteria andIS_SEND_EMAILIsNotNull() {
			addCriterion("IS_SEND_EMAIL is not null");
			return this;
		}

		public Criteria andIS_SEND_EMAILEqualTo(BigDecimal value) {
			addCriterion("IS_SEND_EMAIL =", value, "IS_SEND_EMAIL");
			return this;
		}

		public Criteria andIS_SEND_EMAILNotEqualTo(BigDecimal value) {
			addCriterion("IS_SEND_EMAIL <>", value, "IS_SEND_EMAIL");
			return this;
		}

		public Criteria andIS_SEND_EMAILGreaterThan(BigDecimal value) {
			addCriterion("IS_SEND_EMAIL >", value, "IS_SEND_EMAIL");
			return this;
		}

		public Criteria andIS_SEND_EMAILGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("IS_SEND_EMAIL >=", value, "IS_SEND_EMAIL");
			return this;
		}

		public Criteria andIS_SEND_EMAILLessThan(BigDecimal value) {
			addCriterion("IS_SEND_EMAIL <", value, "IS_SEND_EMAIL");
			return this;
		}

		public Criteria andIS_SEND_EMAILLessThanOrEqualTo(BigDecimal value) {
			addCriterion("IS_SEND_EMAIL <=", value, "IS_SEND_EMAIL");
			return this;
		}

		public Criteria andIS_SEND_EMAILIn(List values) {
			addCriterion("IS_SEND_EMAIL in", values, "IS_SEND_EMAIL");
			return this;
		}

		public Criteria andIS_SEND_EMAILNotIn(List values) {
			addCriterion("IS_SEND_EMAIL not in", values, "IS_SEND_EMAIL");
			return this;
		}

		public Criteria andIS_SEND_EMAILBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("IS_SEND_EMAIL between", value1, value2, "IS_SEND_EMAIL");
			return this;
		}

		public Criteria andIS_SEND_EMAILNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("IS_SEND_EMAIL not between", value1, value2, "IS_SEND_EMAIL");
			return this;
		}

		public Criteria andEMAIL_TITLEIsNull() {
			addCriterion("EMAIL_TITLE is null");
			return this;
		}

		public Criteria andEMAIL_TITLEIsNotNull() {
			addCriterion("EMAIL_TITLE is not null");
			return this;
		}

		public Criteria andEMAIL_TITLEEqualTo(String value) {
			addCriterion("EMAIL_TITLE =", value, "EMAIL_TITLE");
			return this;
		}

		public Criteria andEMAIL_TITLENotEqualTo(String value) {
			addCriterion("EMAIL_TITLE <>", value, "EMAIL_TITLE");
			return this;
		}

		public Criteria andEMAIL_TITLEGreaterThan(String value) {
			addCriterion("EMAIL_TITLE >", value, "EMAIL_TITLE");
			return this;
		}

		public Criteria andEMAIL_TITLEGreaterThanOrEqualTo(String value) {
			addCriterion("EMAIL_TITLE >=", value, "EMAIL_TITLE");
			return this;
		}

		public Criteria andEMAIL_TITLELessThan(String value) {
			addCriterion("EMAIL_TITLE <", value, "EMAIL_TITLE");
			return this;
		}

		public Criteria andEMAIL_TITLELessThanOrEqualTo(String value) {
			addCriterion("EMAIL_TITLE <=", value, "EMAIL_TITLE");
			return this;
		}

		public Criteria andEMAIL_TITLELike(String value) {
			addCriterion("EMAIL_TITLE like", value, "EMAIL_TITLE");
			return this;
		}

		public Criteria andEMAIL_TITLENotLike(String value) {
			addCriterion("EMAIL_TITLE not like", value, "EMAIL_TITLE");
			return this;
		}

		public Criteria andEMAIL_TITLEIn(List values) {
			addCriterion("EMAIL_TITLE in", values, "EMAIL_TITLE");
			return this;
		}

		public Criteria andEMAIL_TITLENotIn(List values) {
			addCriterion("EMAIL_TITLE not in", values, "EMAIL_TITLE");
			return this;
		}

		public Criteria andEMAIL_TITLEBetween(String value1, String value2) {
			addCriterion("EMAIL_TITLE between", value1, value2, "EMAIL_TITLE");
			return this;
		}

		public Criteria andEMAIL_TITLENotBetween(String value1, String value2) {
			addCriterion("EMAIL_TITLE not between", value1, value2, "EMAIL_TITLE");
			return this;
		}

		public Criteria andENABLE_DATEIsNull() {
			addCriterion("ENABLE_DATE is null");
			return this;
		}

		public Criteria andENABLE_DATEIsNotNull() {
			addCriterion("ENABLE_DATE is not null");
			return this;
		}

		public Criteria andENABLE_DATEEqualTo(Date value) {
			addCriterionForJDBCDate("ENABLE_DATE =", value, "ENABLE_DATE");
			return this;
		}

		public Criteria andENABLE_DATENotEqualTo(Date value) {
			addCriterionForJDBCDate("ENABLE_DATE <>", value, "ENABLE_DATE");
			return this;
		}

		public Criteria andENABLE_DATEGreaterThan(Date value) {
			addCriterionForJDBCDate("ENABLE_DATE >", value, "ENABLE_DATE");
			return this;
		}

		public Criteria andENABLE_DATEGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ENABLE_DATE >=", value, "ENABLE_DATE");
			return this;
		}

		public Criteria andENABLE_DATELessThan(Date value) {
			addCriterionForJDBCDate("ENABLE_DATE <", value, "ENABLE_DATE");
			return this;
		}

		public Criteria andENABLE_DATELessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ENABLE_DATE <=", value, "ENABLE_DATE");
			return this;
		}

		public Criteria andENABLE_DATEIn(List values) {
			addCriterionForJDBCDate("ENABLE_DATE in", values, "ENABLE_DATE");
			return this;
		}

		public Criteria andENABLE_DATENotIn(List values) {
			addCriterionForJDBCDate("ENABLE_DATE not in", values, "ENABLE_DATE");
			return this;
		}

		public Criteria andENABLE_DATEBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ENABLE_DATE between", value1, value2, "ENABLE_DATE");
			return this;
		}

		public Criteria andENABLE_DATENotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ENABLE_DATE not between", value1, value2, "ENABLE_DATE");
			return this;
		}

		public Criteria andDISABLE_DATEIsNull() {
			addCriterion("DISABLE_DATE is null");
			return this;
		}

		public Criteria andDISABLE_DATEIsNotNull() {
			addCriterion("DISABLE_DATE is not null");
			return this;
		}

		public Criteria andDISABLE_DATEEqualTo(Date value) {
			addCriterionForJDBCDate("DISABLE_DATE =", value, "DISABLE_DATE");
			return this;
		}

		public Criteria andDISABLE_DATENotEqualTo(Date value) {
			addCriterionForJDBCDate("DISABLE_DATE <>", value, "DISABLE_DATE");
			return this;
		}

		public Criteria andDISABLE_DATEGreaterThan(Date value) {
			addCriterionForJDBCDate("DISABLE_DATE >", value, "DISABLE_DATE");
			return this;
		}

		public Criteria andDISABLE_DATEGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("DISABLE_DATE >=", value, "DISABLE_DATE");
			return this;
		}

		public Criteria andDISABLE_DATELessThan(Date value) {
			addCriterionForJDBCDate("DISABLE_DATE <", value, "DISABLE_DATE");
			return this;
		}

		public Criteria andDISABLE_DATELessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("DISABLE_DATE <=", value, "DISABLE_DATE");
			return this;
		}

		public Criteria andDISABLE_DATEIn(List values) {
			addCriterionForJDBCDate("DISABLE_DATE in", values, "DISABLE_DATE");
			return this;
		}

		public Criteria andDISABLE_DATENotIn(List values) {
			addCriterionForJDBCDate("DISABLE_DATE not in", values, "DISABLE_DATE");
			return this;
		}

		public Criteria andDISABLE_DATEBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("DISABLE_DATE between", value1, value2, "DISABLE_DATE");
			return this;
		}

		public Criteria andDISABLE_DATENotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("DISABLE_DATE not between", value1, value2, "DISABLE_DATE");
			return this;
		}

		public Criteria andDESCRIPTIONIsNull() {
			addCriterion("DESCRIPTION is null");
			return this;
		}

		public Criteria andDESCRIPTIONIsNotNull() {
			addCriterion("DESCRIPTION is not null");
			return this;
		}

		public Criteria andDESCRIPTIONEqualTo(String value) {
			addCriterion("DESCRIPTION =", value, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONNotEqualTo(String value) {
			addCriterion("DESCRIPTION <>", value, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONGreaterThan(String value) {
			addCriterion("DESCRIPTION >", value, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONGreaterThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION >=", value, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONLessThan(String value) {
			addCriterion("DESCRIPTION <", value, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONLessThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION <=", value, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONLike(String value) {
			addCriterion("DESCRIPTION like", value, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONNotLike(String value) {
			addCriterion("DESCRIPTION not like", value, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONIn(List values) {
			addCriterion("DESCRIPTION in", values, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONNotIn(List values) {
			addCriterion("DESCRIPTION not in", values, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONBetween(String value1, String value2) {
			addCriterion("DESCRIPTION between", value1, value2, "DESCRIPTION");
			return this;
		}

		public Criteria andDESCRIPTIONNotBetween(String value1, String value2) {
			addCriterion("DESCRIPTION not between", value1, value2, "DESCRIPTION");
			return this;
		}

		public Criteria andATTRIBUTE1IsNull() {
			addCriterion("ATTRIBUTE1 is null");
			return this;
		}

		public Criteria andATTRIBUTE1IsNotNull() {
			addCriterion("ATTRIBUTE1 is not null");
			return this;
		}

		public Criteria andATTRIBUTE1EqualTo(String value) {
			addCriterion("ATTRIBUTE1 =", value, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1NotEqualTo(String value) {
			addCriterion("ATTRIBUTE1 <>", value, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1GreaterThan(String value) {
			addCriterion("ATTRIBUTE1 >", value, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1GreaterThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE1 >=", value, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1LessThan(String value) {
			addCriterion("ATTRIBUTE1 <", value, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1LessThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE1 <=", value, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1Like(String value) {
			addCriterion("ATTRIBUTE1 like", value, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1NotLike(String value) {
			addCriterion("ATTRIBUTE1 not like", value, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1In(List values) {
			addCriterion("ATTRIBUTE1 in", values, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1NotIn(List values) {
			addCriterion("ATTRIBUTE1 not in", values, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1Between(String value1, String value2) {
			addCriterion("ATTRIBUTE1 between", value1, value2, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE1NotBetween(String value1, String value2) {
			addCriterion("ATTRIBUTE1 not between", value1, value2, "ATTRIBUTE1");
			return this;
		}

		public Criteria andATTRIBUTE2IsNull() {
			addCriterion("ATTRIBUTE2 is null");
			return this;
		}

		public Criteria andATTRIBUTE2IsNotNull() {
			addCriterion("ATTRIBUTE2 is not null");
			return this;
		}

		public Criteria andATTRIBUTE2EqualTo(String value) {
			addCriterion("ATTRIBUTE2 =", value, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2NotEqualTo(String value) {
			addCriterion("ATTRIBUTE2 <>", value, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2GreaterThan(String value) {
			addCriterion("ATTRIBUTE2 >", value, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2GreaterThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE2 >=", value, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2LessThan(String value) {
			addCriterion("ATTRIBUTE2 <", value, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2LessThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE2 <=", value, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2Like(String value) {
			addCriterion("ATTRIBUTE2 like", value, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2NotLike(String value) {
			addCriterion("ATTRIBUTE2 not like", value, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2In(List values) {
			addCriterion("ATTRIBUTE2 in", values, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2NotIn(List values) {
			addCriterion("ATTRIBUTE2 not in", values, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2Between(String value1, String value2) {
			addCriterion("ATTRIBUTE2 between", value1, value2, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE2NotBetween(String value1, String value2) {
			addCriterion("ATTRIBUTE2 not between", value1, value2, "ATTRIBUTE2");
			return this;
		}

		public Criteria andATTRIBUTE3IsNull() {
			addCriterion("ATTRIBUTE3 is null");
			return this;
		}

		public Criteria andATTRIBUTE3IsNotNull() {
			addCriterion("ATTRIBUTE3 is not null");
			return this;
		}

		public Criteria andATTRIBUTE3EqualTo(String value) {
			addCriterion("ATTRIBUTE3 =", value, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3NotEqualTo(String value) {
			addCriterion("ATTRIBUTE3 <>", value, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3GreaterThan(String value) {
			addCriterion("ATTRIBUTE3 >", value, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3GreaterThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE3 >=", value, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3LessThan(String value) {
			addCriterion("ATTRIBUTE3 <", value, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3LessThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE3 <=", value, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3Like(String value) {
			addCriterion("ATTRIBUTE3 like", value, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3NotLike(String value) {
			addCriterion("ATTRIBUTE3 not like", value, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3In(List values) {
			addCriterion("ATTRIBUTE3 in", values, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3NotIn(List values) {
			addCriterion("ATTRIBUTE3 not in", values, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3Between(String value1, String value2) {
			addCriterion("ATTRIBUTE3 between", value1, value2, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE3NotBetween(String value1, String value2) {
			addCriterion("ATTRIBUTE3 not between", value1, value2, "ATTRIBUTE3");
			return this;
		}

		public Criteria andATTRIBUTE4IsNull() {
			addCriterion("ATTRIBUTE4 is null");
			return this;
		}

		public Criteria andATTRIBUTE4IsNotNull() {
			addCriterion("ATTRIBUTE4 is not null");
			return this;
		}

		public Criteria andATTRIBUTE4EqualTo(String value) {
			addCriterion("ATTRIBUTE4 =", value, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4NotEqualTo(String value) {
			addCriterion("ATTRIBUTE4 <>", value, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4GreaterThan(String value) {
			addCriterion("ATTRIBUTE4 >", value, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4GreaterThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE4 >=", value, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4LessThan(String value) {
			addCriterion("ATTRIBUTE4 <", value, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4LessThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE4 <=", value, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4Like(String value) {
			addCriterion("ATTRIBUTE4 like", value, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4NotLike(String value) {
			addCriterion("ATTRIBUTE4 not like", value, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4In(List values) {
			addCriterion("ATTRIBUTE4 in", values, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4NotIn(List values) {
			addCriterion("ATTRIBUTE4 not in", values, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4Between(String value1, String value2) {
			addCriterion("ATTRIBUTE4 between", value1, value2, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE4NotBetween(String value1, String value2) {
			addCriterion("ATTRIBUTE4 not between", value1, value2, "ATTRIBUTE4");
			return this;
		}

		public Criteria andATTRIBUTE5IsNull() {
			addCriterion("ATTRIBUTE5 is null");
			return this;
		}

		public Criteria andATTRIBUTE5IsNotNull() {
			addCriterion("ATTRIBUTE5 is not null");
			return this;
		}

		public Criteria andATTRIBUTE5EqualTo(String value) {
			addCriterion("ATTRIBUTE5 =", value, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5NotEqualTo(String value) {
			addCriterion("ATTRIBUTE5 <>", value, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5GreaterThan(String value) {
			addCriterion("ATTRIBUTE5 >", value, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5GreaterThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE5 >=", value, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5LessThan(String value) {
			addCriterion("ATTRIBUTE5 <", value, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5LessThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE5 <=", value, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5Like(String value) {
			addCriterion("ATTRIBUTE5 like", value, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5NotLike(String value) {
			addCriterion("ATTRIBUTE5 not like", value, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5In(List values) {
			addCriterion("ATTRIBUTE5 in", values, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5NotIn(List values) {
			addCriterion("ATTRIBUTE5 not in", values, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5Between(String value1, String value2) {
			addCriterion("ATTRIBUTE5 between", value1, value2, "ATTRIBUTE5");
			return this;
		}

		public Criteria andATTRIBUTE5NotBetween(String value1, String value2) {
			addCriterion("ATTRIBUTE5 not between", value1, value2, "ATTRIBUTE5");
			return this;
		}

		public Criteria andCREATED_BYIsNull() {
			addCriterion("CREATED_BY is null");
			return this;
		}

		public Criteria andCREATED_BYIsNotNull() {
			addCriterion("CREATED_BY is not null");
			return this;
		}

		public Criteria andCREATED_BYEqualTo(BigDecimal value) {
			addCriterion("CREATED_BY =", value, "CREATED_BY");
			return this;
		}

		public Criteria andCREATED_BYNotEqualTo(BigDecimal value) {
			addCriterion("CREATED_BY <>", value, "CREATED_BY");
			return this;
		}

		public Criteria andCREATED_BYGreaterThan(BigDecimal value) {
			addCriterion("CREATED_BY >", value, "CREATED_BY");
			return this;
		}

		public Criteria andCREATED_BYGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("CREATED_BY >=", value, "CREATED_BY");
			return this;
		}

		public Criteria andCREATED_BYLessThan(BigDecimal value) {
			addCriterion("CREATED_BY <", value, "CREATED_BY");
			return this;
		}

		public Criteria andCREATED_BYLessThanOrEqualTo(BigDecimal value) {
			addCriterion("CREATED_BY <=", value, "CREATED_BY");
			return this;
		}

		public Criteria andCREATED_BYIn(List values) {
			addCriterion("CREATED_BY in", values, "CREATED_BY");
			return this;
		}

		public Criteria andCREATED_BYNotIn(List values) {
			addCriterion("CREATED_BY not in", values, "CREATED_BY");
			return this;
		}

		public Criteria andCREATED_BYBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("CREATED_BY between", value1, value2, "CREATED_BY");
			return this;
		}

		public Criteria andCREATED_BYNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("CREATED_BY not between", value1, value2, "CREATED_BY");
			return this;
		}

		public Criteria andCREATION_DATEIsNull() {
			addCriterion("CREATION_DATE is null");
			return this;
		}

		public Criteria andCREATION_DATEIsNotNull() {
			addCriterion("CREATION_DATE is not null");
			return this;
		}

		public Criteria andCREATION_DATEEqualTo(Date value) {
			addCriterionForJDBCDate("CREATION_DATE =", value, "CREATION_DATE");
			return this;
		}

		public Criteria andCREATION_DATENotEqualTo(Date value) {
			addCriterionForJDBCDate("CREATION_DATE <>", value, "CREATION_DATE");
			return this;
		}

		public Criteria andCREATION_DATEGreaterThan(Date value) {
			addCriterionForJDBCDate("CREATION_DATE >", value, "CREATION_DATE");
			return this;
		}

		public Criteria andCREATION_DATEGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATION_DATE >=", value, "CREATION_DATE");
			return this;
		}

		public Criteria andCREATION_DATELessThan(Date value) {
			addCriterionForJDBCDate("CREATION_DATE <", value, "CREATION_DATE");
			return this;
		}

		public Criteria andCREATION_DATELessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATION_DATE <=", value, "CREATION_DATE");
			return this;
		}

		public Criteria andCREATION_DATEIn(List values) {
			addCriterionForJDBCDate("CREATION_DATE in", values, "CREATION_DATE");
			return this;
		}

		public Criteria andCREATION_DATENotIn(List values) {
			addCriterionForJDBCDate("CREATION_DATE not in", values, "CREATION_DATE");
			return this;
		}

		public Criteria andCREATION_DATEBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATION_DATE between", value1, value2, "CREATION_DATE");
			return this;
		}

		public Criteria andCREATION_DATENotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATION_DATE not between", value1, value2, "CREATION_DATE");
			return this;
		}

		public Criteria andLAST_UPDATED_BYIsNull() {
			addCriterion("LAST_UPDATED_BY is null");
			return this;
		}

		public Criteria andLAST_UPDATED_BYIsNotNull() {
			addCriterion("LAST_UPDATED_BY is not null");
			return this;
		}

		public Criteria andLAST_UPDATED_BYEqualTo(BigDecimal value) {
			addCriterion("LAST_UPDATED_BY =", value, "LAST_UPDATED_BY");
			return this;
		}

		public Criteria andLAST_UPDATED_BYNotEqualTo(BigDecimal value) {
			addCriterion("LAST_UPDATED_BY <>", value, "LAST_UPDATED_BY");
			return this;
		}

		public Criteria andLAST_UPDATED_BYGreaterThan(BigDecimal value) {
			addCriterion("LAST_UPDATED_BY >", value, "LAST_UPDATED_BY");
			return this;
		}

		public Criteria andLAST_UPDATED_BYGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("LAST_UPDATED_BY >=", value, "LAST_UPDATED_BY");
			return this;
		}

		public Criteria andLAST_UPDATED_BYLessThan(BigDecimal value) {
			addCriterion("LAST_UPDATED_BY <", value, "LAST_UPDATED_BY");
			return this;
		}

		public Criteria andLAST_UPDATED_BYLessThanOrEqualTo(BigDecimal value) {
			addCriterion("LAST_UPDATED_BY <=", value, "LAST_UPDATED_BY");
			return this;
		}

		public Criteria andLAST_UPDATED_BYIn(List values) {
			addCriterion("LAST_UPDATED_BY in", values, "LAST_UPDATED_BY");
			return this;
		}

		public Criteria andLAST_UPDATED_BYNotIn(List values) {
			addCriterion("LAST_UPDATED_BY not in", values, "LAST_UPDATED_BY");
			return this;
		}

		public Criteria andLAST_UPDATED_BYBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("LAST_UPDATED_BY between", value1, value2, "LAST_UPDATED_BY");
			return this;
		}

		public Criteria andLAST_UPDATED_BYNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("LAST_UPDATED_BY not between", value1, value2, "LAST_UPDATED_BY");
			return this;
		}

		public Criteria andLAST_UPDATE_DATEIsNull() {
			addCriterion("LAST_UPDATE_DATE is null");
			return this;
		}

		public Criteria andLAST_UPDATE_DATEIsNotNull() {
			addCriterion("LAST_UPDATE_DATE is not null");
			return this;
		}

		public Criteria andLAST_UPDATE_DATEEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_UPDATE_DATE =", value, "LAST_UPDATE_DATE");
			return this;
		}

		public Criteria andLAST_UPDATE_DATENotEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_UPDATE_DATE <>", value, "LAST_UPDATE_DATE");
			return this;
		}

		public Criteria andLAST_UPDATE_DATEGreaterThan(Date value) {
			addCriterionForJDBCDate("LAST_UPDATE_DATE >", value, "LAST_UPDATE_DATE");
			return this;
		}

		public Criteria andLAST_UPDATE_DATEGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_UPDATE_DATE >=", value, "LAST_UPDATE_DATE");
			return this;
		}

		public Criteria andLAST_UPDATE_DATELessThan(Date value) {
			addCriterionForJDBCDate("LAST_UPDATE_DATE <", value, "LAST_UPDATE_DATE");
			return this;
		}

		public Criteria andLAST_UPDATE_DATELessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_UPDATE_DATE <=", value, "LAST_UPDATE_DATE");
			return this;
		}

		public Criteria andLAST_UPDATE_DATEIn(List values) {
			addCriterionForJDBCDate("LAST_UPDATE_DATE in", values, "LAST_UPDATE_DATE");
			return this;
		}

		public Criteria andLAST_UPDATE_DATENotIn(List values) {
			addCriterionForJDBCDate("LAST_UPDATE_DATE not in", values, "LAST_UPDATE_DATE");
			return this;
		}

		public Criteria andLAST_UPDATE_DATEBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("LAST_UPDATE_DATE between", value1, value2, "LAST_UPDATE_DATE");
			return this;
		}

		public Criteria andLAST_UPDATE_DATENotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("LAST_UPDATE_DATE not between", value1, value2, "LAST_UPDATE_DATE");
			return this;
		}

		public Criteria andSTATUSIsNull() {
			addCriterion("STATUS is null");
			return this;
		}

		public Criteria andSTATUSIsNotNull() {
			addCriterion("STATUS is not null");
			return this;
		}

		public Criteria andSTATUSEqualTo(String value) {
			addCriterion("STATUS =", value, "STATUS");
			return this;
		}

		public Criteria andSTATUSNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "STATUS");
			return this;
		}

		public Criteria andSTATUSGreaterThan(String value) {
			addCriterion("STATUS >", value, "STATUS");
			return this;
		}

		public Criteria andSTATUSGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "STATUS");
			return this;
		}

		public Criteria andSTATUSLessThan(String value) {
			addCriterion("STATUS <", value, "STATUS");
			return this;
		}

		public Criteria andSTATUSLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "STATUS");
			return this;
		}

		public Criteria andSTATUSLike(String value) {
			addCriterion("STATUS like", value, "STATUS");
			return this;
		}

		public Criteria andSTATUSNotLike(String value) {
			addCriterion("STATUS not like", value, "STATUS");
			return this;
		}

		public Criteria andSTATUSIn(List values) {
			addCriterion("STATUS in", values, "STATUS");
			return this;
		}

		public Criteria andSTATUSNotIn(List values) {
			addCriterion("STATUS not in", values, "STATUS");
			return this;
		}

		public Criteria andSTATUSBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "STATUS");
			return this;
		}

		public Criteria andSTATUSNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "STATUS");
			return this;
		}

		public Criteria andNODE_STATUSIsNull() {
			addCriterion("NODE_STATUS is null");
			return this;
		}

		public Criteria andNODE_STATUSIsNotNull() {
			addCriterion("NODE_STATUS is not null");
			return this;
		}

		public Criteria andNODE_STATUSEqualTo(String value) {
			addCriterion("NODE_STATUS =", value, "NODE_STATUS");
			return this;
		}

		public Criteria andNODE_STATUSNotEqualTo(String value) {
			addCriterion("NODE_STATUS <>", value, "NODE_STATUS");
			return this;
		}

		public Criteria andNODE_STATUSGreaterThan(String value) {
			addCriterion("NODE_STATUS >", value, "NODE_STATUS");
			return this;
		}

		public Criteria andNODE_STATUSGreaterThanOrEqualTo(String value) {
			addCriterion("NODE_STATUS >=", value, "NODE_STATUS");
			return this;
		}

		public Criteria andNODE_STATUSLessThan(String value) {
			addCriterion("NODE_STATUS <", value, "NODE_STATUS");
			return this;
		}

		public Criteria andNODE_STATUSLessThanOrEqualTo(String value) {
			addCriterion("NODE_STATUS <=", value, "NODE_STATUS");
			return this;
		}

		public Criteria andNODE_STATUSLike(String value) {
			addCriterion("NODE_STATUS like", value, "NODE_STATUS");
			return this;
		}

		public Criteria andNODE_STATUSNotLike(String value) {
			addCriterion("NODE_STATUS not like", value, "NODE_STATUS");
			return this;
		}

		public Criteria andNODE_STATUSIn(List values) {
			addCriterion("NODE_STATUS in", values, "NODE_STATUS");
			return this;
		}

		public Criteria andNODE_STATUSNotIn(List values) {
			addCriterion("NODE_STATUS not in", values, "NODE_STATUS");
			return this;
		}

		public Criteria andNODE_STATUSBetween(String value1, String value2) {
			addCriterion("NODE_STATUS between", value1, value2, "NODE_STATUS");
			return this;
		}

		public Criteria andNODE_STATUSNotBetween(String value1, String value2) {
			addCriterion("NODE_STATUS not between", value1, value2, "NODE_STATUS");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_VALUEIsNull() {
			addCriterion("TASK_EXE_CYCLE_VALUE is null");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_VALUEIsNotNull() {
			addCriterion("TASK_EXE_CYCLE_VALUE is not null");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_VALUEEqualTo(BigDecimal value) {
			addCriterion("TASK_EXE_CYCLE_VALUE =", value, "TASK_EXE_CYCLE_VALUE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_VALUENotEqualTo(BigDecimal value) {
			addCriterion("TASK_EXE_CYCLE_VALUE <>", value, "TASK_EXE_CYCLE_VALUE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_VALUEGreaterThan(BigDecimal value) {
			addCriterion("TASK_EXE_CYCLE_VALUE >", value, "TASK_EXE_CYCLE_VALUE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_VALUEGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("TASK_EXE_CYCLE_VALUE >=", value, "TASK_EXE_CYCLE_VALUE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_VALUELessThan(BigDecimal value) {
			addCriterion("TASK_EXE_CYCLE_VALUE <", value, "TASK_EXE_CYCLE_VALUE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_VALUELessThanOrEqualTo(BigDecimal value) {
			addCriterion("TASK_EXE_CYCLE_VALUE <=", value, "TASK_EXE_CYCLE_VALUE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_VALUEIn(List values) {
			addCriterion("TASK_EXE_CYCLE_VALUE in", values, "TASK_EXE_CYCLE_VALUE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_VALUENotIn(List values) {
			addCriterion("TASK_EXE_CYCLE_VALUE not in", values, "TASK_EXE_CYCLE_VALUE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_VALUEBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("TASK_EXE_CYCLE_VALUE between", value1, value2, "TASK_EXE_CYCLE_VALUE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_VALUENotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("TASK_EXE_CYCLE_VALUE not between", value1, value2, "TASK_EXE_CYCLE_VALUE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_TYPEIsNull() {
			addCriterion("TASK_EXE_CYCLE_TYPE is null");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_TYPEIsNotNull() {
			addCriterion("TASK_EXE_CYCLE_TYPE is not null");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_TYPEEqualTo(String value) {
			addCriterion("TASK_EXE_CYCLE_TYPE =", value, "TASK_EXE_CYCLE_TYPE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_TYPENotEqualTo(String value) {
			addCriterion("TASK_EXE_CYCLE_TYPE <>", value, "TASK_EXE_CYCLE_TYPE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_TYPEGreaterThan(String value) {
			addCriterion("TASK_EXE_CYCLE_TYPE >", value, "TASK_EXE_CYCLE_TYPE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_TYPEGreaterThanOrEqualTo(String value) {
			addCriterion("TASK_EXE_CYCLE_TYPE >=", value, "TASK_EXE_CYCLE_TYPE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_TYPELessThan(String value) {
			addCriterion("TASK_EXE_CYCLE_TYPE <", value, "TASK_EXE_CYCLE_TYPE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_TYPELessThanOrEqualTo(String value) {
			addCriterion("TASK_EXE_CYCLE_TYPE <=", value, "TASK_EXE_CYCLE_TYPE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_TYPELike(String value) {
			addCriterion("TASK_EXE_CYCLE_TYPE like", value, "TASK_EXE_CYCLE_TYPE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_TYPENotLike(String value) {
			addCriterion("TASK_EXE_CYCLE_TYPE not like", value, "TASK_EXE_CYCLE_TYPE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_TYPEIn(List values) {
			addCriterion("TASK_EXE_CYCLE_TYPE in", values, "TASK_EXE_CYCLE_TYPE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_TYPENotIn(List values) {
			addCriterion("TASK_EXE_CYCLE_TYPE not in", values, "TASK_EXE_CYCLE_TYPE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_TYPEBetween(String value1, String value2) {
			addCriterion("TASK_EXE_CYCLE_TYPE between", value1, value2, "TASK_EXE_CYCLE_TYPE");
			return this;
		}

		public Criteria andTASK_EXE_CYCLE_TYPENotBetween(String value1, String value2) {
			addCriterion("TASK_EXE_CYCLE_TYPE not between", value1, value2, "TASK_EXE_CYCLE_TYPE");
			return this;
		}

		public Criteria andTASK_EXE_DATEIsNull() {
			addCriterion("TASK_EXE_DATE is null");
			return this;
		}

		public Criteria andTASK_EXE_DATEIsNotNull() {
			addCriterion("TASK_EXE_DATE is not null");
			return this;
		}

		public Criteria andTASK_EXE_DATEEqualTo(Date value) {
			addCriterionForJDBCDate("TASK_EXE_DATE =", value, "TASK_EXE_DATE");
			return this;
		}

		public Criteria andTASK_EXE_DATENotEqualTo(Date value) {
			addCriterionForJDBCDate("TASK_EXE_DATE <>", value, "TASK_EXE_DATE");
			return this;
		}

		public Criteria andTASK_EXE_DATEGreaterThan(Date value) {
			addCriterionForJDBCDate("TASK_EXE_DATE >", value, "TASK_EXE_DATE");
			return this;
		}

		public Criteria andTASK_EXE_DATEGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("TASK_EXE_DATE >=", value, "TASK_EXE_DATE");
			return this;
		}

		public Criteria andTASK_EXE_DATELessThan(Date value) {
			addCriterionForJDBCDate("TASK_EXE_DATE <", value, "TASK_EXE_DATE");
			return this;
		}

		public Criteria andTASK_EXE_DATELessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("TASK_EXE_DATE <=", value, "TASK_EXE_DATE");
			return this;
		}

		public Criteria andTASK_EXE_DATEIn(List values) {
			addCriterionForJDBCDate("TASK_EXE_DATE in", values, "TASK_EXE_DATE");
			return this;
		}

		public Criteria andTASK_EXE_DATENotIn(List values) {
			addCriterionForJDBCDate("TASK_EXE_DATE not in", values, "TASK_EXE_DATE");
			return this;
		}

		public Criteria andTASK_EXE_DATEBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("TASK_EXE_DATE between", value1, value2, "TASK_EXE_DATE");
			return this;
		}

		public Criteria andTASK_EXE_DATENotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("TASK_EXE_DATE not between", value1, value2, "TASK_EXE_DATE");
			return this;
		}

		public Criteria andWEEKDAY_VALUEIsNull() {
			addCriterion("WEEKDAY_VALUE is null");
			return this;
		}

		public Criteria andWEEKDAY_VALUEIsNotNull() {
			addCriterion("WEEKDAY_VALUE is not null");
			return this;
		}

		public Criteria andWEEKDAY_VALUEEqualTo(String value) {
			addCriterion("WEEKDAY_VALUE =", value, "WEEKDAY_VALUE");
			return this;
		}

		public Criteria andWEEKDAY_VALUENotEqualTo(String value) {
			addCriterion("WEEKDAY_VALUE <>", value, "WEEKDAY_VALUE");
			return this;
		}

		public Criteria andWEEKDAY_VALUEGreaterThan(String value) {
			addCriterion("WEEKDAY_VALUE >", value, "WEEKDAY_VALUE");
			return this;
		}

		public Criteria andWEEKDAY_VALUEGreaterThanOrEqualTo(String value) {
			addCriterion("WEEKDAY_VALUE >=", value, "WEEKDAY_VALUE");
			return this;
		}

		public Criteria andWEEKDAY_VALUELessThan(String value) {
			addCriterion("WEEKDAY_VALUE <", value, "WEEKDAY_VALUE");
			return this;
		}

		public Criteria andWEEKDAY_VALUELessThanOrEqualTo(String value) {
			addCriterion("WEEKDAY_VALUE <=", value, "WEEKDAY_VALUE");
			return this;
		}

		public Criteria andWEEKDAY_VALUELike(String value) {
			addCriterion("WEEKDAY_VALUE like", value, "WEEKDAY_VALUE");
			return this;
		}

		public Criteria andWEEKDAY_VALUENotLike(String value) {
			addCriterion("WEEKDAY_VALUE not like", value, "WEEKDAY_VALUE");
			return this;
		}

		public Criteria andWEEKDAY_VALUEIn(List values) {
			addCriterion("WEEKDAY_VALUE in", values, "WEEKDAY_VALUE");
			return this;
		}

		public Criteria andWEEKDAY_VALUENotIn(List values) {
			addCriterion("WEEKDAY_VALUE not in", values, "WEEKDAY_VALUE");
			return this;
		}

		public Criteria andWEEKDAY_VALUEBetween(String value1, String value2) {
			addCriterion("WEEKDAY_VALUE between", value1, value2, "WEEKDAY_VALUE");
			return this;
		}

		public Criteria andWEEKDAY_VALUENotBetween(String value1, String value2) {
			addCriterion("WEEKDAY_VALUE not between", value1, value2, "WEEKDAY_VALUE");
			return this;
		}

		public Criteria andWORKDAY_EXEIsNull() {
			addCriterion("WORKDAY_EXE is null");
			return this;
		}

		public Criteria andWORKDAY_EXEIsNotNull() {
			addCriterion("WORKDAY_EXE is not null");
			return this;
		}

		public Criteria andWORKDAY_EXEEqualTo(String value) {
			addCriterion("WORKDAY_EXE =", value, "WORKDAY_EXE");
			return this;
		}

		public Criteria andWORKDAY_EXENotEqualTo(String value) {
			addCriterion("WORKDAY_EXE <>", value, "WORKDAY_EXE");
			return this;
		}

		public Criteria andWORKDAY_EXEGreaterThan(String value) {
			addCriterion("WORKDAY_EXE >", value, "WORKDAY_EXE");
			return this;
		}

		public Criteria andWORKDAY_EXEGreaterThanOrEqualTo(String value) {
			addCriterion("WORKDAY_EXE >=", value, "WORKDAY_EXE");
			return this;
		}

		public Criteria andWORKDAY_EXELessThan(String value) {
			addCriterion("WORKDAY_EXE <", value, "WORKDAY_EXE");
			return this;
		}

		public Criteria andWORKDAY_EXELessThanOrEqualTo(String value) {
			addCriterion("WORKDAY_EXE <=", value, "WORKDAY_EXE");
			return this;
		}

		public Criteria andWORKDAY_EXELike(String value) {
			addCriterion("WORKDAY_EXE like", value, "WORKDAY_EXE");
			return this;
		}

		public Criteria andWORKDAY_EXENotLike(String value) {
			addCriterion("WORKDAY_EXE not like", value, "WORKDAY_EXE");
			return this;
		}

		public Criteria andWORKDAY_EXEIn(List values) {
			addCriterion("WORKDAY_EXE in", values, "WORKDAY_EXE");
			return this;
		}

		public Criteria andWORKDAY_EXENotIn(List values) {
			addCriterion("WORKDAY_EXE not in", values, "WORKDAY_EXE");
			return this;
		}

		public Criteria andWORKDAY_EXEBetween(String value1, String value2) {
			addCriterion("WORKDAY_EXE between", value1, value2, "WORKDAY_EXE");
			return this;
		}

		public Criteria andWORKDAY_EXENotBetween(String value1, String value2) {
			addCriterion("WORKDAY_EXE not between", value1, value2, "WORKDAY_EXE");
			return this;
		}
	}
}