package com.notice.model;

import java.math.BigDecimal;
import java.util.Date;

public class SysTaskPageAll {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TASK_PAGE_ALL.PAGE_ID
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    private BigDecimal PAGE_ID;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TASK_PAGE_ALL.TASK_ID
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    private BigDecimal TASK_ID;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TASK_PAGE_ALL.PAGE_NAME
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    private String PAGE_NAME;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TASK_PAGE_ALL.DISABLED
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    private String DISABLED;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TASK_PAGE_ALL.DESCRIPTION
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    private String DESCRIPTION;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TASK_PAGE_ALL.CREATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    private BigDecimal CREATED_BY;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TASK_PAGE_ALL.CREATION_DATE
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    private Date CREATION_DATE;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TASK_PAGE_ALL.LAST_UPDATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    private BigDecimal LAST_UPDATED_BY;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TASK_PAGE_ALL.LAST_UPDATE_DATE
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    private Date LAST_UPDATE_DATE;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TASK_PAGE_ALL.PAGE_ID
     *
     * @return the value of SYS_TASK_PAGE_ALL.PAGE_ID
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    public BigDecimal getPAGE_ID() {
        return PAGE_ID;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TASK_PAGE_ALL.PAGE_ID
     *
     * @param PAGE_ID the value for SYS_TASK_PAGE_ALL.PAGE_ID
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    public void setPAGE_ID(BigDecimal PAGE_ID) {
        this.PAGE_ID = PAGE_ID;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TASK_PAGE_ALL.TASK_ID
     *
     * @return the value of SYS_TASK_PAGE_ALL.TASK_ID
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    public BigDecimal getTASK_ID() {
        return TASK_ID;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TASK_PAGE_ALL.TASK_ID
     *
     * @param TASK_ID the value for SYS_TASK_PAGE_ALL.TASK_ID
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    public void setTASK_ID(BigDecimal TASK_ID) {
        this.TASK_ID = TASK_ID;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TASK_PAGE_ALL.PAGE_NAME
     *
     * @return the value of SYS_TASK_PAGE_ALL.PAGE_NAME
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    public String getPAGE_NAME() {
        return PAGE_NAME;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TASK_PAGE_ALL.PAGE_NAME
     *
     * @param PAGE_NAME the value for SYS_TASK_PAGE_ALL.PAGE_NAME
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    public void setPAGE_NAME(String PAGE_NAME) {
        this.PAGE_NAME = PAGE_NAME;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TASK_PAGE_ALL.DISABLED
     *
     * @return the value of SYS_TASK_PAGE_ALL.DISABLED
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    public String getDISABLED() {
        return DISABLED;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TASK_PAGE_ALL.DISABLED
     *
     * @param DISABLED the value for SYS_TASK_PAGE_ALL.DISABLED
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    public void setDISABLED(String DISABLED) {
        this.DISABLED = DISABLED;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TASK_PAGE_ALL.DESCRIPTION
     *
     * @return the value of SYS_TASK_PAGE_ALL.DESCRIPTION
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TASK_PAGE_ALL.DESCRIPTION
     *
     * @param DESCRIPTION the value for SYS_TASK_PAGE_ALL.DESCRIPTION
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TASK_PAGE_ALL.CREATED_BY
     *
     * @return the value of SYS_TASK_PAGE_ALL.CREATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    public BigDecimal getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TASK_PAGE_ALL.CREATED_BY
     *
     * @param CREATED_BY the value for SYS_TASK_PAGE_ALL.CREATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    public void setCREATED_BY(BigDecimal CREATED_BY) {
        this.CREATED_BY = CREATED_BY;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TASK_PAGE_ALL.CREATION_DATE
     *
     * @return the value of SYS_TASK_PAGE_ALL.CREATION_DATE
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    public Date getCREATION_DATE() {
        return CREATION_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TASK_PAGE_ALL.CREATION_DATE
     *
     * @param CREATION_DATE the value for SYS_TASK_PAGE_ALL.CREATION_DATE
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    public void setCREATION_DATE(Date CREATION_DATE) {
        this.CREATION_DATE = CREATION_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TASK_PAGE_ALL.LAST_UPDATED_BY
     *
     * @return the value of SYS_TASK_PAGE_ALL.LAST_UPDATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    public BigDecimal getLAST_UPDATED_BY() {
        return LAST_UPDATED_BY;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TASK_PAGE_ALL.LAST_UPDATED_BY
     *
     * @param LAST_UPDATED_BY the value for SYS_TASK_PAGE_ALL.LAST_UPDATED_BY
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    public void setLAST_UPDATED_BY(BigDecimal LAST_UPDATED_BY) {
        this.LAST_UPDATED_BY = LAST_UPDATED_BY;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TASK_PAGE_ALL.LAST_UPDATE_DATE
     *
     * @return the value of SYS_TASK_PAGE_ALL.LAST_UPDATE_DATE
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    public Date getLAST_UPDATE_DATE() {
        return LAST_UPDATE_DATE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TASK_PAGE_ALL.LAST_UPDATE_DATE
     *
     * @param LAST_UPDATE_DATE the value for SYS_TASK_PAGE_ALL.LAST_UPDATE_DATE
     *
     * @abatorgenerated Fri May 24 18:30:16 CST 2013
     */
    public void setLAST_UPDATE_DATE(Date LAST_UPDATE_DATE) {
        this.LAST_UPDATE_DATE = LAST_UPDATE_DATE;
    }
}